workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    bolt-python-api:
        inputs:
            - location: https://assets.bolt.com/external-api-references/bolt.yml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/bolt/boltpublicapi/bolt-python-api
targets:
    bolt-sdk:
        target: python
        source: bolt-python-api
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/bolt/boltpublicapi/bolt-python-api-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
