"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.errors import BoltError
from bolt_api_sdk.models import (
    v1_error as models_v1_error,
    v1_webhookerror as models_v1_webhookerror,
)
from bolt_api_sdk.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class V1WebhookErrorData(BaseModel):
    status: models_v1_webhookerror.V1WebhookErrorStatus

    error: Optional[models_v1_error.V1Error] = None


@dataclass(frozen=True)
class V1WebhookError(BoltError):
    r"""Webhooks Transaction Response"""

    data: V1WebhookErrorData = field(hash=False)

    def __init__(
        self,
        data: V1WebhookErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
