"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt.types import BaseModel
from datetime import datetime
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SubscriptionOrderStatus(str, Enum):
    SCHEDULED = "scheduled"
    ACTIVE = "active"
    CANCELED = "canceled"


class SubscriptionOrderTypedDict(TypedDict):
    id: NotRequired[str]
    r"""unique identifier for the subscription order."""
    subscription_id: NotRequired[str]
    r"""ID of the subscription associated with the order."""
    order_id: NotRequired[str]
    r"""ID of the order."""
    placement_time: NotRequired[datetime]
    status: NotRequired[SubscriptionOrderStatus]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class SubscriptionOrder(BaseModel):
    id: Optional[str] = None
    r"""unique identifier for the subscription order."""

    subscription_id: Optional[str] = None
    r"""ID of the subscription associated with the order."""

    order_id: Optional[str] = None
    r"""ID of the order."""

    placement_time: Optional[datetime] = None

    status: Optional[SubscriptionOrderStatus] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None
