"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from bolt_api_sdk.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .account_details import (
        AccountDetails,
        AccountDetailsTypedDict,
        PaymentMethod,
        PaymentMethodTypedDict,
    )
    from .account_details_address_view import (
        AccountDetailsAddressView,
        AccountDetailsAddressViewPriority,
        AccountDetailsAddressViewTypedDict,
    )
    from .account_identifier_status import AccountIdentifierStatus
    from .addaddressop import (
        AddAddressPriority,
        AddAddressRequest,
        AddAddressRequestTypedDict,
        AddAddressResponse,
        AddAddressResponseTypedDict,
        AddAddressSecurity,
        AddAddressSecurityTypedDict,
    )
    from .addpaymentmethodop import (
        AddPaymentMethodNetwork,
        AddPaymentMethodPriority,
        AddPaymentMethodRequest,
        AddPaymentMethodRequestBody,
        AddPaymentMethodRequestBodyTypedDict,
        AddPaymentMethodRequestTypedDict,
        AddPaymentMethodSecurity,
        AddPaymentMethodSecurityTypedDict,
        AddPaymentMethodTokenType,
    )
    from .address import Address, AddressTypedDict
    from .address_account import AddressAccount, AddressAccountTypedDict
    from .address_change_request_metadata_view import (
        AddressChangeRequestMetadataView,
        AddressChangeRequestMetadataViewTypedDict,
    )
    from .address_change_view import AddressChangeView, AddressChangeViewTypedDict
    from .address_view import AddressView, AddressViewPriority, AddressViewTypedDict
    from .amount_view import AmountView, AmountViewTypedDict
    from .amounts import Amounts, AmountsTypedDict
    from .auth_rejection_details import (
        AuthRejectionDetails,
        AuthRejectionDetailsTypedDict,
    )
    from .auth_rejection_details_view import (
        AuthRejectionDetailsView,
        AuthRejectionDetailsViewTypedDict,
    )
    from .authorization_verification_status import AuthorizationVerificationStatus
    from .authorizetransactionop import (
        AuthorizeTransactionRequest,
        AuthorizeTransactionRequestBody,
        AuthorizeTransactionRequestBodyTypedDict,
        AuthorizeTransactionRequestTypedDict,
        AuthorizeTransactionSecurity,
        AuthorizeTransactionSecurityTypedDict,
    )
    from .cancelsubscriptionop import (
        CancelSubscriptionRequest,
        CancelSubscriptionRequestTypedDict,
    )
    from .capture_status import CaptureStatus
    from .capture_transaction_with_reference import (
        CaptureTransactionWithReference,
        CaptureTransactionWithReferenceTypedDict,
    )
    from .capture_view import (
        CaptureView,
        CaptureViewType,
        CaptureViewTypedDict,
        Split,
        SplitTypedDict,
    )
    from .capturetransactionop import (
        CaptureTransactionRequest,
        CaptureTransactionRequestTypedDict,
        Error,
        ErrorTypedDict,
        Result,
        ResultTypedDict,
    )
    from .card_display_network import CardDisplayNetwork
    from .card_network import CardNetwork
    from .card_status import CardStatus
    from .card_token_type import CardTokenType
    from .cart_add_on import CartAddOn, CartAddOnTypedDict
    from .cart_create import CartCreate, CartCreateTypedDict
    from .cart_discount import (
        CartDiscount,
        CartDiscountDiscountCategory,
        CartDiscountType,
        CartDiscountTypedDict,
    )
    from .cart_fee import CartFee, CartFeeTypedDict
    from .cart_item import (
        CartItem,
        CartItemShipmentType,
        CartItemType,
        CartItemTypedDict,
    )
    from .cart_item_customization import (
        CartItemCustomization,
        CartItemCustomizationTypedDict,
    )
    from .cart_item_gift_option import CartItemGiftOption, CartItemGiftOptionTypedDict
    from .cart_item_property import CartItemProperty, CartItemPropertyTypedDict
    from .cart_item_property_view import (
        CartItemPropertyView,
        CartItemPropertyViewTypedDict,
    )
    from .cart_loyalty_rewards import CartLoyaltyRewards, CartLoyaltyRewardsTypedDict
    from .cart_loyalty_rewards_view import (
        CartLoyaltyRewardsView,
        CartLoyaltyRewardsViewTypedDict,
    )
    from .cart_shipment import CartShipment, CartShipmentTypedDict
    from .cart_shipment_type import CartShipmentType
    from .cart_view import CartView, CartViewTypedDict
    from .chargeback_details import ChargebackDetails, ChargebackDetailsTypedDict
    from .chargeback_details_view import (
        ChargebackDetailsView,
        ChargebackDetailsViewTypedDict,
        RepresentmentResult,
    )
    from .chargeback_event_view import ChargebackEventView, ChargebackEventViewTypedDict
    from .chargeback_reason_code import ChargebackReasonCode
    from .chargeback_representment_result import ChargebackRepresentmentResult
    from .consumer_billing_address import (
        ConsumerBillingAddress,
        ConsumerBillingAddressTypedDict,
    )
    from .consumer_membership_status import ConsumerMembershipStatus
    from .consumer_self_view import (
        ConsumerSelfView,
        ConsumerSelfViewTypedDict,
        PlatformAccountStatus,
    )
    from .consumer_summary_view import ConsumerSummaryView, ConsumerSummaryViewTypedDict
    from .consumer_user_membership import (
        ConsumerUserMembership,
        ConsumerUserMembershipTypedDict,
    )
    from .create_account_input import CreateAccountInput, CreateAccountInputTypedDict
    from .createaccountop import CreateAccountRequest, CreateAccountRequestTypedDict
    from .createtestingshopperaccountop import (
        CreateTestingShopperAccountRequest,
        CreateTestingShopperAccountRequestTypedDict,
    )
    from .createwebhookop import (
        CreateWebhookRequest,
        CreateWebhookRequestTypedDict,
        CreateWebhookResponse,
        CreateWebhookResponseTypedDict,
    )
    from .credit import Credit, CreditTypedDict
    from .credit_card import (
        CreditCard,
        CreditCardPriority,
        CreditCardTokenType,
        CreditCardTypedDict,
    )
    from .credit_card_authorization_reason import CreditCardAuthorizationReason
    from .credit_card_authorization_status import CreditCardAuthorizationStatus
    from .credit_card_authorization_view import (
        AvsResponse,
        CreditCardAuthorizationView,
        CreditCardAuthorizationViewTypedDict,
        CvvResponse,
        Processor,
    )
    from .credit_card_capture_view import (
        CreditCardCaptureView,
        CreditCardCaptureViewTypedDict,
    )
    from .credit_card_credit_view import (
        CreditCardCreditView,
        CreditCardCreditViewStatus,
        CreditCardCreditViewTypedDict,
    )
    from .credit_card_user import CreditCardUser, CreditCardUserTypedDict
    from .credit_card_view import CreditCardView, CreditCardViewTypedDict
    from .credit_card_void import CreditCardVoid, CreditCardVoidTypedDict
    from .credit_card_void_cause import CreditCardVoidCause
    from .credit_card_void_status import CreditCardVoidStatus
    from .credit_card_void_view import CreditCardVoidView, CreditCardVoidViewTypedDict
    from .custom_field_full_response_view import (
        CustomFieldFullResponseView,
        CustomFieldFullResponseViewTypedDict,
    )
    from .custom_field_response_view import (
        CustomFieldResponseView,
        CustomFieldResponseViewTypedDict,
        Response,
        ResponseTypedDict,
    )
    from .custom_field_view import (
        CustomFieldView,
        CustomFieldViewCheckoutStep,
        CustomFieldViewContext,
        CustomFieldViewTypedDict,
    )
    from .custom_fields import (
        CheckoutSetup,
        CustomFields,
        CustomFieldsContext,
        CustomFieldsTypedDict,
    )
    from .customer_list_status import CustomerListStatus, CustomerListStatusTypedDict
    from .deleteaddressop import (
        DeleteAddressRequest,
        DeleteAddressRequestTypedDict,
        DeleteAddressSecurity,
        DeleteAddressSecurityTypedDict,
    )
    from .deletepaymentmethodop import (
        DeletePaymentMethodRequest,
        DeletePaymentMethodRequestTypedDict,
        DeletePaymentMethodSecurity,
        DeletePaymentMethodSecurityTypedDict,
    )
    from .deletewebhookop import DeleteWebhookRequest, DeleteWebhookRequestTypedDict
    from .detectaccountop import DetectAccountRequest, DetectAccountRequestTypedDict
    from .digital_delivery import DigitalDelivery, DigitalDeliveryTypedDict
    from .editaddressop import (
        EditAddressPriority,
        EditAddressRequest,
        EditAddressRequestTypedDict,
        EditAddressResponse,
        EditAddressResponseTypedDict,
        EditAddressSecurity,
        EditAddressSecurityTypedDict,
    )
    from .eligible_payment_method import (
        EligiblePaymentMethod,
        EligiblePaymentMethodTypedDict,
    )
    from .email_priority import EmailPriority
    from .email_status import EmailStatus
    from .email_view import EmailView, EmailViewTypedDict
    from .emails import Emails, EmailsTypedDict
    from .error_bolt_api import ErrorBoltAPI, ErrorBoltAPITypedDict
    from .event_group_create_webhook import (
        EventGroupCreateWebhook,
        EventGroupCreateWebhookTypedDict,
    )
    from .events_array_create_webhook import (
        EventsArrayCreateWebhook,
        EventsArrayCreateWebhookTypedDict,
    )
    from .fulfillment import Fulfillment, FulfillmentType, FulfillmentTypedDict
    from .fulfillment_view import FulfillmentView, FulfillmentViewTypedDict
    from .getaccountop import (
        GetAccountRequest,
        GetAccountRequestTypedDict,
        GetAccountSecurity,
        GetAccountSecurityTypedDict,
    )
    from .getdunningsettingsop import (
        GetDunningSettingsRequest,
        GetDunningSettingsRequestTypedDict,
    )
    from .getmerchantcallbacksop import (
        GetMerchantCallbacksRequest,
        GetMerchantCallbacksRequestTypedDict,
    )
    from .getsubscriptionop import (
        GetSubscriptionRequest,
        GetSubscriptionRequestTypedDict,
    )
    from .getsubscriptionordersop import (
        GetSubscriptionOrdersRequest,
        GetSubscriptionOrdersRequestTypedDict,
    )
    from .getsubscriptionsop import (
        GetSubscriptionsRequest,
        GetSubscriptionsRequestTypedDict,
    )
    from .gettestcreditcardtokenop import (
        GetTestCreditCardTokenResponse,
        GetTestCreditCardTokenResponseTypedDict,
    )
    from .gettransactiondetailsop import (
        GetTransactionDetailsRequest,
        GetTransactionDetailsRequestTypedDict,
    )
    from .getwebhookop import GetWebhookRequest, GetWebhookRequestTypedDict
    from .gift_option_view import GiftOptionView, GiftOptionViewTypedDict
    from .gift_options import GiftOptions, GiftOptionsTypedDict
    from .i_authorize_result_view import (
        IAuthorizeResultView,
        IAuthorizeResultViewTypedDict,
    )
    from .i_cart_discount_view import (
        ICartDiscountView,
        ICartDiscountViewDiscountCategory,
        ICartDiscountViewTypedDict,
    )
    from .i_cart_fee_view import ICartFeeView, ICartFeeViewTypedDict
    from .i_cart_item_external_inputs import (
        ICartItemExternalInputs,
        ICartItemExternalInputsTypedDict,
    )
    from .i_cart_item_view import (
        ICartItemView,
        ICartItemViewShipmentType,
        ICartItemViewType,
        ICartItemViewTypedDict,
    )
    from .i_cart_shipment_view import (
        ICartShipmentView,
        ICartShipmentViewPackageDimension,
        ICartShipmentViewPackageDimensionTypedDict,
        ICartShipmentViewTypedDict,
    )
    from .i_cart_view import ICartView, ICartViewTypedDict
    from .i_currency import ICurrency, ICurrencyTypedDict
    from .i_custom_field_view import (
        ICustomFieldView,
        ICustomFieldViewCheckoutStep,
        ICustomFieldViewContext,
        ICustomFieldViewTypedDict,
    )
    from .i_description_part import IDescriptionPart, IDescriptionPartTypedDict
    from .i_description_tooltip import IDescriptionTooltip, IDescriptionTooltipTypedDict
    from .i_free_shipping_discount_view import (
        IFreeShippingDiscountView,
        IFreeShippingDiscountViewTypedDict,
    )
    from .i_gift_option_view import IGiftOptionView, IGiftOptionViewTypedDict
    from .i_order_dynamic_content import (
        HideApm,
        IOrderDynamicContent,
        IOrderDynamicContentTypedDict,
    )
    from .i_order_external_data import IOrderExternalData, IOrderExternalDataTypedDict
    from .i_order_metadata import IOrderMetadata, IOrderMetadataTypedDict
    from .i_order_view import IOrderView, IOrderViewTypedDict
    from .i_weight import IWeight, IWeightTypedDict
    from .in_store_cart_shipment import (
        InStoreCartShipment,
        InStoreCartShipmentDistanceUnit,
        InStoreCartShipmentTypedDict,
    )
    from .in_store_shipment import InStoreShipment, InStoreShipmentTypedDict
    from .in_store_shipment2 import (
        InStoreShipment2,
        InStoreShipment2DistanceUnit,
        InStoreShipment2TypedDict,
    )
    from .item import Customization, CustomizationTypedDict, Item, ItemTypedDict
    from .item_property import ItemProperty, ItemPropertyTypedDict
    from .item_shipment_type import ItemShipmentType
    from .login_view import Action, LoginView, LoginViewTypedDict, Method
    from .manual_dispute_view import (
        ManualDisputeView,
        ManualDisputeViewStatus,
        ManualDisputeViewTypedDict,
    )
    from .manual_disputes import (
        ManualDisputes,
        ManualDisputesStatus,
        ManualDisputesTypedDict,
    )
    from .marketplace_commission_fee import (
        MarketplaceCommissionFee,
        MarketplaceCommissionFeeTypedDict,
    )
    from .merchant import Merchant, MerchantTypedDict
    from .merchant_callback_url_type import MerchantCallbackURLType
    from .merchant_callbacks_input import (
        MerchantCallbacksInput,
        MerchantCallbacksInputCallbackURL,
        MerchantCallbacksInputCallbackURLTypedDict,
        MerchantCallbacksInputTypedDict,
    )
    from .merchant_callbacks_view import (
        MerchantCallbacksView,
        MerchantCallbacksViewCallbackURL,
        MerchantCallbacksViewCallbackURLTypedDict,
        MerchantCallbacksViewTypedDict,
    )
    from .merchant_credit_card_authorization import (
        MerchantCreditCardAuthorization,
        MerchantCreditCardAuthorizationProcessingInitiator,
        MerchantCreditCardAuthorizationSource,
        MerchantCreditCardAuthorizationTypedDict,
    )
    from .merchant_credit_card_authorization_recharge import (
        MerchantCreditCardAuthorizationRecharge,
        MerchantCreditCardAuthorizationRechargeSource,
        MerchantCreditCardAuthorizationRechargeTypedDict,
    )
    from .merchant_credit_card_review import (
        Decision,
        MerchantCreditCardReview,
        MerchantCreditCardReviewTypedDict,
    )
    from .merchant_division import MerchantDivision, MerchantDivisionTypedDict
    from .merchant_division_logo_view import (
        MerchantDivisionLogoView,
        MerchantDivisionLogoViewTypedDict,
    )
    from .merchant_division_summary_view import (
        HookType,
        MerchantDivisionSummaryView,
        MerchantDivisionSummaryViewTypedDict,
    )
    from .merchant_divisions_identifiers_view import (
        MerchantDivisionsIdentifiersView,
        MerchantDivisionsIdentifiersViewTypedDict,
    )
    from .merchant_identifiers_view import (
        MerchantIdentifiersView,
        MerchantIdentifiersViewTypedDict,
    )
    from .merchant_logo import MerchantLogo, MerchantLogoTypedDict
    from .merchant_onboarding_status_code import MerchantOnboardingStatusCode
    from .merchant_platform import MerchantPlatform
    from .merchant_status import MerchantStatus
    from .metadata_component import MetadataComponent, MetadataComponentTypedDict
    from .mock_tracking_input import (
        MockTrackingInput,
        MockTrackingInputStatus,
        MockTrackingInputTypedDict,
    )
    from .o_auth_token_input import (
        OAuthTokenInput,
        OAuthTokenInputGrantType,
        OAuthTokenInputTypedDict,
        Scope,
    )
    from .o_auth_token_input_refresh import (
        OAuthTokenInputRefresh,
        OAuthTokenInputRefreshGrantType,
        OAuthTokenInputRefreshTypedDict,
    )
    from .o_auth_token_response import OAuthTokenResponse, OAuthTokenResponseTypedDict
    from .oauthtokenop import (
        OAuthTokenRequest,
        OAuthTokenRequestBody,
        OAuthTokenRequestBodyTypedDict,
        OAuthTokenRequestTypedDict,
    )
    from .order_create import (
        Cart,
        CartTypedDict,
        Channel,
        OrderCreate,
        OrderCreateTypedDict,
    )
    from .order_decision import OrderDecision, OrderDecisionTypedDict
    from .order_decision_details_view import (
        OrderDecisionDetailsView,
        OrderDecisionDetailsViewTypedDict,
    )
    from .order_external_data_view import (
        OrderExternalDataView,
        OrderExternalDataViewTypedDict,
    )
    from .order_track_requestbody import (
        OrderTrackRequestBody,
        OrderTrackRequestBodyTypedDict,
    )
    from .order_track_response import OrderTrackResponse, OrderTrackResponseTypedDict
    from .order_view import OrderView, OrderViewTypedDict
    from .package_dimension import PackageDimension, PackageDimensionTypedDict
    from .package_weights import PackageWeights, PackageWeightsTypedDict
    from .pausesubscriptionop import (
        PauseSubscriptionRequest,
        PauseSubscriptionRequestTypedDict,
    )
    from .payment_method_account import (
        Network,
        PaymentMethodAccount,
        PaymentMethodAccountPriority,
        PaymentMethodAccountTokenType,
        PaymentMethodAccountTypedDict,
    )
    from .payment_service import PaymentService
    from .phone_priority import PhonePriority
    from .phone_status import PhoneStatus
    from .phone_view import PhoneView, PhoneViewPriority, PhoneViewTypedDict
    from .phones_with_country_code import (
        PhonesWithCountryCode,
        PhonesWithCountryCodeTypedDict,
    )
    from .priority import Priority
    from .processing_initiator import ProcessingInitiator
    from .profile import Profile, ProfileTypedDict
    from .profile_view import ProfileView, ProfileViewTypedDict
    from .querywebhooksop import (
        QueryWebhooksRequest,
        QueryWebhooksRequestTypedDict,
        QueryWebhooksResponse,
        QueryWebhooksResponseTypedDict,
    )
    from .refundtransactionop import (
        RefundTransactionRequest,
        RefundTransactionRequestTypedDict,
    )
    from .replaceaddressop import (
        ReplaceAddressPriority,
        ReplaceAddressRequest,
        ReplaceAddressRequestTypedDict,
        ReplaceAddressResponse,
        ReplaceAddressResponseTypedDict,
        ReplaceAddressSecurity,
        ReplaceAddressSecurityTypedDict,
    )
    from .request_result import RequestResult, RequestResultTypedDict
    from .request_status import RequestStatus
    from .review_ticket import ReviewTicket, ReviewTicketTypedDict
    from .review_ticket_view import ReviewTicketView, ReviewTicketViewTypedDict
    from .reviewtransactionop import (
        ReviewTransactionRequest,
        ReviewTransactionRequestTypedDict,
    )
    from .risk_decision_factor_yml import RiskDecisionFactorYml
    from .risk_insights_yml import RiskInsightsYml, RiskInsightsYmlTypedDict
    from .risk_model_external_result_view import (
        RiskModelExternalResultView,
        RiskModelExternalResultViewTypedDict,
    )
    from .risk_model_resul_contribution_view import (
        RiskModelResulContributionView,
        RiskModelResulContributionViewTypedDict,
    )
    from .risk_model_result_view import (
        RiskModelResultView,
        RiskModelResultViewTypedDict,
    )
    from .risk_review_status import RiskReviewStatus
    from .saved_credit_card_view import (
        SavedCreditCardView,
        SavedCreditCardViewType,
        SavedCreditCardViewTypedDict,
    )
    from .saved_paypal_account_view import (
        SavedPaypalAccountView,
        SavedPaypalAccountViewType,
        SavedPaypalAccountViewTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .seller_split import SellerSplit, SellerSplitTypedDict
    from .seller_split_amounts import SellerSplitAmounts, SellerSplitAmountsTypedDict
    from .shopper_metadata import ShopperMetadata, ShopperMetadataTypedDict
    from .splits_view import SplitsView, SplitsViewType, SplitsViewTypedDict
    from .statements_file_type import StatementsFileType
    from .statements_type import StatementsType
    from .statements_view_requestbody import (
        StatementsViewRequestBody,
        StatementsViewRequestBodyTypedDict,
    )
    from .statements_view_response import (
        StatementsViewResponse,
        StatementsViewResponseTypedDict,
    )
    from .subscription import (
        Frequency,
        FrequencyTypedDict,
        Subscription,
        SubscriptionTypedDict,
        Unit,
    )
    from .subscription_v2 import SubscriptionV2, SubscriptionV2TypedDict
    from .subscription_v2_dunning_settings import (
        FinalAction,
        SubscriptionV2DunningSettings,
        SubscriptionV2DunningSettingsTypedDict,
    )
    from .subscription_v2_initial_period import (
        SubscriptionV2InitialPeriod,
        SubscriptionV2InitialPeriodFrequencyUnit,
        SubscriptionV2InitialPeriodTypedDict,
    )
    from .subscription_v2_list import SubscriptionV2List, SubscriptionV2ListTypedDict
    from .subscription_v2_order import SubscriptionV2Order, SubscriptionV2OrderTypedDict
    from .subscription_v2_order_list import (
        SubscriptionV2OrderList,
        SubscriptionV2OrderListTypedDict,
    )
    from .subscription_v2_order_status import SubscriptionV2OrderStatus
    from .subscription_v2_pagination import (
        SubscriptionV2Pagination,
        SubscriptionV2PaginationTypedDict,
    )
    from .subscription_v2_payment_method import (
        SubscriptionV2PaymentMethod,
        SubscriptionV2PaymentMethodTypedDict,
    )
    from .subscription_v2_plan import (
        SubscriptionV2Plan,
        SubscriptionV2PlanFrequencyUnit,
        SubscriptionV2PlanTypedDict,
    )
    from .subscription_v2_status import SubscriptionV2Status
    from .subscription_v2_status_details import (
        SubscriptionV2StatusDetails,
        SubscriptionV2StatusDetailsTypedDict,
    )
    from .subscription_v2_success import (
        SubscriptionV2Success,
        SubscriptionV2SuccessTypedDict,
    )
    from .testing_account_details import (
        TestingAccountDetails,
        TestingAccountDetailsTypedDict,
    )
    from .testing_account_request import (
        TestingAccountRequest,
        TestingAccountRequestTypedDict,
    )
    from .total_weight import TotalWeight, TotalWeightTypedDict
    from .tracking_detail import (
        TrackingDetail,
        TrackingDetailStatus,
        TrackingDetailTypedDict,
    )
    from .transaction_credit import TransactionCredit, TransactionCreditTypedDict
    from .transaction_details import TransactionDetails, TransactionDetailsTypedDict
    from .transaction_details_view import (
        AuthVerificationStatus,
        TransactionDetailsView,
        TransactionDetailsViewTypedDict,
        TransactionDetailsViewViewStatus,
        TransactionRejectionDetails,
        TransactionRejectionDetailsTypedDict,
        VoidCause,
    )
    from .transaction_indemnification_decision import TransactionIndemnificationDecision
    from .transaction_indemnification_reason import TransactionIndemnificationReason
    from .transaction_operational_processor import (
        TransactionOperationalProcessor,
        TransactionOperationalProcessorTypedDict,
    )
    from .transaction_processor import TransactionProcessor
    from .transaction_processor_status import TransactionProcessorStatus
    from .transaction_rejection_details_view import (
        TransactionRejectionDetailsView,
        TransactionRejectionDetailsViewTypedDict,
    )
    from .transaction_review_view import (
        TransactionReviewView,
        TransactionReviewViewTypedDict,
    )
    from .transaction_splits_view import (
        TransactionSplitsView,
        TransactionSplitsViewType,
        TransactionSplitsViewTypedDict,
    )
    from .transaction_status import TransactionStatus
    from .transaction_timeline_view import (
        TransactionTimelineView,
        TransactionTimelineViewType,
        TransactionTimelineViewTypedDict,
    )
    from .transaction_type import TransactionType
    from .transaction_update_input import (
        TransactionUpdateInput,
        TransactionUpdateInputTypedDict,
    )
    from .transaction_view import (
        TransactionView,
        TransactionViewTypedDict,
        TransactionViewViewStatus,
    )
    from .type import Type
    from .unpausesubscriptionop import (
        UnpauseSubscriptionRequest,
        UnpauseSubscriptionRequestTypedDict,
    )
    from .update_profile import UpdateProfile, UpdateProfileTypedDict
    from .updateaccountprofileop import (
        UpdateAccountProfileRequest,
        UpdateAccountProfileRequestTypedDict,
        UpdateAccountProfileSecurity,
        UpdateAccountProfileSecurityTypedDict,
    )
    from .updatedunningsettingsop import (
        UpdateDunningSettingsRequest,
        UpdateDunningSettingsRequestTypedDict,
    )
    from .updatetransactionop import (
        UpdateTransactionRequest,
        UpdateTransactionRequestTypedDict,
    )
    from .user_identifier import UserIdentifier, UserIdentifierTypedDict
    from .user_identity import UserIdentity, UserIdentityTypedDict
    from .v1_accounts_view import V1AccountsView, V1AccountsViewTypedDict
    from .voidtransactionop import (
        VoidTransactionRequest,
        VoidTransactionRequestTypedDict,
    )
    from .webhook import Webhook, WebhookTypedDict
    from .webhook_event_group import WebhookEventGroup
    from .webhooks_type import WebhooksType

__all__ = [
    "AccountDetails",
    "AccountDetailsAddressView",
    "AccountDetailsAddressViewPriority",
    "AccountDetailsAddressViewTypedDict",
    "AccountDetailsTypedDict",
    "AccountIdentifierStatus",
    "Action",
    "AddAddressPriority",
    "AddAddressRequest",
    "AddAddressRequestTypedDict",
    "AddAddressResponse",
    "AddAddressResponseTypedDict",
    "AddAddressSecurity",
    "AddAddressSecurityTypedDict",
    "AddPaymentMethodNetwork",
    "AddPaymentMethodPriority",
    "AddPaymentMethodRequest",
    "AddPaymentMethodRequestBody",
    "AddPaymentMethodRequestBodyTypedDict",
    "AddPaymentMethodRequestTypedDict",
    "AddPaymentMethodSecurity",
    "AddPaymentMethodSecurityTypedDict",
    "AddPaymentMethodTokenType",
    "Address",
    "AddressAccount",
    "AddressAccountTypedDict",
    "AddressChangeRequestMetadataView",
    "AddressChangeRequestMetadataViewTypedDict",
    "AddressChangeView",
    "AddressChangeViewTypedDict",
    "AddressTypedDict",
    "AddressView",
    "AddressViewPriority",
    "AddressViewTypedDict",
    "AmountView",
    "AmountViewTypedDict",
    "Amounts",
    "AmountsTypedDict",
    "AuthRejectionDetails",
    "AuthRejectionDetailsTypedDict",
    "AuthRejectionDetailsView",
    "AuthRejectionDetailsViewTypedDict",
    "AuthVerificationStatus",
    "AuthorizationVerificationStatus",
    "AuthorizeTransactionRequest",
    "AuthorizeTransactionRequestBody",
    "AuthorizeTransactionRequestBodyTypedDict",
    "AuthorizeTransactionRequestTypedDict",
    "AuthorizeTransactionSecurity",
    "AuthorizeTransactionSecurityTypedDict",
    "AvsResponse",
    "CancelSubscriptionRequest",
    "CancelSubscriptionRequestTypedDict",
    "CaptureStatus",
    "CaptureTransactionRequest",
    "CaptureTransactionRequestTypedDict",
    "CaptureTransactionWithReference",
    "CaptureTransactionWithReferenceTypedDict",
    "CaptureView",
    "CaptureViewType",
    "CaptureViewTypedDict",
    "CardDisplayNetwork",
    "CardNetwork",
    "CardStatus",
    "CardTokenType",
    "Cart",
    "CartAddOn",
    "CartAddOnTypedDict",
    "CartCreate",
    "CartCreateTypedDict",
    "CartDiscount",
    "CartDiscountDiscountCategory",
    "CartDiscountType",
    "CartDiscountTypedDict",
    "CartFee",
    "CartFeeTypedDict",
    "CartItem",
    "CartItemCustomization",
    "CartItemCustomizationTypedDict",
    "CartItemGiftOption",
    "CartItemGiftOptionTypedDict",
    "CartItemProperty",
    "CartItemPropertyTypedDict",
    "CartItemPropertyView",
    "CartItemPropertyViewTypedDict",
    "CartItemShipmentType",
    "CartItemType",
    "CartItemTypedDict",
    "CartLoyaltyRewards",
    "CartLoyaltyRewardsTypedDict",
    "CartLoyaltyRewardsView",
    "CartLoyaltyRewardsViewTypedDict",
    "CartShipment",
    "CartShipmentType",
    "CartShipmentTypedDict",
    "CartTypedDict",
    "CartView",
    "CartViewTypedDict",
    "Channel",
    "ChargebackDetails",
    "ChargebackDetailsTypedDict",
    "ChargebackDetailsView",
    "ChargebackDetailsViewTypedDict",
    "ChargebackEventView",
    "ChargebackEventViewTypedDict",
    "ChargebackReasonCode",
    "ChargebackRepresentmentResult",
    "CheckoutSetup",
    "ConsumerBillingAddress",
    "ConsumerBillingAddressTypedDict",
    "ConsumerMembershipStatus",
    "ConsumerSelfView",
    "ConsumerSelfViewTypedDict",
    "ConsumerSummaryView",
    "ConsumerSummaryViewTypedDict",
    "ConsumerUserMembership",
    "ConsumerUserMembershipTypedDict",
    "CreateAccountInput",
    "CreateAccountInputTypedDict",
    "CreateAccountRequest",
    "CreateAccountRequestTypedDict",
    "CreateTestingShopperAccountRequest",
    "CreateTestingShopperAccountRequestTypedDict",
    "CreateWebhookRequest",
    "CreateWebhookRequestTypedDict",
    "CreateWebhookResponse",
    "CreateWebhookResponseTypedDict",
    "Credit",
    "CreditCard",
    "CreditCardAuthorizationReason",
    "CreditCardAuthorizationStatus",
    "CreditCardAuthorizationView",
    "CreditCardAuthorizationViewTypedDict",
    "CreditCardCaptureView",
    "CreditCardCaptureViewTypedDict",
    "CreditCardCreditView",
    "CreditCardCreditViewStatus",
    "CreditCardCreditViewTypedDict",
    "CreditCardPriority",
    "CreditCardTokenType",
    "CreditCardTypedDict",
    "CreditCardUser",
    "CreditCardUserTypedDict",
    "CreditCardView",
    "CreditCardViewTypedDict",
    "CreditCardVoid",
    "CreditCardVoidCause",
    "CreditCardVoidStatus",
    "CreditCardVoidTypedDict",
    "CreditCardVoidView",
    "CreditCardVoidViewTypedDict",
    "CreditTypedDict",
    "CustomFieldFullResponseView",
    "CustomFieldFullResponseViewTypedDict",
    "CustomFieldResponseView",
    "CustomFieldResponseViewTypedDict",
    "CustomFieldView",
    "CustomFieldViewCheckoutStep",
    "CustomFieldViewContext",
    "CustomFieldViewTypedDict",
    "CustomFields",
    "CustomFieldsContext",
    "CustomFieldsTypedDict",
    "CustomerListStatus",
    "CustomerListStatusTypedDict",
    "Customization",
    "CustomizationTypedDict",
    "CvvResponse",
    "Decision",
    "DeleteAddressRequest",
    "DeleteAddressRequestTypedDict",
    "DeleteAddressSecurity",
    "DeleteAddressSecurityTypedDict",
    "DeletePaymentMethodRequest",
    "DeletePaymentMethodRequestTypedDict",
    "DeletePaymentMethodSecurity",
    "DeletePaymentMethodSecurityTypedDict",
    "DeleteWebhookRequest",
    "DeleteWebhookRequestTypedDict",
    "DetectAccountRequest",
    "DetectAccountRequestTypedDict",
    "DigitalDelivery",
    "DigitalDeliveryTypedDict",
    "EditAddressPriority",
    "EditAddressRequest",
    "EditAddressRequestTypedDict",
    "EditAddressResponse",
    "EditAddressResponseTypedDict",
    "EditAddressSecurity",
    "EditAddressSecurityTypedDict",
    "EligiblePaymentMethod",
    "EligiblePaymentMethodTypedDict",
    "EmailPriority",
    "EmailStatus",
    "EmailView",
    "EmailViewTypedDict",
    "Emails",
    "EmailsTypedDict",
    "Error",
    "ErrorBoltAPI",
    "ErrorBoltAPITypedDict",
    "ErrorTypedDict",
    "EventGroupCreateWebhook",
    "EventGroupCreateWebhookTypedDict",
    "EventsArrayCreateWebhook",
    "EventsArrayCreateWebhookTypedDict",
    "FinalAction",
    "Frequency",
    "FrequencyTypedDict",
    "Fulfillment",
    "FulfillmentType",
    "FulfillmentTypedDict",
    "FulfillmentView",
    "FulfillmentViewTypedDict",
    "GetAccountRequest",
    "GetAccountRequestTypedDict",
    "GetAccountSecurity",
    "GetAccountSecurityTypedDict",
    "GetDunningSettingsRequest",
    "GetDunningSettingsRequestTypedDict",
    "GetMerchantCallbacksRequest",
    "GetMerchantCallbacksRequestTypedDict",
    "GetSubscriptionOrdersRequest",
    "GetSubscriptionOrdersRequestTypedDict",
    "GetSubscriptionRequest",
    "GetSubscriptionRequestTypedDict",
    "GetSubscriptionsRequest",
    "GetSubscriptionsRequestTypedDict",
    "GetTestCreditCardTokenResponse",
    "GetTestCreditCardTokenResponseTypedDict",
    "GetTransactionDetailsRequest",
    "GetTransactionDetailsRequestTypedDict",
    "GetWebhookRequest",
    "GetWebhookRequestTypedDict",
    "GiftOptionView",
    "GiftOptionViewTypedDict",
    "GiftOptions",
    "GiftOptionsTypedDict",
    "HideApm",
    "HookType",
    "IAuthorizeResultView",
    "IAuthorizeResultViewTypedDict",
    "ICartDiscountView",
    "ICartDiscountViewDiscountCategory",
    "ICartDiscountViewTypedDict",
    "ICartFeeView",
    "ICartFeeViewTypedDict",
    "ICartItemExternalInputs",
    "ICartItemExternalInputsTypedDict",
    "ICartItemView",
    "ICartItemViewShipmentType",
    "ICartItemViewType",
    "ICartItemViewTypedDict",
    "ICartShipmentView",
    "ICartShipmentViewPackageDimension",
    "ICartShipmentViewPackageDimensionTypedDict",
    "ICartShipmentViewTypedDict",
    "ICartView",
    "ICartViewTypedDict",
    "ICurrency",
    "ICurrencyTypedDict",
    "ICustomFieldView",
    "ICustomFieldViewCheckoutStep",
    "ICustomFieldViewContext",
    "ICustomFieldViewTypedDict",
    "IDescriptionPart",
    "IDescriptionPartTypedDict",
    "IDescriptionTooltip",
    "IDescriptionTooltipTypedDict",
    "IFreeShippingDiscountView",
    "IFreeShippingDiscountViewTypedDict",
    "IGiftOptionView",
    "IGiftOptionViewTypedDict",
    "IOrderDynamicContent",
    "IOrderDynamicContentTypedDict",
    "IOrderExternalData",
    "IOrderExternalDataTypedDict",
    "IOrderMetadata",
    "IOrderMetadataTypedDict",
    "IOrderView",
    "IOrderViewTypedDict",
    "IWeight",
    "IWeightTypedDict",
    "InStoreCartShipment",
    "InStoreCartShipmentDistanceUnit",
    "InStoreCartShipmentTypedDict",
    "InStoreShipment",
    "InStoreShipment2",
    "InStoreShipment2DistanceUnit",
    "InStoreShipment2TypedDict",
    "InStoreShipmentTypedDict",
    "Item",
    "ItemProperty",
    "ItemPropertyTypedDict",
    "ItemShipmentType",
    "ItemTypedDict",
    "LoginView",
    "LoginViewTypedDict",
    "ManualDisputeView",
    "ManualDisputeViewStatus",
    "ManualDisputeViewTypedDict",
    "ManualDisputes",
    "ManualDisputesStatus",
    "ManualDisputesTypedDict",
    "MarketplaceCommissionFee",
    "MarketplaceCommissionFeeTypedDict",
    "Merchant",
    "MerchantCallbackURLType",
    "MerchantCallbacksInput",
    "MerchantCallbacksInputCallbackURL",
    "MerchantCallbacksInputCallbackURLTypedDict",
    "MerchantCallbacksInputTypedDict",
    "MerchantCallbacksView",
    "MerchantCallbacksViewCallbackURL",
    "MerchantCallbacksViewCallbackURLTypedDict",
    "MerchantCallbacksViewTypedDict",
    "MerchantCreditCardAuthorization",
    "MerchantCreditCardAuthorizationProcessingInitiator",
    "MerchantCreditCardAuthorizationRecharge",
    "MerchantCreditCardAuthorizationRechargeSource",
    "MerchantCreditCardAuthorizationRechargeTypedDict",
    "MerchantCreditCardAuthorizationSource",
    "MerchantCreditCardAuthorizationTypedDict",
    "MerchantCreditCardReview",
    "MerchantCreditCardReviewTypedDict",
    "MerchantDivision",
    "MerchantDivisionLogoView",
    "MerchantDivisionLogoViewTypedDict",
    "MerchantDivisionSummaryView",
    "MerchantDivisionSummaryViewTypedDict",
    "MerchantDivisionTypedDict",
    "MerchantDivisionsIdentifiersView",
    "MerchantDivisionsIdentifiersViewTypedDict",
    "MerchantIdentifiersView",
    "MerchantIdentifiersViewTypedDict",
    "MerchantLogo",
    "MerchantLogoTypedDict",
    "MerchantOnboardingStatusCode",
    "MerchantPlatform",
    "MerchantStatus",
    "MerchantTypedDict",
    "MetadataComponent",
    "MetadataComponentTypedDict",
    "Method",
    "MockTrackingInput",
    "MockTrackingInputStatus",
    "MockTrackingInputTypedDict",
    "Network",
    "OAuthTokenInput",
    "OAuthTokenInputGrantType",
    "OAuthTokenInputRefresh",
    "OAuthTokenInputRefreshGrantType",
    "OAuthTokenInputRefreshTypedDict",
    "OAuthTokenInputTypedDict",
    "OAuthTokenRequest",
    "OAuthTokenRequestBody",
    "OAuthTokenRequestBodyTypedDict",
    "OAuthTokenRequestTypedDict",
    "OAuthTokenResponse",
    "OAuthTokenResponseTypedDict",
    "OrderCreate",
    "OrderCreateTypedDict",
    "OrderDecision",
    "OrderDecisionDetailsView",
    "OrderDecisionDetailsViewTypedDict",
    "OrderDecisionTypedDict",
    "OrderExternalDataView",
    "OrderExternalDataViewTypedDict",
    "OrderTrackRequestBody",
    "OrderTrackRequestBodyTypedDict",
    "OrderTrackResponse",
    "OrderTrackResponseTypedDict",
    "OrderView",
    "OrderViewTypedDict",
    "PackageDimension",
    "PackageDimensionTypedDict",
    "PackageWeights",
    "PackageWeightsTypedDict",
    "PauseSubscriptionRequest",
    "PauseSubscriptionRequestTypedDict",
    "PaymentMethod",
    "PaymentMethodAccount",
    "PaymentMethodAccountPriority",
    "PaymentMethodAccountTokenType",
    "PaymentMethodAccountTypedDict",
    "PaymentMethodTypedDict",
    "PaymentService",
    "PhonePriority",
    "PhoneStatus",
    "PhoneView",
    "PhoneViewPriority",
    "PhoneViewTypedDict",
    "PhonesWithCountryCode",
    "PhonesWithCountryCodeTypedDict",
    "PlatformAccountStatus",
    "Priority",
    "ProcessingInitiator",
    "Processor",
    "Profile",
    "ProfileTypedDict",
    "ProfileView",
    "ProfileViewTypedDict",
    "QueryWebhooksRequest",
    "QueryWebhooksRequestTypedDict",
    "QueryWebhooksResponse",
    "QueryWebhooksResponseTypedDict",
    "RefundTransactionRequest",
    "RefundTransactionRequestTypedDict",
    "ReplaceAddressPriority",
    "ReplaceAddressRequest",
    "ReplaceAddressRequestTypedDict",
    "ReplaceAddressResponse",
    "ReplaceAddressResponseTypedDict",
    "ReplaceAddressSecurity",
    "ReplaceAddressSecurityTypedDict",
    "RepresentmentResult",
    "RequestResult",
    "RequestResultTypedDict",
    "RequestStatus",
    "Response",
    "ResponseTypedDict",
    "Result",
    "ResultTypedDict",
    "ReviewTicket",
    "ReviewTicketTypedDict",
    "ReviewTicketView",
    "ReviewTicketViewTypedDict",
    "ReviewTransactionRequest",
    "ReviewTransactionRequestTypedDict",
    "RiskDecisionFactorYml",
    "RiskInsightsYml",
    "RiskInsightsYmlTypedDict",
    "RiskModelExternalResultView",
    "RiskModelExternalResultViewTypedDict",
    "RiskModelResulContributionView",
    "RiskModelResulContributionViewTypedDict",
    "RiskModelResultView",
    "RiskModelResultViewTypedDict",
    "RiskReviewStatus",
    "SavedCreditCardView",
    "SavedCreditCardViewType",
    "SavedCreditCardViewTypedDict",
    "SavedPaypalAccountView",
    "SavedPaypalAccountViewType",
    "SavedPaypalAccountViewTypedDict",
    "Scope",
    "Security",
    "SecurityTypedDict",
    "SellerSplit",
    "SellerSplitAmounts",
    "SellerSplitAmountsTypedDict",
    "SellerSplitTypedDict",
    "ShopperMetadata",
    "ShopperMetadataTypedDict",
    "Split",
    "SplitTypedDict",
    "SplitsView",
    "SplitsViewType",
    "SplitsViewTypedDict",
    "StatementsFileType",
    "StatementsType",
    "StatementsViewRequestBody",
    "StatementsViewRequestBodyTypedDict",
    "StatementsViewResponse",
    "StatementsViewResponseTypedDict",
    "Subscription",
    "SubscriptionTypedDict",
    "SubscriptionV2",
    "SubscriptionV2DunningSettings",
    "SubscriptionV2DunningSettingsTypedDict",
    "SubscriptionV2InitialPeriod",
    "SubscriptionV2InitialPeriodFrequencyUnit",
    "SubscriptionV2InitialPeriodTypedDict",
    "SubscriptionV2List",
    "SubscriptionV2ListTypedDict",
    "SubscriptionV2Order",
    "SubscriptionV2OrderList",
    "SubscriptionV2OrderListTypedDict",
    "SubscriptionV2OrderStatus",
    "SubscriptionV2OrderTypedDict",
    "SubscriptionV2Pagination",
    "SubscriptionV2PaginationTypedDict",
    "SubscriptionV2PaymentMethod",
    "SubscriptionV2PaymentMethodTypedDict",
    "SubscriptionV2Plan",
    "SubscriptionV2PlanFrequencyUnit",
    "SubscriptionV2PlanTypedDict",
    "SubscriptionV2Status",
    "SubscriptionV2StatusDetails",
    "SubscriptionV2StatusDetailsTypedDict",
    "SubscriptionV2Success",
    "SubscriptionV2SuccessTypedDict",
    "SubscriptionV2TypedDict",
    "TestingAccountDetails",
    "TestingAccountDetailsTypedDict",
    "TestingAccountRequest",
    "TestingAccountRequestTypedDict",
    "TotalWeight",
    "TotalWeightTypedDict",
    "TrackingDetail",
    "TrackingDetailStatus",
    "TrackingDetailTypedDict",
    "TransactionCredit",
    "TransactionCreditTypedDict",
    "TransactionDetails",
    "TransactionDetailsTypedDict",
    "TransactionDetailsView",
    "TransactionDetailsViewTypedDict",
    "TransactionDetailsViewViewStatus",
    "TransactionIndemnificationDecision",
    "TransactionIndemnificationReason",
    "TransactionOperationalProcessor",
    "TransactionOperationalProcessorTypedDict",
    "TransactionProcessor",
    "TransactionProcessorStatus",
    "TransactionRejectionDetails",
    "TransactionRejectionDetailsTypedDict",
    "TransactionRejectionDetailsView",
    "TransactionRejectionDetailsViewTypedDict",
    "TransactionReviewView",
    "TransactionReviewViewTypedDict",
    "TransactionSplitsView",
    "TransactionSplitsViewType",
    "TransactionSplitsViewTypedDict",
    "TransactionStatus",
    "TransactionTimelineView",
    "TransactionTimelineViewType",
    "TransactionTimelineViewTypedDict",
    "TransactionType",
    "TransactionUpdateInput",
    "TransactionUpdateInputTypedDict",
    "TransactionView",
    "TransactionViewTypedDict",
    "TransactionViewViewStatus",
    "Type",
    "Unit",
    "UnpauseSubscriptionRequest",
    "UnpauseSubscriptionRequestTypedDict",
    "UpdateAccountProfileRequest",
    "UpdateAccountProfileRequestTypedDict",
    "UpdateAccountProfileSecurity",
    "UpdateAccountProfileSecurityTypedDict",
    "UpdateDunningSettingsRequest",
    "UpdateDunningSettingsRequestTypedDict",
    "UpdateProfile",
    "UpdateProfileTypedDict",
    "UpdateTransactionRequest",
    "UpdateTransactionRequestTypedDict",
    "UserIdentifier",
    "UserIdentifierTypedDict",
    "UserIdentity",
    "UserIdentityTypedDict",
    "V1AccountsView",
    "V1AccountsViewTypedDict",
    "VoidCause",
    "VoidTransactionRequest",
    "VoidTransactionRequestTypedDict",
    "Webhook",
    "WebhookEventGroup",
    "WebhookTypedDict",
    "WebhooksType",
]

_dynamic_imports: dict[str, str] = {
    "AccountDetails": ".account_details",
    "AccountDetailsTypedDict": ".account_details",
    "PaymentMethod": ".account_details",
    "PaymentMethodTypedDict": ".account_details",
    "AccountDetailsAddressView": ".account_details_address_view",
    "AccountDetailsAddressViewPriority": ".account_details_address_view",
    "AccountDetailsAddressViewTypedDict": ".account_details_address_view",
    "AccountIdentifierStatus": ".account_identifier_status",
    "AddAddressPriority": ".addaddressop",
    "AddAddressRequest": ".addaddressop",
    "AddAddressRequestTypedDict": ".addaddressop",
    "AddAddressResponse": ".addaddressop",
    "AddAddressResponseTypedDict": ".addaddressop",
    "AddAddressSecurity": ".addaddressop",
    "AddAddressSecurityTypedDict": ".addaddressop",
    "AddPaymentMethodNetwork": ".addpaymentmethodop",
    "AddPaymentMethodPriority": ".addpaymentmethodop",
    "AddPaymentMethodRequest": ".addpaymentmethodop",
    "AddPaymentMethodRequestBody": ".addpaymentmethodop",
    "AddPaymentMethodRequestBodyTypedDict": ".addpaymentmethodop",
    "AddPaymentMethodRequestTypedDict": ".addpaymentmethodop",
    "AddPaymentMethodSecurity": ".addpaymentmethodop",
    "AddPaymentMethodSecurityTypedDict": ".addpaymentmethodop",
    "AddPaymentMethodTokenType": ".addpaymentmethodop",
    "Address": ".address",
    "AddressTypedDict": ".address",
    "AddressAccount": ".address_account",
    "AddressAccountTypedDict": ".address_account",
    "AddressChangeRequestMetadataView": ".address_change_request_metadata_view",
    "AddressChangeRequestMetadataViewTypedDict": ".address_change_request_metadata_view",
    "AddressChangeView": ".address_change_view",
    "AddressChangeViewTypedDict": ".address_change_view",
    "AddressView": ".address_view",
    "AddressViewPriority": ".address_view",
    "AddressViewTypedDict": ".address_view",
    "AmountView": ".amount_view",
    "AmountViewTypedDict": ".amount_view",
    "Amounts": ".amounts",
    "AmountsTypedDict": ".amounts",
    "AuthRejectionDetails": ".auth_rejection_details",
    "AuthRejectionDetailsTypedDict": ".auth_rejection_details",
    "AuthRejectionDetailsView": ".auth_rejection_details_view",
    "AuthRejectionDetailsViewTypedDict": ".auth_rejection_details_view",
    "AuthorizationVerificationStatus": ".authorization_verification_status",
    "AuthorizeTransactionRequest": ".authorizetransactionop",
    "AuthorizeTransactionRequestBody": ".authorizetransactionop",
    "AuthorizeTransactionRequestBodyTypedDict": ".authorizetransactionop",
    "AuthorizeTransactionRequestTypedDict": ".authorizetransactionop",
    "AuthorizeTransactionSecurity": ".authorizetransactionop",
    "AuthorizeTransactionSecurityTypedDict": ".authorizetransactionop",
    "CancelSubscriptionRequest": ".cancelsubscriptionop",
    "CancelSubscriptionRequestTypedDict": ".cancelsubscriptionop",
    "CaptureStatus": ".capture_status",
    "CaptureTransactionWithReference": ".capture_transaction_with_reference",
    "CaptureTransactionWithReferenceTypedDict": ".capture_transaction_with_reference",
    "CaptureView": ".capture_view",
    "CaptureViewType": ".capture_view",
    "CaptureViewTypedDict": ".capture_view",
    "Split": ".capture_view",
    "SplitTypedDict": ".capture_view",
    "CaptureTransactionRequest": ".capturetransactionop",
    "CaptureTransactionRequestTypedDict": ".capturetransactionop",
    "Error": ".capturetransactionop",
    "ErrorTypedDict": ".capturetransactionop",
    "Result": ".capturetransactionop",
    "ResultTypedDict": ".capturetransactionop",
    "CardDisplayNetwork": ".card_display_network",
    "CardNetwork": ".card_network",
    "CardStatus": ".card_status",
    "CardTokenType": ".card_token_type",
    "CartAddOn": ".cart_add_on",
    "CartAddOnTypedDict": ".cart_add_on",
    "CartCreate": ".cart_create",
    "CartCreateTypedDict": ".cart_create",
    "CartDiscount": ".cart_discount",
    "CartDiscountDiscountCategory": ".cart_discount",
    "CartDiscountType": ".cart_discount",
    "CartDiscountTypedDict": ".cart_discount",
    "CartFee": ".cart_fee",
    "CartFeeTypedDict": ".cart_fee",
    "CartItem": ".cart_item",
    "CartItemShipmentType": ".cart_item",
    "CartItemType": ".cart_item",
    "CartItemTypedDict": ".cart_item",
    "CartItemCustomization": ".cart_item_customization",
    "CartItemCustomizationTypedDict": ".cart_item_customization",
    "CartItemGiftOption": ".cart_item_gift_option",
    "CartItemGiftOptionTypedDict": ".cart_item_gift_option",
    "CartItemProperty": ".cart_item_property",
    "CartItemPropertyTypedDict": ".cart_item_property",
    "CartItemPropertyView": ".cart_item_property_view",
    "CartItemPropertyViewTypedDict": ".cart_item_property_view",
    "CartLoyaltyRewards": ".cart_loyalty_rewards",
    "CartLoyaltyRewardsTypedDict": ".cart_loyalty_rewards",
    "CartLoyaltyRewardsView": ".cart_loyalty_rewards_view",
    "CartLoyaltyRewardsViewTypedDict": ".cart_loyalty_rewards_view",
    "CartShipment": ".cart_shipment",
    "CartShipmentTypedDict": ".cart_shipment",
    "CartShipmentType": ".cart_shipment_type",
    "CartView": ".cart_view",
    "CartViewTypedDict": ".cart_view",
    "ChargebackDetails": ".chargeback_details",
    "ChargebackDetailsTypedDict": ".chargeback_details",
    "ChargebackDetailsView": ".chargeback_details_view",
    "ChargebackDetailsViewTypedDict": ".chargeback_details_view",
    "RepresentmentResult": ".chargeback_details_view",
    "ChargebackEventView": ".chargeback_event_view",
    "ChargebackEventViewTypedDict": ".chargeback_event_view",
    "ChargebackReasonCode": ".chargeback_reason_code",
    "ChargebackRepresentmentResult": ".chargeback_representment_result",
    "ConsumerBillingAddress": ".consumer_billing_address",
    "ConsumerBillingAddressTypedDict": ".consumer_billing_address",
    "ConsumerMembershipStatus": ".consumer_membership_status",
    "ConsumerSelfView": ".consumer_self_view",
    "ConsumerSelfViewTypedDict": ".consumer_self_view",
    "PlatformAccountStatus": ".consumer_self_view",
    "ConsumerSummaryView": ".consumer_summary_view",
    "ConsumerSummaryViewTypedDict": ".consumer_summary_view",
    "ConsumerUserMembership": ".consumer_user_membership",
    "ConsumerUserMembershipTypedDict": ".consumer_user_membership",
    "CreateAccountInput": ".create_account_input",
    "CreateAccountInputTypedDict": ".create_account_input",
    "CreateAccountRequest": ".createaccountop",
    "CreateAccountRequestTypedDict": ".createaccountop",
    "CreateTestingShopperAccountRequest": ".createtestingshopperaccountop",
    "CreateTestingShopperAccountRequestTypedDict": ".createtestingshopperaccountop",
    "CreateWebhookRequest": ".createwebhookop",
    "CreateWebhookRequestTypedDict": ".createwebhookop",
    "CreateWebhookResponse": ".createwebhookop",
    "CreateWebhookResponseTypedDict": ".createwebhookop",
    "Credit": ".credit",
    "CreditTypedDict": ".credit",
    "CreditCard": ".credit_card",
    "CreditCardPriority": ".credit_card",
    "CreditCardTokenType": ".credit_card",
    "CreditCardTypedDict": ".credit_card",
    "CreditCardAuthorizationReason": ".credit_card_authorization_reason",
    "CreditCardAuthorizationStatus": ".credit_card_authorization_status",
    "AvsResponse": ".credit_card_authorization_view",
    "CreditCardAuthorizationView": ".credit_card_authorization_view",
    "CreditCardAuthorizationViewTypedDict": ".credit_card_authorization_view",
    "CvvResponse": ".credit_card_authorization_view",
    "Processor": ".credit_card_authorization_view",
    "CreditCardCaptureView": ".credit_card_capture_view",
    "CreditCardCaptureViewTypedDict": ".credit_card_capture_view",
    "CreditCardCreditView": ".credit_card_credit_view",
    "CreditCardCreditViewStatus": ".credit_card_credit_view",
    "CreditCardCreditViewTypedDict": ".credit_card_credit_view",
    "CreditCardUser": ".credit_card_user",
    "CreditCardUserTypedDict": ".credit_card_user",
    "CreditCardView": ".credit_card_view",
    "CreditCardViewTypedDict": ".credit_card_view",
    "CreditCardVoid": ".credit_card_void",
    "CreditCardVoidTypedDict": ".credit_card_void",
    "CreditCardVoidCause": ".credit_card_void_cause",
    "CreditCardVoidStatus": ".credit_card_void_status",
    "CreditCardVoidView": ".credit_card_void_view",
    "CreditCardVoidViewTypedDict": ".credit_card_void_view",
    "CustomFieldFullResponseView": ".custom_field_full_response_view",
    "CustomFieldFullResponseViewTypedDict": ".custom_field_full_response_view",
    "CustomFieldResponseView": ".custom_field_response_view",
    "CustomFieldResponseViewTypedDict": ".custom_field_response_view",
    "Response": ".custom_field_response_view",
    "ResponseTypedDict": ".custom_field_response_view",
    "CustomFieldView": ".custom_field_view",
    "CustomFieldViewCheckoutStep": ".custom_field_view",
    "CustomFieldViewContext": ".custom_field_view",
    "CustomFieldViewTypedDict": ".custom_field_view",
    "CheckoutSetup": ".custom_fields",
    "CustomFields": ".custom_fields",
    "CustomFieldsContext": ".custom_fields",
    "CustomFieldsTypedDict": ".custom_fields",
    "CustomerListStatus": ".customer_list_status",
    "CustomerListStatusTypedDict": ".customer_list_status",
    "DeleteAddressRequest": ".deleteaddressop",
    "DeleteAddressRequestTypedDict": ".deleteaddressop",
    "DeleteAddressSecurity": ".deleteaddressop",
    "DeleteAddressSecurityTypedDict": ".deleteaddressop",
    "DeletePaymentMethodRequest": ".deletepaymentmethodop",
    "DeletePaymentMethodRequestTypedDict": ".deletepaymentmethodop",
    "DeletePaymentMethodSecurity": ".deletepaymentmethodop",
    "DeletePaymentMethodSecurityTypedDict": ".deletepaymentmethodop",
    "DeleteWebhookRequest": ".deletewebhookop",
    "DeleteWebhookRequestTypedDict": ".deletewebhookop",
    "DetectAccountRequest": ".detectaccountop",
    "DetectAccountRequestTypedDict": ".detectaccountop",
    "DigitalDelivery": ".digital_delivery",
    "DigitalDeliveryTypedDict": ".digital_delivery",
    "EditAddressPriority": ".editaddressop",
    "EditAddressRequest": ".editaddressop",
    "EditAddressRequestTypedDict": ".editaddressop",
    "EditAddressResponse": ".editaddressop",
    "EditAddressResponseTypedDict": ".editaddressop",
    "EditAddressSecurity": ".editaddressop",
    "EditAddressSecurityTypedDict": ".editaddressop",
    "EligiblePaymentMethod": ".eligible_payment_method",
    "EligiblePaymentMethodTypedDict": ".eligible_payment_method",
    "EmailPriority": ".email_priority",
    "EmailStatus": ".email_status",
    "EmailView": ".email_view",
    "EmailViewTypedDict": ".email_view",
    "Emails": ".emails",
    "EmailsTypedDict": ".emails",
    "ErrorBoltAPI": ".error_bolt_api",
    "ErrorBoltAPITypedDict": ".error_bolt_api",
    "EventGroupCreateWebhook": ".event_group_create_webhook",
    "EventGroupCreateWebhookTypedDict": ".event_group_create_webhook",
    "EventsArrayCreateWebhook": ".events_array_create_webhook",
    "EventsArrayCreateWebhookTypedDict": ".events_array_create_webhook",
    "Fulfillment": ".fulfillment",
    "FulfillmentType": ".fulfillment",
    "FulfillmentTypedDict": ".fulfillment",
    "FulfillmentView": ".fulfillment_view",
    "FulfillmentViewTypedDict": ".fulfillment_view",
    "GetAccountRequest": ".getaccountop",
    "GetAccountRequestTypedDict": ".getaccountop",
    "GetAccountSecurity": ".getaccountop",
    "GetAccountSecurityTypedDict": ".getaccountop",
    "GetDunningSettingsRequest": ".getdunningsettingsop",
    "GetDunningSettingsRequestTypedDict": ".getdunningsettingsop",
    "GetMerchantCallbacksRequest": ".getmerchantcallbacksop",
    "GetMerchantCallbacksRequestTypedDict": ".getmerchantcallbacksop",
    "GetSubscriptionRequest": ".getsubscriptionop",
    "GetSubscriptionRequestTypedDict": ".getsubscriptionop",
    "GetSubscriptionOrdersRequest": ".getsubscriptionordersop",
    "GetSubscriptionOrdersRequestTypedDict": ".getsubscriptionordersop",
    "GetSubscriptionsRequest": ".getsubscriptionsop",
    "GetSubscriptionsRequestTypedDict": ".getsubscriptionsop",
    "GetTestCreditCardTokenResponse": ".gettestcreditcardtokenop",
    "GetTestCreditCardTokenResponseTypedDict": ".gettestcreditcardtokenop",
    "GetTransactionDetailsRequest": ".gettransactiondetailsop",
    "GetTransactionDetailsRequestTypedDict": ".gettransactiondetailsop",
    "GetWebhookRequest": ".getwebhookop",
    "GetWebhookRequestTypedDict": ".getwebhookop",
    "GiftOptionView": ".gift_option_view",
    "GiftOptionViewTypedDict": ".gift_option_view",
    "GiftOptions": ".gift_options",
    "GiftOptionsTypedDict": ".gift_options",
    "IAuthorizeResultView": ".i_authorize_result_view",
    "IAuthorizeResultViewTypedDict": ".i_authorize_result_view",
    "ICartDiscountView": ".i_cart_discount_view",
    "ICartDiscountViewDiscountCategory": ".i_cart_discount_view",
    "ICartDiscountViewTypedDict": ".i_cart_discount_view",
    "ICartFeeView": ".i_cart_fee_view",
    "ICartFeeViewTypedDict": ".i_cart_fee_view",
    "ICartItemExternalInputs": ".i_cart_item_external_inputs",
    "ICartItemExternalInputsTypedDict": ".i_cart_item_external_inputs",
    "ICartItemView": ".i_cart_item_view",
    "ICartItemViewShipmentType": ".i_cart_item_view",
    "ICartItemViewType": ".i_cart_item_view",
    "ICartItemViewTypedDict": ".i_cart_item_view",
    "ICartShipmentView": ".i_cart_shipment_view",
    "ICartShipmentViewPackageDimension": ".i_cart_shipment_view",
    "ICartShipmentViewPackageDimensionTypedDict": ".i_cart_shipment_view",
    "ICartShipmentViewTypedDict": ".i_cart_shipment_view",
    "ICartView": ".i_cart_view",
    "ICartViewTypedDict": ".i_cart_view",
    "ICurrency": ".i_currency",
    "ICurrencyTypedDict": ".i_currency",
    "ICustomFieldView": ".i_custom_field_view",
    "ICustomFieldViewCheckoutStep": ".i_custom_field_view",
    "ICustomFieldViewContext": ".i_custom_field_view",
    "ICustomFieldViewTypedDict": ".i_custom_field_view",
    "IDescriptionPart": ".i_description_part",
    "IDescriptionPartTypedDict": ".i_description_part",
    "IDescriptionTooltip": ".i_description_tooltip",
    "IDescriptionTooltipTypedDict": ".i_description_tooltip",
    "IFreeShippingDiscountView": ".i_free_shipping_discount_view",
    "IFreeShippingDiscountViewTypedDict": ".i_free_shipping_discount_view",
    "IGiftOptionView": ".i_gift_option_view",
    "IGiftOptionViewTypedDict": ".i_gift_option_view",
    "HideApm": ".i_order_dynamic_content",
    "IOrderDynamicContent": ".i_order_dynamic_content",
    "IOrderDynamicContentTypedDict": ".i_order_dynamic_content",
    "IOrderExternalData": ".i_order_external_data",
    "IOrderExternalDataTypedDict": ".i_order_external_data",
    "IOrderMetadata": ".i_order_metadata",
    "IOrderMetadataTypedDict": ".i_order_metadata",
    "IOrderView": ".i_order_view",
    "IOrderViewTypedDict": ".i_order_view",
    "IWeight": ".i_weight",
    "IWeightTypedDict": ".i_weight",
    "InStoreCartShipment": ".in_store_cart_shipment",
    "InStoreCartShipmentDistanceUnit": ".in_store_cart_shipment",
    "InStoreCartShipmentTypedDict": ".in_store_cart_shipment",
    "InStoreShipment": ".in_store_shipment",
    "InStoreShipmentTypedDict": ".in_store_shipment",
    "InStoreShipment2": ".in_store_shipment2",
    "InStoreShipment2DistanceUnit": ".in_store_shipment2",
    "InStoreShipment2TypedDict": ".in_store_shipment2",
    "Customization": ".item",
    "CustomizationTypedDict": ".item",
    "Item": ".item",
    "ItemTypedDict": ".item",
    "ItemProperty": ".item_property",
    "ItemPropertyTypedDict": ".item_property",
    "ItemShipmentType": ".item_shipment_type",
    "Action": ".login_view",
    "LoginView": ".login_view",
    "LoginViewTypedDict": ".login_view",
    "Method": ".login_view",
    "ManualDisputeView": ".manual_dispute_view",
    "ManualDisputeViewStatus": ".manual_dispute_view",
    "ManualDisputeViewTypedDict": ".manual_dispute_view",
    "ManualDisputes": ".manual_disputes",
    "ManualDisputesStatus": ".manual_disputes",
    "ManualDisputesTypedDict": ".manual_disputes",
    "MarketplaceCommissionFee": ".marketplace_commission_fee",
    "MarketplaceCommissionFeeTypedDict": ".marketplace_commission_fee",
    "Merchant": ".merchant",
    "MerchantTypedDict": ".merchant",
    "MerchantCallbackURLType": ".merchant_callback_url_type",
    "MerchantCallbacksInput": ".merchant_callbacks_input",
    "MerchantCallbacksInputCallbackURL": ".merchant_callbacks_input",
    "MerchantCallbacksInputCallbackURLTypedDict": ".merchant_callbacks_input",
    "MerchantCallbacksInputTypedDict": ".merchant_callbacks_input",
    "MerchantCallbacksView": ".merchant_callbacks_view",
    "MerchantCallbacksViewCallbackURL": ".merchant_callbacks_view",
    "MerchantCallbacksViewCallbackURLTypedDict": ".merchant_callbacks_view",
    "MerchantCallbacksViewTypedDict": ".merchant_callbacks_view",
    "MerchantCreditCardAuthorization": ".merchant_credit_card_authorization",
    "MerchantCreditCardAuthorizationProcessingInitiator": ".merchant_credit_card_authorization",
    "MerchantCreditCardAuthorizationSource": ".merchant_credit_card_authorization",
    "MerchantCreditCardAuthorizationTypedDict": ".merchant_credit_card_authorization",
    "MerchantCreditCardAuthorizationRecharge": ".merchant_credit_card_authorization_recharge",
    "MerchantCreditCardAuthorizationRechargeSource": ".merchant_credit_card_authorization_recharge",
    "MerchantCreditCardAuthorizationRechargeTypedDict": ".merchant_credit_card_authorization_recharge",
    "Decision": ".merchant_credit_card_review",
    "MerchantCreditCardReview": ".merchant_credit_card_review",
    "MerchantCreditCardReviewTypedDict": ".merchant_credit_card_review",
    "MerchantDivision": ".merchant_division",
    "MerchantDivisionTypedDict": ".merchant_division",
    "MerchantDivisionLogoView": ".merchant_division_logo_view",
    "MerchantDivisionLogoViewTypedDict": ".merchant_division_logo_view",
    "HookType": ".merchant_division_summary_view",
    "MerchantDivisionSummaryView": ".merchant_division_summary_view",
    "MerchantDivisionSummaryViewTypedDict": ".merchant_division_summary_view",
    "MerchantDivisionsIdentifiersView": ".merchant_divisions_identifiers_view",
    "MerchantDivisionsIdentifiersViewTypedDict": ".merchant_divisions_identifiers_view",
    "MerchantIdentifiersView": ".merchant_identifiers_view",
    "MerchantIdentifiersViewTypedDict": ".merchant_identifiers_view",
    "MerchantLogo": ".merchant_logo",
    "MerchantLogoTypedDict": ".merchant_logo",
    "MerchantOnboardingStatusCode": ".merchant_onboarding_status_code",
    "MerchantPlatform": ".merchant_platform",
    "MerchantStatus": ".merchant_status",
    "MetadataComponent": ".metadata_component",
    "MetadataComponentTypedDict": ".metadata_component",
    "MockTrackingInput": ".mock_tracking_input",
    "MockTrackingInputStatus": ".mock_tracking_input",
    "MockTrackingInputTypedDict": ".mock_tracking_input",
    "OAuthTokenInput": ".o_auth_token_input",
    "OAuthTokenInputGrantType": ".o_auth_token_input",
    "OAuthTokenInputTypedDict": ".o_auth_token_input",
    "Scope": ".o_auth_token_input",
    "OAuthTokenInputRefresh": ".o_auth_token_input_refresh",
    "OAuthTokenInputRefreshGrantType": ".o_auth_token_input_refresh",
    "OAuthTokenInputRefreshTypedDict": ".o_auth_token_input_refresh",
    "OAuthTokenResponse": ".o_auth_token_response",
    "OAuthTokenResponseTypedDict": ".o_auth_token_response",
    "OAuthTokenRequest": ".oauthtokenop",
    "OAuthTokenRequestBody": ".oauthtokenop",
    "OAuthTokenRequestBodyTypedDict": ".oauthtokenop",
    "OAuthTokenRequestTypedDict": ".oauthtokenop",
    "Cart": ".order_create",
    "CartTypedDict": ".order_create",
    "Channel": ".order_create",
    "OrderCreate": ".order_create",
    "OrderCreateTypedDict": ".order_create",
    "OrderDecision": ".order_decision",
    "OrderDecisionTypedDict": ".order_decision",
    "OrderDecisionDetailsView": ".order_decision_details_view",
    "OrderDecisionDetailsViewTypedDict": ".order_decision_details_view",
    "OrderExternalDataView": ".order_external_data_view",
    "OrderExternalDataViewTypedDict": ".order_external_data_view",
    "OrderTrackRequestBody": ".order_track_requestbody",
    "OrderTrackRequestBodyTypedDict": ".order_track_requestbody",
    "OrderTrackResponse": ".order_track_response",
    "OrderTrackResponseTypedDict": ".order_track_response",
    "OrderView": ".order_view",
    "OrderViewTypedDict": ".order_view",
    "PackageDimension": ".package_dimension",
    "PackageDimensionTypedDict": ".package_dimension",
    "PackageWeights": ".package_weights",
    "PackageWeightsTypedDict": ".package_weights",
    "PauseSubscriptionRequest": ".pausesubscriptionop",
    "PauseSubscriptionRequestTypedDict": ".pausesubscriptionop",
    "Network": ".payment_method_account",
    "PaymentMethodAccount": ".payment_method_account",
    "PaymentMethodAccountPriority": ".payment_method_account",
    "PaymentMethodAccountTokenType": ".payment_method_account",
    "PaymentMethodAccountTypedDict": ".payment_method_account",
    "PaymentService": ".payment_service",
    "PhonePriority": ".phone_priority",
    "PhoneStatus": ".phone_status",
    "PhoneView": ".phone_view",
    "PhoneViewPriority": ".phone_view",
    "PhoneViewTypedDict": ".phone_view",
    "PhonesWithCountryCode": ".phones_with_country_code",
    "PhonesWithCountryCodeTypedDict": ".phones_with_country_code",
    "Priority": ".priority",
    "ProcessingInitiator": ".processing_initiator",
    "Profile": ".profile",
    "ProfileTypedDict": ".profile",
    "ProfileView": ".profile_view",
    "ProfileViewTypedDict": ".profile_view",
    "QueryWebhooksRequest": ".querywebhooksop",
    "QueryWebhooksRequestTypedDict": ".querywebhooksop",
    "QueryWebhooksResponse": ".querywebhooksop",
    "QueryWebhooksResponseTypedDict": ".querywebhooksop",
    "RefundTransactionRequest": ".refundtransactionop",
    "RefundTransactionRequestTypedDict": ".refundtransactionop",
    "ReplaceAddressPriority": ".replaceaddressop",
    "ReplaceAddressRequest": ".replaceaddressop",
    "ReplaceAddressRequestTypedDict": ".replaceaddressop",
    "ReplaceAddressResponse": ".replaceaddressop",
    "ReplaceAddressResponseTypedDict": ".replaceaddressop",
    "ReplaceAddressSecurity": ".replaceaddressop",
    "ReplaceAddressSecurityTypedDict": ".replaceaddressop",
    "RequestResult": ".request_result",
    "RequestResultTypedDict": ".request_result",
    "RequestStatus": ".request_status",
    "ReviewTicket": ".review_ticket",
    "ReviewTicketTypedDict": ".review_ticket",
    "ReviewTicketView": ".review_ticket_view",
    "ReviewTicketViewTypedDict": ".review_ticket_view",
    "ReviewTransactionRequest": ".reviewtransactionop",
    "ReviewTransactionRequestTypedDict": ".reviewtransactionop",
    "RiskDecisionFactorYml": ".risk_decision_factor_yml",
    "RiskInsightsYml": ".risk_insights_yml",
    "RiskInsightsYmlTypedDict": ".risk_insights_yml",
    "RiskModelExternalResultView": ".risk_model_external_result_view",
    "RiskModelExternalResultViewTypedDict": ".risk_model_external_result_view",
    "RiskModelResulContributionView": ".risk_model_resul_contribution_view",
    "RiskModelResulContributionViewTypedDict": ".risk_model_resul_contribution_view",
    "RiskModelResultView": ".risk_model_result_view",
    "RiskModelResultViewTypedDict": ".risk_model_result_view",
    "RiskReviewStatus": ".risk_review_status",
    "SavedCreditCardView": ".saved_credit_card_view",
    "SavedCreditCardViewType": ".saved_credit_card_view",
    "SavedCreditCardViewTypedDict": ".saved_credit_card_view",
    "SavedPaypalAccountView": ".saved_paypal_account_view",
    "SavedPaypalAccountViewType": ".saved_paypal_account_view",
    "SavedPaypalAccountViewTypedDict": ".saved_paypal_account_view",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "SellerSplit": ".seller_split",
    "SellerSplitTypedDict": ".seller_split",
    "SellerSplitAmounts": ".seller_split_amounts",
    "SellerSplitAmountsTypedDict": ".seller_split_amounts",
    "ShopperMetadata": ".shopper_metadata",
    "ShopperMetadataTypedDict": ".shopper_metadata",
    "SplitsView": ".splits_view",
    "SplitsViewType": ".splits_view",
    "SplitsViewTypedDict": ".splits_view",
    "StatementsFileType": ".statements_file_type",
    "StatementsType": ".statements_type",
    "StatementsViewRequestBody": ".statements_view_requestbody",
    "StatementsViewRequestBodyTypedDict": ".statements_view_requestbody",
    "StatementsViewResponse": ".statements_view_response",
    "StatementsViewResponseTypedDict": ".statements_view_response",
    "Frequency": ".subscription",
    "FrequencyTypedDict": ".subscription",
    "Subscription": ".subscription",
    "SubscriptionTypedDict": ".subscription",
    "Unit": ".subscription",
    "SubscriptionV2": ".subscription_v2",
    "SubscriptionV2TypedDict": ".subscription_v2",
    "FinalAction": ".subscription_v2_dunning_settings",
    "SubscriptionV2DunningSettings": ".subscription_v2_dunning_settings",
    "SubscriptionV2DunningSettingsTypedDict": ".subscription_v2_dunning_settings",
    "SubscriptionV2InitialPeriod": ".subscription_v2_initial_period",
    "SubscriptionV2InitialPeriodFrequencyUnit": ".subscription_v2_initial_period",
    "SubscriptionV2InitialPeriodTypedDict": ".subscription_v2_initial_period",
    "SubscriptionV2List": ".subscription_v2_list",
    "SubscriptionV2ListTypedDict": ".subscription_v2_list",
    "SubscriptionV2Order": ".subscription_v2_order",
    "SubscriptionV2OrderTypedDict": ".subscription_v2_order",
    "SubscriptionV2OrderList": ".subscription_v2_order_list",
    "SubscriptionV2OrderListTypedDict": ".subscription_v2_order_list",
    "SubscriptionV2OrderStatus": ".subscription_v2_order_status",
    "SubscriptionV2Pagination": ".subscription_v2_pagination",
    "SubscriptionV2PaginationTypedDict": ".subscription_v2_pagination",
    "SubscriptionV2PaymentMethod": ".subscription_v2_payment_method",
    "SubscriptionV2PaymentMethodTypedDict": ".subscription_v2_payment_method",
    "SubscriptionV2Plan": ".subscription_v2_plan",
    "SubscriptionV2PlanFrequencyUnit": ".subscription_v2_plan",
    "SubscriptionV2PlanTypedDict": ".subscription_v2_plan",
    "SubscriptionV2Status": ".subscription_v2_status",
    "SubscriptionV2StatusDetails": ".subscription_v2_status_details",
    "SubscriptionV2StatusDetailsTypedDict": ".subscription_v2_status_details",
    "SubscriptionV2Success": ".subscription_v2_success",
    "SubscriptionV2SuccessTypedDict": ".subscription_v2_success",
    "TestingAccountDetails": ".testing_account_details",
    "TestingAccountDetailsTypedDict": ".testing_account_details",
    "TestingAccountRequest": ".testing_account_request",
    "TestingAccountRequestTypedDict": ".testing_account_request",
    "TotalWeight": ".total_weight",
    "TotalWeightTypedDict": ".total_weight",
    "TrackingDetail": ".tracking_detail",
    "TrackingDetailStatus": ".tracking_detail",
    "TrackingDetailTypedDict": ".tracking_detail",
    "TransactionCredit": ".transaction_credit",
    "TransactionCreditTypedDict": ".transaction_credit",
    "TransactionDetails": ".transaction_details",
    "TransactionDetailsTypedDict": ".transaction_details",
    "AuthVerificationStatus": ".transaction_details_view",
    "TransactionDetailsView": ".transaction_details_view",
    "TransactionDetailsViewTypedDict": ".transaction_details_view",
    "TransactionDetailsViewViewStatus": ".transaction_details_view",
    "TransactionRejectionDetails": ".transaction_details_view",
    "TransactionRejectionDetailsTypedDict": ".transaction_details_view",
    "VoidCause": ".transaction_details_view",
    "TransactionIndemnificationDecision": ".transaction_indemnification_decision",
    "TransactionIndemnificationReason": ".transaction_indemnification_reason",
    "TransactionOperationalProcessor": ".transaction_operational_processor",
    "TransactionOperationalProcessorTypedDict": ".transaction_operational_processor",
    "TransactionProcessor": ".transaction_processor",
    "TransactionProcessorStatus": ".transaction_processor_status",
    "TransactionRejectionDetailsView": ".transaction_rejection_details_view",
    "TransactionRejectionDetailsViewTypedDict": ".transaction_rejection_details_view",
    "TransactionReviewView": ".transaction_review_view",
    "TransactionReviewViewTypedDict": ".transaction_review_view",
    "TransactionSplitsView": ".transaction_splits_view",
    "TransactionSplitsViewType": ".transaction_splits_view",
    "TransactionSplitsViewTypedDict": ".transaction_splits_view",
    "TransactionStatus": ".transaction_status",
    "TransactionTimelineView": ".transaction_timeline_view",
    "TransactionTimelineViewType": ".transaction_timeline_view",
    "TransactionTimelineViewTypedDict": ".transaction_timeline_view",
    "TransactionType": ".transaction_type",
    "TransactionUpdateInput": ".transaction_update_input",
    "TransactionUpdateInputTypedDict": ".transaction_update_input",
    "TransactionView": ".transaction_view",
    "TransactionViewTypedDict": ".transaction_view",
    "TransactionViewViewStatus": ".transaction_view",
    "Type": ".type",
    "UnpauseSubscriptionRequest": ".unpausesubscriptionop",
    "UnpauseSubscriptionRequestTypedDict": ".unpausesubscriptionop",
    "UpdateProfile": ".update_profile",
    "UpdateProfileTypedDict": ".update_profile",
    "UpdateAccountProfileRequest": ".updateaccountprofileop",
    "UpdateAccountProfileRequestTypedDict": ".updateaccountprofileop",
    "UpdateAccountProfileSecurity": ".updateaccountprofileop",
    "UpdateAccountProfileSecurityTypedDict": ".updateaccountprofileop",
    "UpdateDunningSettingsRequest": ".updatedunningsettingsop",
    "UpdateDunningSettingsRequestTypedDict": ".updatedunningsettingsop",
    "UpdateTransactionRequest": ".updatetransactionop",
    "UpdateTransactionRequestTypedDict": ".updatetransactionop",
    "UserIdentifier": ".user_identifier",
    "UserIdentifierTypedDict": ".user_identifier",
    "UserIdentity": ".user_identity",
    "UserIdentityTypedDict": ".user_identity",
    "V1AccountsView": ".v1_accounts_view",
    "V1AccountsViewTypedDict": ".v1_accounts_view",
    "VoidTransactionRequest": ".voidtransactionop",
    "VoidTransactionRequestTypedDict": ".voidtransactionop",
    "Webhook": ".webhook",
    "WebhookTypedDict": ".webhook",
    "WebhookEventGroup": ".webhook_event_group",
    "WebhooksType": ".webhooks_type",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
