"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_address_listing_input import (
    ThreeDot3Dot7AddressListingInput,
    ThreeDot3Dot7AddressListingInputTypedDict,
)
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    SecurityMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ACCOUNT_ADDRESS_CREATE_OP_SERVERS = [
    "https://{environment}.bolt.com/v3",
]


class AccountAddressCreateSecurityTypedDict(TypedDict):
    three_dot_3_dot_7_oauth: str
    three_dot_3_dot_7_api_key: str


class AccountAddressCreateSecurity(BaseModel):
    three_dot_3_dot_7_oauth: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", field_name="Authorization"
            )
        ),
    ]

    three_dot_3_dot_7_api_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ]


class AccountAddressCreateRequestTypedDict(TypedDict):
    x_publishable_key: str
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""
    three_dot_3_dot_7_address_listing: ThreeDot3Dot7AddressListingInputTypedDict
    x_merchant_client_id: NotRequired[str]
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""


class AccountAddressCreateRequest(BaseModel):
    x_publishable_key: Annotated[
        str,
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""

    three_dot_3_dot_7_address_listing: Annotated[
        ThreeDot3Dot7AddressListingInput,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_merchant_client_id: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Merchant-Client-Id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""
