"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AddressChangeRequestMetadataViewTypedDict(TypedDict):
    can_change_shipping_address: NotRequired[bool]
    id: NotRequired[str]
    status: NotRequired[str]
    ticket_id: NotRequired[str]
    ticket_status: NotRequired[str]


class AddressChangeRequestMetadataView(BaseModel):
    can_change_shipping_address: Optional[bool] = None

    id: Optional[str] = None

    status: Optional[str] = None

    ticket_id: Optional[str] = None

    ticket_status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "can_change_shipping_address",
                "id",
                "status",
                "ticket_id",
                "ticket_status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
