"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .merchant_credit_card_authorization import (
    MerchantCreditCardAuthorization,
    MerchantCreditCardAuthorizationTypedDict,
)
from .merchant_credit_card_authorization_recharge import (
    MerchantCreditCardAuthorizationRecharge,
    MerchantCreditCardAuthorizationRechargeTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from bolt_api_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    SecurityMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class AuthorizeTransactionSecurityTypedDict(TypedDict):
    o_auth: str
    x_api_key: str


class AuthorizeTransactionSecurity(BaseModel):
    o_auth: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="oauth2",
                composite=True,
                field_name="Authorization",
            )
        ),
    ]

    x_api_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                composite=True,
                field_name="X-API-Key",
            )
        ),
    ]


AuthorizeTransactionRequestBodyTypedDict = TypeAliasType(
    "AuthorizeTransactionRequestBodyTypedDict",
    Union[
        MerchantCreditCardAuthorizationRechargeTypedDict,
        MerchantCreditCardAuthorizationTypedDict,
    ],
)
r"""**Authorize a Transaction**
* • `merchant_credit_card_authorization`: For authorizing with a new, unsaved card. This can be for a guest checkout flow, one-time payment, or an existing Bolt shopper.
* • `merchant_credit_card_authorization_recharge`: For authorizing a card using a shoppers saved payment methods.
* • **Anytime the shopper is paying while logged-in attach their OAuth `access_token` to the request.**

"""


AuthorizeTransactionRequestBody = TypeAliasType(
    "AuthorizeTransactionRequestBody",
    Union[MerchantCreditCardAuthorizationRecharge, MerchantCreditCardAuthorization],
)
r"""**Authorize a Transaction**
* • `merchant_credit_card_authorization`: For authorizing with a new, unsaved card. This can be for a guest checkout flow, one-time payment, or an existing Bolt shopper.
* • `merchant_credit_card_authorization_recharge`: For authorizing a card using a shoppers saved payment methods.
* • **Anytime the shopper is paying while logged-in attach their OAuth `access_token` to the request.**

"""


class AuthorizeTransactionRequestTypedDict(TypedDict):
    x_publishable_key: NotRequired[str]
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED]."""
    idempotency_key: NotRequired[str]
    r"""A key created by merchants that ensures `POST` and `PATCH` requests are only performed once. [Read more about Idempotent Requests here](/developers/references/idempotency/)."""
    request_body: NotRequired[AuthorizeTransactionRequestBodyTypedDict]
    r"""**Authorize a Transaction**
    * • `merchant_credit_card_authorization`: For authorizing with a new, unsaved card. This can be for a guest checkout flow, one-time payment, or an existing Bolt shopper.
    * • `merchant_credit_card_authorization_recharge`: For authorizing a card using a shoppers saved payment methods.
    * • **Anytime the shopper is paying while logged-in attach their OAuth `access_token` to the request.**

    """


class AuthorizeTransactionRequest(BaseModel):
    x_publishable_key: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED]."""

    idempotency_key: Annotated[
        Optional[str],
        pydantic.Field(alias="Idempotency-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A key created by merchants that ensures `POST` and `PATCH` requests are only performed once. [Read more about Idempotent Requests here](/developers/references/idempotency/)."""

    request_body: Annotated[
        Optional[AuthorizeTransactionRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""**Authorize a Transaction**
    * • `merchant_credit_card_authorization`: For authorizing with a new, unsaved card. This can be for a guest checkout flow, one-time payment, or an existing Bolt shopper.
    * • `merchant_credit_card_authorization_recharge`: For authorizing a card using a shoppers saved payment methods.
    * • **Anytime the shopper is paying while logged-in attach their OAuth `access_token` to the request.**

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Publishable-Key", "Idempotency-Key", "RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
