"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amount_view import AmountView, AmountViewTypedDict
from .capture_status import CaptureStatus
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class CaptureViewType(str, Enum):
    r"""Fee type options. **Nullable** for Transactions Details."""

    NET = "net"
    PROCESSING_FEE = "processing_fee"
    RISK_FEE = "risk_fee"
    APM_FEE = "apm_fee"
    NETWORK_FEE = "network_fee"
    PLATFORM_FEE = "platform_fee"
    BOLT_ACCOUNT_FEE = "bolt_account_fee"


class SplitTypedDict(TypedDict):
    r"""A split of fees by type and amount."""

    amount: NotRequired[AmountViewTypedDict]
    type: NotRequired[CaptureViewType]
    r"""Fee type options. **Nullable** for Transactions Details.

    """


class Split(BaseModel):
    r"""A split of fees by type and amount."""

    amount: Optional[AmountView] = None

    type: Optional[CaptureViewType] = None
    r"""Fee type options. **Nullable** for Transactions Details.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CaptureViewTypedDict(TypedDict):
    r"""Deprecated. Use `captures`."""

    amount: NotRequired[AmountViewTypedDict]
    id: NotRequired[str]
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    metadata: NotRequired[Dict[str, str]]
    r"""Additional information about the capture. For example, the processor capture ID. **Nullable** for Transactions Details."""
    splits: NotRequired[List[SplitTypedDict]]
    r"""A split of fees by type and amount. **Nullable** for Transactions Details."""
    status: NotRequired[CaptureStatus]
    r"""The status of the capture. **Nullable** for Transactions Details."""


class CaptureView(BaseModel):
    r"""Deprecated. Use `captures`."""

    amount: Optional[AmountView] = None

    id: Optional[str] = None
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    metadata: Optional[Dict[str, str]] = None
    r"""Additional information about the capture. For example, the processor capture ID. **Nullable** for Transactions Details."""

    splits: Optional[List[Split]] = None
    r"""A split of fees by type and amount. **Nullable** for Transactions Details."""

    status: Optional[CaptureStatus] = None
    r"""The status of the capture. **Nullable** for Transactions Details."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["amount", "id", "merchant_event_id", "metadata", "splits", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
