"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CartAddOnTypedDict(TypedDict):
    r"""A list of up to 3 add-ons that are displayed to the shopper."""

    name: str
    r"""The name of the product being displayed as an add on."""
    price: float
    r"""The price of the product add on in cents (1/100)."""
    product_id: str
    r"""The the ID of the product being displayed as an add on."""
    description: NotRequired[str]
    r"""The description of the product being displayed as an add on."""
    image_url: NotRequired[str]
    r"""The URL of the image displayed for the add on product."""
    product_page_url: NotRequired[str]
    r"""The URL to the product page of the product being displayed as an add on."""


class CartAddOn(BaseModel):
    r"""A list of up to 3 add-ons that are displayed to the shopper."""

    name: str
    r"""The name of the product being displayed as an add on."""

    price: float
    r"""The price of the product add on in cents (1/100)."""

    product_id: Annotated[str, pydantic.Field(alias="productId")]
    r"""The the ID of the product being displayed as an add on."""

    description: Optional[str] = None
    r"""The description of the product being displayed as an add on."""

    image_url: Annotated[Optional[str], pydantic.Field(alias="imageUrl")] = None
    r"""The URL of the image displayed for the add on product."""

    product_page_url: Annotated[
        Optional[str], pydantic.Field(alias="productPageUrl")
    ] = None
    r"""The URL to the product page of the product being displayed as an add on."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "imageUrl", "productPageUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CartAddOn.model_rebuild()
except NameError:
    pass
