"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CartLoyaltyRewardsTypedDict(TypedDict):
    amount: NotRequired[float]
    r"""The reward amount in cents (1/100)."""
    coupon_code: NotRequired[str]
    r"""The loyalty reward's coupon code."""
    description: NotRequired[str]
    r"""A description of the loyalty reward that will be shown to the shopper."""
    details: NotRequired[str]
    r"""Internal-facing metadata for the Loyalty Rewards. Ideal for adding any other identifying information about the reward, including a duplication of the original loyalty reward json response from the loyalty provider as shown in the example provided. If you choose to use this field to hold json, enclose the content in single quotes to force a string value."""
    points: NotRequired[float]
    r"""The number of points needed for this reward."""
    source: NotRequired[str]
    r"""The loyalty rewards provider."""
    type: NotRequired[str]
    r"""The type of loyalty reward."""


class CartLoyaltyRewards(BaseModel):
    amount: Optional[float] = None
    r"""The reward amount in cents (1/100)."""

    coupon_code: Optional[str] = None
    r"""The loyalty reward's coupon code."""

    description: Optional[str] = None
    r"""A description of the loyalty reward that will be shown to the shopper."""

    details: Optional[str] = None
    r"""Internal-facing metadata for the Loyalty Rewards. Ideal for adding any other identifying information about the reward, including a duplication of the original loyalty reward json response from the loyalty provider as shown in the example provided. If you choose to use this field to hold json, enclose the content in single quotes to force a string value."""

    points: Optional[float] = None
    r"""The number of points needed for this reward."""

    source: Optional[str] = None
    r"""The loyalty rewards provider."""

    type: Optional[str] = None
    r"""The type of loyalty reward."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "coupon_code",
                "description",
                "details",
                "points",
                "source",
                "type",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
