"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ConsumerSummaryViewTypedDict(TypedDict):
    first_name: NotRequired[str]
    r"""The given name of the person associated with this record."""
    id: NotRequired[str]
    last_name: NotRequired[str]
    r"""The surname of the person associated with this record."""


class ConsumerSummaryView(BaseModel):
    first_name: Optional[str] = None
    r"""The given name of the person associated with this record."""

    id: Optional[str] = None

    last_name: Optional[str] = None
    r"""The surname of the person associated with this record."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["first_name", "id", "last_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
