"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address_account import AddressAccount, AddressAccountTypedDict
from .payment_method_account import PaymentMethodAccount, PaymentMethodAccountTypedDict
from .profile import Profile, ProfileTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateAccountInputTypedDict(TypedDict):
    r"""The details needed to create a Bolt account."""

    profile: ProfileTypedDict
    r"""The first name, last name, email address, and phone number of a shopper."""
    addresses: NotRequired[List[AddressAccountTypedDict]]
    r"""A list of physical shipping addresses associated with this account."""
    payment_methods: NotRequired[List[PaymentMethodAccountTypedDict]]
    r"""A list of payment methods associated with this account."""


class CreateAccountInput(BaseModel):
    r"""The details needed to create a Bolt account."""

    profile: Profile
    r"""The first name, last name, email address, and phone number of a shopper."""

    addresses: Optional[List[AddressAccount]] = None
    r"""A list of physical shipping addresses associated with this account."""

    payment_methods: Optional[List[PaymentMethodAccount]] = None
    r"""A list of payment methods associated with this account."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["addresses", "payment_methods"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
