"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .emails import Emails, EmailsTypedDict
from .phones_with_country_code import (
    PhonesWithCountryCode,
    PhonesWithCountryCodeTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreditCardUserTypedDict(TypedDict):
    r"""The credit card user."""

    emails: NotRequired[List[EmailsTypedDict]]
    r"""A list of email addresses. **Nullable** for Transactions Details."""
    first_name: NotRequired[str]
    r"""The person's first name."""
    id: NotRequired[str]
    r"""The shopper's unique ID."""
    last_name: NotRequired[str]
    r"""The person's last name."""
    phones: NotRequired[List[PhonesWithCountryCodeTypedDict]]
    r"""A list of phone numbers."""


class CreditCardUser(BaseModel):
    r"""The credit card user."""

    emails: Optional[List[Emails]] = None
    r"""A list of email addresses. **Nullable** for Transactions Details."""

    first_name: Optional[str] = None
    r"""The person's first name."""

    id: Optional[str] = None
    r"""The shopper's unique ID."""

    last_name: Optional[str] = None
    r"""The person's last name."""

    phones: Optional[List[PhonesWithCountryCode]] = None
    r"""A list of phone numbers."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["emails", "first_name", "id", "last_name", "phones"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
