"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .credit_card_void_cause import CreditCardVoidCause
from .credit_card_void_status import CreditCardVoidStatus
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreditCardVoidViewTypedDict(TypedDict):
    cause: NotRequired[CreditCardVoidCause]
    r"""Specifies why this particular transaction is voided."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    status: NotRequired[CreditCardVoidStatus]
    r"""The status of the void request."""
    void: NotRequired[str]
    r"""The void ID returned from the payment processor."""


class CreditCardVoidView(BaseModel):
    cause: Optional[CreditCardVoidCause] = None
    r"""Specifies why this particular transaction is voided."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    status: Optional[CreditCardVoidStatus] = None
    r"""The status of the void request."""

    void: Optional[str] = None
    r"""The void ID returned from the payment processor."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cause", "merchant_event_id", "status", "void"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
