"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amount_view import AmountView, AmountViewTypedDict
from .capture_status import CaptureStatus
from .transaction_splits_view import (
    TransactionSplitsView,
    TransactionSplitsViewTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class CreditCardCaptureViewTypedDict(TypedDict):
    amount: NotRequired[AmountViewTypedDict]
    id: NotRequired[str]
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    metadata: NotRequired[Dict[str, str]]
    splits: NotRequired[TransactionSplitsViewTypedDict]
    status: NotRequired[CaptureStatus]
    r"""The status of the capture. **Nullable** for Transactions Details."""


class CreditCardCaptureView(BaseModel):
    amount: Optional[AmountView] = None

    id: Optional[str] = None
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    metadata: Optional[Dict[str, str]] = None

    splits: Optional[TransactionSplitsView] = None

    status: Optional[CaptureStatus] = None
    r"""The status of the capture. **Nullable** for Transactions Details."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["amount", "id", "merchant_event_id", "metadata", "splits", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
