"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CustomFieldViewCheckoutStep(str, Enum):
    SHIPPING_STEP = "SHIPPING_STEP"
    DELIVERY_STEP = "DELIVERY_STEP"
    PAYMENT_STEP = "PAYMENT_STEP"
    ACCOUNT_REGISTRATION_SSO = "ACCOUNT_REGISTRATION_SSO"


class CustomFieldViewContext(str, Enum):
    CHECKOUT = "CHECKOUT"
    SSO = "SSO"


class CustomFieldViewTypedDict(TypedDict):
    checkout_step: NotRequired[CustomFieldViewCheckoutStep]
    dynamic: NotRequired[bool]
    context: NotRequired[CustomFieldViewContext]
    external_id: NotRequired[str]
    field_setup: NotRequired[str]
    label: NotRequired[str]
    position: NotRequired[float]
    public_id: NotRequired[str]
    required: NotRequired[bool]
    subscribe_to_newsletter: NotRequired[bool]


class CustomFieldView(BaseModel):
    checkout_step: Optional[CustomFieldViewCheckoutStep] = None

    dynamic: Optional[bool] = None

    context: Optional[CustomFieldViewContext] = None

    external_id: Optional[str] = None

    field_setup: Optional[str] = None

    label: Optional[str] = None

    position: Optional[float] = None

    public_id: Optional[str] = None

    required: Optional[bool] = None

    subscribe_to_newsletter: Annotated[
        Optional[bool], pydantic.Field(alias="subscribeToNewsletter")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "checkout_step",
                "dynamic",
                "context",
                "external_id",
                "field_setup",
                "label",
                "position",
                "public_id",
                "required",
                "subscribeToNewsletter",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CustomFieldView.model_rebuild()
except NameError:
    pass
