"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CheckoutSetup(str, Enum):
    SHIPPING_STEP = "shipping_step"
    DELIVERY_STEP = "delivery_step"
    PAYMENT_STEP = "payment_step"
    ACCOUNT_REGISTRATION_SSO = "account_registration_sso"


class CustomFieldsContext(str, Enum):
    r"""The app context of where the custom field is used."""

    CHECKOUT = "CHECKOUT"
    SSO = "SSO"


class CustomFieldsTypedDict(TypedDict):
    checkout_setup: NotRequired[CheckoutSetup]
    dynamic: NotRequired[bool]
    r"""Defines whether the field is dynamic."""
    context: NotRequired[CustomFieldsContext]
    r"""The app context of where the custom field is used."""
    external_id: NotRequired[str]
    r"""The external ID for the custom field."""
    field_setup: NotRequired[str]
    label: NotRequired[str]
    r"""The displayed label for the custom field, seen by the shopper."""
    position: NotRequired[int]
    public_id: NotRequired[str]
    r"""The internal ID for the custom field."""
    required: NotRequired[bool]
    r"""Defines if the field must be completed to check out."""
    subscribe_to_newsletter: NotRequired[bool]
    r"""Defines whether the shopper is opted into a newsletter or not."""


class CustomFields(BaseModel):
    checkout_setup: Optional[CheckoutSetup] = None

    dynamic: Optional[bool] = None
    r"""Defines whether the field is dynamic."""

    context: Optional[CustomFieldsContext] = None
    r"""The app context of where the custom field is used."""

    external_id: Optional[str] = None
    r"""The external ID for the custom field."""

    field_setup: Optional[str] = None

    label: Optional[str] = None
    r"""The displayed label for the custom field, seen by the shopper."""

    position: Optional[int] = None

    public_id: Optional[str] = None
    r"""The internal ID for the custom field."""

    required: Optional[bool] = None
    r"""Defines if the field must be completed to check out."""

    subscribe_to_newsletter: Optional[bool] = None
    r"""Defines whether the shopper is opted into a newsletter or not."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "checkout_setup",
                "dynamic",
                "context",
                "external_id",
                "field_setup",
                "label",
                "position",
                "public_id",
                "required",
                "subscribe_to_newsletter",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
