"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .email_priority import EmailPriority
from .email_status import EmailStatus
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EmailsTypedDict(TypedDict):
    r"""An object of user email."""

    address: NotRequired[str]
    r"""An email address."""
    id: NotRequired[str]
    r"""This is the ID for the email address associated with the shopper."""
    priority: NotRequired[EmailPriority]
    r"""This is the priority of the contact method. This field's contents are not displayed in the transaction details view."""
    status: NotRequired[EmailStatus]
    r"""This is the status of the contact method."""


class Emails(BaseModel):
    r"""An object of user email."""

    address: Optional[str] = None
    r"""An email address."""

    id: Optional[str] = None
    r"""This is the ID for the email address associated with the shopper."""

    priority: Optional[EmailPriority] = None
    r"""This is the priority of the contact method. This field's contents are not displayed in the transaction details view."""

    status: Optional[EmailStatus] = None
    r"""This is the status of the contact method."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "id", "priority", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
