"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ErrorBoltAPITypedDict(TypedDict):
    r"""Error object containing custom error information"""

    code: NotRequired[int]
    r"""Custom-defined Bolt error code. This can be used to programmatically react to specific errors."""
    message: NotRequired[str]
    r"""Human-readable description of the error for developers. Should not be shown to users and is not localized."""


class ErrorBoltAPI(BaseModel):
    r"""Error object containing custom error information"""

    code: Optional[int] = None
    r"""Custom-defined Bolt error code. This can be used to programmatically react to specific errors."""

    message: Optional[str] = None
    r"""Human-readable description of the error for developers. Should not be shown to users and is not localized."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
