"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhook_event_group import WebhookEventGroup
from bolt_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class EventGroupCreateWebhookTypedDict(TypedDict):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""
    url: str
    r"""The full URL to receive webhook notifications."""
    event_group: NotRequired[Nullable[WebhookEventGroup]]
    r"""Subscribe to a group of events.
    `all`: subscribe to all existing and future event types

    """


class EventGroupCreateWebhook(BaseModel):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""

    url: str
    r"""The full URL to receive webhook notifications."""

    event_group: OptionalNullable[WebhookEventGroup] = UNSET
    r"""Subscribe to a group of events.
    `all`: subscribe to all existing and future event types

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event_group"])
        nullable_fields = set(["event_group"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
