"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .webhooks_type import WebhooksType
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class EventsArrayCreateWebhookTypedDict(TypedDict):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""
    url: str
    r"""The full URL to receive webhook notifications."""
    events: NotRequired[List[WebhooksType]]
    r"""If `webhook_event_group` is null, pick a list of notification events to subscribe to.

    """


class EventsArrayCreateWebhook(BaseModel):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""

    url: str
    r"""The full URL to receive webhook notifications."""

    events: Optional[List[WebhooksType]] = None
    r"""If `webhook_event_group` is null, pick a list of notification events to subscribe to.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["events"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
