"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cart_item import CartItem, CartItemTypedDict
from .cart_shipment import CartShipment, CartShipmentTypedDict
from .digital_delivery import DigitalDelivery, DigitalDeliveryTypedDict
from .in_store_cart_shipment import InStoreCartShipment, InStoreCartShipmentTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FulfillmentType(str, Enum):
    PHYSICAL_DOOR_DELIVERY = "physical_door_delivery"
    PHYSICAL_SHIP_TO_STORE = "physical_ship_to_store"
    PHYSICAL_IN_STORE_PICKUP = "physical_in_store_pickup"
    DIGITAL_DOWNLOAD = "digital_download"
    DIGITAL_NO_DELIVERY = "digital_no_delivery"


class FulfillmentTypedDict(TypedDict):
    r"""Defines the shipments associated with the cart items."""

    cart_items: NotRequired[List[CartItemTypedDict]]
    cart_shipment: NotRequired[CartShipmentTypedDict]
    r"""A cart that is being prepared for shipment"""
    digital_delivery: NotRequired[DigitalDeliveryTypedDict]
    in_store_cart_shipment: NotRequired[InStoreCartShipmentTypedDict]
    type: NotRequired[FulfillmentType]


class Fulfillment(BaseModel):
    r"""Defines the shipments associated with the cart items."""

    cart_items: Optional[List[CartItem]] = None

    cart_shipment: Optional[CartShipment] = None
    r"""A cart that is being prepared for shipment"""

    digital_delivery: Optional[DigitalDelivery] = None

    in_store_cart_shipment: Optional[InStoreCartShipment] = None

    type: Optional[FulfillmentType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cart_items",
                "cart_shipment",
                "digital_delivery",
                "in_store_cart_shipment",
                "type",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
