"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .i_cart_item_view import ICartItemView, ICartItemViewTypedDict
from .i_cart_shipment_view import ICartShipmentView, ICartShipmentViewTypedDict
from .in_store_shipment2 import InStoreShipment2, InStoreShipment2TypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class FulfillmentViewTypedDict(TypedDict):
    cart_shipment: NotRequired[ICartShipmentViewTypedDict]
    fulfillment_type: NotRequired[str]
    id: NotRequired[str]
    in_store_cart_shipment: NotRequired[InStoreShipment2TypedDict]
    r"""A cart that is being prepared for shipment"""
    items: NotRequired[List[ICartItemViewTypedDict]]


class FulfillmentView(BaseModel):
    cart_shipment: Optional[ICartShipmentView] = None

    fulfillment_type: Optional[str] = None

    id: Optional[str] = None

    in_store_cart_shipment: Optional[InStoreShipment2] = None
    r"""A cart that is being prepared for shipment"""

    items: Optional[List[ICartItemView]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cart_shipment",
                "fulfillment_type",
                "id",
                "in_store_cart_shipment",
                "items",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
