"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GetTestCreditCardTokenResponseTypedDict(TypedDict):
    r"""Successfully Fetched Credit Card Token"""

    token: NotRequired[str]
    r"""The newly generated credit card token."""
    expiry: NotRequired[int]
    r"""The date at which the token expires. A token must be used within 15 minutes of creation."""
    last4: NotRequired[str]
    r"""The last 4 digits of the card number."""
    bin: NotRequired[str]
    r"""The credit card bin."""
    network: NotRequired[str]
    r"""The credit card network."""


class GetTestCreditCardTokenResponse(BaseModel):
    r"""Successfully Fetched Credit Card Token"""

    token: Optional[str] = None
    r"""The newly generated credit card token."""

    expiry: Optional[int] = None
    r"""The date at which the token expires. A token must be used within 15 minutes of creation."""

    last4: Optional[str] = None
    r"""The last 4 digits of the card number."""

    bin: Optional[str] = None
    r"""The credit card bin."""

    network: Optional[str] = None
    r"""The credit card network."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["token", "expiry", "last4", "bin", "network"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
