"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GiftOptionsTypedDict(TypedDict):
    r"""Contains the gift option settings for wrapping and custom messages."""

    message: NotRequired[str]
    r"""Includes the gift message written by the shopper."""
    wrap: NotRequired[bool]
    r"""Defines whether gift wrapping was requested."""


class GiftOptions(BaseModel):
    r"""Contains the gift option settings for wrapping and custom messages."""

    message: Optional[str] = None
    r"""Includes the gift message written by the shopper."""

    wrap: Optional[bool] = None
    r"""Defines whether gift wrapping was requested."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message", "wrap"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
