"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GiftOptionViewTypedDict(TypedDict):
    r"""Defines which gift options are hidden."""

    hide_gift_message: NotRequired[bool]
    hide_gift_wrap: NotRequired[bool]


class GiftOptionView(BaseModel):
    r"""Defines which gift options are hidden."""

    hide_gift_message: Optional[bool] = None

    hide_gift_wrap: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hide_gift_message", "hide_gift_wrap"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
