"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address_view import AddressView, AddressViewTypedDict
from .amount_view import AmountView, AmountViewTypedDict
from .gift_option_view import GiftOptionView, GiftOptionViewTypedDict
from .i_description_part import IDescriptionPart, IDescriptionPartTypedDict
from .i_description_tooltip import IDescriptionTooltip, IDescriptionTooltipTypedDict
from .i_weight import IWeight, IWeightTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ICartShipmentViewPackageDimensionTypedDict(TypedDict):
    depth: NotRequired[float]
    height: NotRequired[float]
    unit: NotRequired[str]
    width: NotRequired[float]


class ICartShipmentViewPackageDimension(BaseModel):
    depth: Optional[float] = None

    height: Optional[float] = None

    unit: Optional[str] = None

    width: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["depth", "height", "unit", "width"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ICartShipmentViewTypedDict(TypedDict):
    carrier: NotRequired[str]
    r"""The carrier used to deliver the shipment."""
    cost: NotRequired[AmountViewTypedDict]
    default: NotRequired[bool]
    description: NotRequired[List[IDescriptionPartTypedDict]]
    description_tooltips: NotRequired[List[IDescriptionTooltipTypedDict]]
    estimated_delivery_date: NotRequired[datetime]
    expedited: NotRequired[bool]
    r"""Used to determine whether a shipment has been expedited or not."""
    gift_options: NotRequired[GiftOptionViewTypedDict]
    r"""Defines which gift options are hidden."""
    id: NotRequired[str]
    package_dimension: NotRequired[ICartShipmentViewPackageDimensionTypedDict]
    package_type: NotRequired[str]
    package_weight: NotRequired[IWeightTypedDict]
    reference: NotRequired[str]
    service: NotRequired[str]
    shipping_address: NotRequired[AddressViewTypedDict]
    r"""The address object returned in the response."""
    shipping_method: NotRequired[str]
    signature: NotRequired[str]
    tax_amount: NotRequired[AmountViewTypedDict]
    total_weight: NotRequired[IWeightTypedDict]
    type: NotRequired[str]


class ICartShipmentView(BaseModel):
    carrier: Optional[str] = None
    r"""The carrier used to deliver the shipment."""

    cost: Optional[AmountView] = None

    default: Optional[bool] = None

    description: Optional[List[IDescriptionPart]] = None

    description_tooltips: Optional[List[IDescriptionTooltip]] = None

    estimated_delivery_date: Optional[datetime] = None

    expedited: Optional[bool] = None
    r"""Used to determine whether a shipment has been expedited or not."""

    gift_options: Optional[GiftOptionView] = None
    r"""Defines which gift options are hidden."""

    id: Optional[str] = None

    package_dimension: Optional[ICartShipmentViewPackageDimension] = None

    package_type: Optional[str] = None

    package_weight: Optional[IWeight] = None

    reference: Optional[str] = None

    service: Optional[str] = None

    shipping_address: Optional[AddressView] = None
    r"""The address object returned in the response."""

    shipping_method: Optional[str] = None

    signature: Optional[str] = None

    tax_amount: Optional[AmountView] = None

    total_weight: Optional[IWeight] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "carrier",
                "cost",
                "default",
                "description",
                "description_tooltips",
                "estimated_delivery_date",
                "expedited",
                "gift_options",
                "id",
                "package_dimension",
                "package_type",
                "package_weight",
                "reference",
                "service",
                "shipping_address",
                "shipping_method",
                "signature",
                "tax_amount",
                "total_weight",
                "type",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
