"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ICartItemExternalInputsTypedDict(TypedDict):
    shopify_line_item_reference: NotRequired[float]
    shopify_product_reference: NotRequired[float]
    shopify_product_variant_reference: NotRequired[float]


class ICartItemExternalInputs(BaseModel):
    shopify_line_item_reference: Optional[float] = None

    shopify_product_reference: Optional[float] = None

    shopify_product_variant_reference: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "shopify_line_item_reference",
                "shopify_product_reference",
                "shopify_product_variant_reference",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
