"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import FieldMetadata, QueryParamMetadata, SecurityMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


LIST_SUBSCRIPTIONS_OP_SERVERS = [
    # The Production URL (Live Data).
    "https://api.bolt.com",
    # The Sandbox URL (Test Data).
    "https://api-sandbox.bolt.com",
    # The Staging URL (Staged Data).
    "https://api-staging.bolt.com",
]


class ListSubscriptionsSecurityTypedDict(TypedDict):
    v1_x_api_key: NotRequired[str]
    v1_x_publishable_key: NotRequired[str]


class ListSubscriptionsSecurity(BaseModel):
    v1_x_api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ] = None

    v1_x_publishable_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Publishable-Key",
            )
        ),
    ] = None


class ListSubscriptionsRequestTypedDict(TypedDict):
    customer_ids: NotRequired[str]
    r"""Comma-separated list of customer IDs to filter subscriptions."""
    emails: NotRequired[str]
    r"""Comma-separated list of email addresses to filter subscriptions."""
    product_ids: NotRequired[str]
    r"""Comma-separated list of product IDs to filter subscriptions."""
    plan_ids: NotRequired[str]
    r"""Comma-separated list of plan IDs to filter subscriptions."""


class ListSubscriptionsRequest(BaseModel):
    customer_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of customer IDs to filter subscriptions."""

    emails: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of email addresses to filter subscriptions."""

    product_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of product IDs to filter subscriptions."""

    plan_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of plan IDs to filter subscriptions."""
