"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import FieldMetadata, QueryParamMetadata, SecurityMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


LIST_SUBSCRIPTION_ORDERS_OP_SERVERS = [
    # The Production URL (Live Data).
    "https://api.bolt.com",
    # The Sandbox URL (Test Data).
    "https://api-sandbox.bolt.com",
    # The Staging URL (Staged Data).
    "https://api-staging.bolt.com",
]


class ListSubscriptionOrdersSecurityTypedDict(TypedDict):
    v1_x_api_key: NotRequired[str]
    v1_x_publishable_key: NotRequired[str]


class ListSubscriptionOrdersSecurity(BaseModel):
    v1_x_api_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ] = None

    v1_x_publishable_key: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-Publishable-Key",
            )
        ),
    ] = None


class ListSubscriptionOrdersRequestTypedDict(TypedDict):
    subscription_ids: NotRequired[str]
    r"""Comma-separated list of subscription IDs to filter orders."""


class ListSubscriptionOrdersRequest(BaseModel):
    subscription_ids: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of subscription IDs to filter orders."""
