"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ManualDisputesStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"


class ManualDisputesTypedDict(TypedDict):
    amount: NotRequired[int]
    r"""The amount in cents. **Nullable** for Transactions Details."""
    currency: NotRequired[str]
    r"""The 3-digit ISO code for the currency. **Nullable** for Transactions Details."""
    delivery_evidence: NotRequired[str]
    delivery_link: NotRequired[str]
    dispute_evidence: NotRequired[str]
    dispute_link: NotRequired[str]
    other_evidence: NotRequired[str]
    other_link: NotRequired[str]
    reason: NotRequired[str]
    status: NotRequired[ManualDisputesStatus]


class ManualDisputes(BaseModel):
    amount: Optional[int] = None
    r"""The amount in cents. **Nullable** for Transactions Details."""

    currency: Optional[str] = None
    r"""The 3-digit ISO code for the currency. **Nullable** for Transactions Details."""

    delivery_evidence: Optional[str] = None

    delivery_link: Optional[str] = None

    dispute_evidence: Optional[str] = None

    dispute_link: Optional[str] = None

    other_evidence: Optional[str] = None

    other_link: Optional[str] = None

    reason: Optional[str] = None

    status: Optional[ManualDisputesStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "currency",
                "delivery_evidence",
                "delivery_link",
                "dispute_evidence",
                "dispute_link",
                "other_evidence",
                "other_link",
                "reason",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
