"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ManualDisputeViewStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"


class ManualDisputeViewTypedDict(TypedDict):
    amount: NotRequired[float]
    currency: NotRequired[str]
    delivery_evidence: NotRequired[str]
    delivery_link: NotRequired[str]
    dispute_evidence: NotRequired[str]
    dispute_link: NotRequired[str]
    other_evidence: NotRequired[List[str]]
    other_link: NotRequired[List[str]]
    reason: NotRequired[str]
    status: NotRequired[ManualDisputeViewStatus]


class ManualDisputeView(BaseModel):
    amount: Optional[float] = None

    currency: Optional[str] = None

    delivery_evidence: Optional[str] = None

    delivery_link: Optional[str] = None

    dispute_evidence: Optional[str] = None

    dispute_link: Optional[str] = None

    other_evidence: Optional[List[str]] = None

    other_link: Optional[List[str]] = None

    reason: Optional[str] = None

    status: Optional[ManualDisputeViewStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "amount",
                "currency",
                "delivery_evidence",
                "delivery_link",
                "dispute_evidence",
                "dispute_link",
                "other_evidence",
                "other_link",
                "reason",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
