"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Dict
from typing_extensions import NotRequired, TypedDict


class MarketplaceCommissionFeeTypedDict(TypedDict):
    r"""Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models."""

    bps: float
    r"""The commission fee expressed in basis points (1 bps = 0.01%). For example, 100 bps = 1%, 250 bps = 2.5%."""
    flat_cents: float
    r"""The fixed commission fee amount in cents, applied regardless of transaction value."""
    metadata: NotRequired[Nullable[Dict[str, str]]]
    r"""Additional contextual information about the commission fee, such as plan type, tier level, or other business rules."""


class MarketplaceCommissionFee(BaseModel):
    r"""Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models."""

    bps: float
    r"""The commission fee expressed in basis points (1 bps = 0.01%). For example, 100 bps = 1%, 250 bps = 2.5%."""

    flat_cents: float
    r"""The fixed commission fee amount in cents, applied regardless of transaction value."""

    metadata: OptionalNullable[Dict[str, str]] = UNSET
    r"""Additional contextual information about the commission fee, such as plan type, tier level, or other business rules."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metadata"])
        nullable_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
