"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .merchant_divisions_identifiers_view import (
    MerchantDivisionsIdentifiersView,
    MerchantDivisionsIdentifiersViewTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class MerchantIdentifiersViewTypedDict(TypedDict):
    merchant_divisions: NotRequired[List[MerchantDivisionsIdentifiersViewTypedDict]]
    merchant_id: NotRequired[str]
    r"""The public ID of this merchant."""
    signing_secret: NotRequired[str]
    r"""Bolt generates one secret key per merchant and uses it to securely sign requests."""


class MerchantIdentifiersView(BaseModel):
    merchant_divisions: Optional[List[MerchantDivisionsIdentifiersView]] = None

    merchant_id: Optional[str] = None
    r"""The public ID of this merchant."""

    signing_secret: Optional[str] = None
    r"""Bolt generates one secret key per merchant and uses it to securely sign requests."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["merchant_divisions", "merchant_id", "signing_secret"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
