"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .merchant_onboarding_status_code import MerchantOnboardingStatusCode
from .merchant_status import MerchantStatus
from .transaction_operational_processor import (
    TransactionOperationalProcessor,
    TransactionOperationalProcessorTypedDict,
)
from .transaction_processor import TransactionProcessor
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class MerchantTypedDict(TypedDict):
    created_at: int
    r"""The date the merchant account was created.  **Nullable** for Transactions Details."""
    description: str
    r"""The description of the merchant account. **Nullable** for Transactions Details."""
    operational_processors: List[TransactionOperationalProcessorTypedDict]
    r"""**Nullable** for Transactions Details.

    """
    processor: TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""
    time_zone: str
    r"""The timezone of the merchant. **Nullable** for Transactions Details."""
    onboarding_status: NotRequired[MerchantOnboardingStatusCode]
    public_id: NotRequired[str]
    r"""The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions."""
    status: NotRequired[MerchantStatus]
    r"""The merchant's status:
    * `1` - Active
    * `2` - Inactive
    * `3` - Offboarding

    """


class Merchant(BaseModel):
    created_at: int
    r"""The date the merchant account was created.  **Nullable** for Transactions Details."""

    description: str
    r"""The description of the merchant account. **Nullable** for Transactions Details."""

    operational_processors: List[TransactionOperationalProcessor]
    r"""**Nullable** for Transactions Details.

    """

    processor: TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""

    time_zone: str
    r"""The timezone of the merchant. **Nullable** for Transactions Details."""

    onboarding_status: Optional[MerchantOnboardingStatusCode] = None

    public_id: Optional[str] = None
    r"""The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions."""

    status: Optional[MerchantStatus] = None
    r"""The merchant's status:
    * `1` - Active
    * `2` - Inactive
    * `3` - Offboarding

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["onboarding_status", "public_id", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
