"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .merchant_division_logo_view import (
    MerchantDivisionLogoView,
    MerchantDivisionLogoViewTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HookType(str, Enum):
    ONE = "1"
    TWO = "2"
    THREE = "3"
    FOUR = "4"
    FIVE = "5"
    SIX = "6"


class MerchantDivisionSummaryViewTypedDict(TypedDict):
    account_page_url: NotRequired[str]
    api_base_domain_url: NotRequired[str]
    base_domain_url: NotRequired[str]
    confirmation_redirect_url: NotRequired[str]
    create_order_url: NotRequired[str]
    debug_url: NotRequired[str]
    description: NotRequired[str]
    display_name: NotRequired[str]
    get_account_url: NotRequired[str]
    shopper_custom_fields_updated_url: NotRequired[str]
    hook_type: NotRequired[HookType]
    hook_url: NotRequired[str]
    id: NotRequired[str]
    is_universal_merchant_api: NotRequired[bool]
    is_webhooks_v2: NotRequired[bool]
    logo: NotRequired[MerchantDivisionLogoViewTypedDict]
    logo_dashboard: NotRequired[MerchantDivisionLogoViewTypedDict]
    merchant_id: NotRequired[str]
    mobile_app_domain_url: NotRequired[str]
    oauth_logout_url: NotRequired[str]
    oauth_redirect_url: NotRequired[str]
    platform: NotRequired[str]
    plugin_config_url: NotRequired[str]
    privacy_policy_url: NotRequired[str]
    product_info_url: NotRequired[str]
    public_id: NotRequired[str]
    remote_apiurl: NotRequired[str]
    shipping_and_tax_url: NotRequired[str]
    shipping_url: NotRequired[str]
    status: NotRequired[str]
    tax_url: NotRequired[str]
    terms_of_service_url: NotRequired[str]
    universal_merchant_api_url: NotRequired[str]
    update_cart_url: NotRequired[str]
    use_async_refunds_amazon_pay: NotRequired[bool]
    use_async_refunds_paypal: NotRequired[bool]
    validate_additional_account_data_url: NotRequired[str]
    merchant_password_login_url: NotRequired[str]
    r"""(Optional) Link shoppers can use to log into a merchant store via the Bolt SSO modal."""


class MerchantDivisionSummaryView(BaseModel):
    account_page_url: Optional[str] = None

    api_base_domain_url: Optional[str] = None

    base_domain_url: Optional[str] = None

    confirmation_redirect_url: Optional[str] = None

    create_order_url: Optional[str] = None

    debug_url: Optional[str] = None

    description: Optional[str] = None

    display_name: Optional[str] = None

    get_account_url: Optional[str] = None

    shopper_custom_fields_updated_url: Optional[str] = None

    hook_type: Optional[HookType] = None

    hook_url: Optional[str] = None

    id: Optional[str] = None

    is_universal_merchant_api: Optional[bool] = None

    is_webhooks_v2: Optional[bool] = None

    logo: Optional[MerchantDivisionLogoView] = None

    logo_dashboard: Optional[MerchantDivisionLogoView] = None

    merchant_id: Optional[str] = None

    mobile_app_domain_url: Optional[str] = None

    oauth_logout_url: Optional[str] = None

    oauth_redirect_url: Optional[str] = None

    platform: Optional[str] = None

    plugin_config_url: Optional[str] = None

    privacy_policy_url: Optional[str] = None

    product_info_url: Optional[str] = None

    public_id: Optional[str] = None

    remote_apiurl: Optional[str] = None

    shipping_and_tax_url: Optional[str] = None

    shipping_url: Optional[str] = None

    status: Optional[str] = None

    tax_url: Optional[str] = None

    terms_of_service_url: Optional[str] = None

    universal_merchant_api_url: Optional[str] = None

    update_cart_url: Optional[str] = None

    use_async_refunds_amazon_pay: Optional[bool] = None

    use_async_refunds_paypal: Optional[bool] = None

    validate_additional_account_data_url: Optional[str] = None

    merchant_password_login_url: Optional[str] = None
    r"""(Optional) Link shoppers can use to log into a merchant store via the Bolt SSO modal."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "account_page_url",
                "api_base_domain_url",
                "base_domain_url",
                "confirmation_redirect_url",
                "create_order_url",
                "debug_url",
                "description",
                "display_name",
                "get_account_url",
                "shopper_custom_fields_updated_url",
                "hook_type",
                "hook_url",
                "id",
                "is_universal_merchant_api",
                "is_webhooks_v2",
                "logo",
                "logo_dashboard",
                "merchant_id",
                "mobile_app_domain_url",
                "oauth_logout_url",
                "oauth_redirect_url",
                "platform",
                "plugin_config_url",
                "privacy_policy_url",
                "product_info_url",
                "public_id",
                "remote_apiurl",
                "shipping_and_tax_url",
                "shipping_url",
                "status",
                "tax_url",
                "terms_of_service_url",
                "universal_merchant_api_url",
                "update_cart_url",
                "use_async_refunds_amazon_pay",
                "use_async_refunds_paypal",
                "validate_additional_account_data_url",
                "merchant_password_login_url",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
