"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .o_auth_token_input import OAuthTokenInput, OAuthTokenInputTypedDict
from .o_auth_token_input_refresh import (
    OAuthTokenInputRefresh,
    OAuthTokenInputRefreshTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from bolt_api_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    get_discriminator,
)
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


OAuthTokenRequestBodyTypedDict = TypeAliasType(
    "OAuthTokenRequestBodyTypedDict",
    Union[OAuthTokenInputTypedDict, OAuthTokenInputRefreshTypedDict],
)


OAuthTokenRequestBody = Annotated[
    Union[
        Annotated[OAuthTokenInput, Tag("authorization_code")],
        Annotated[OAuthTokenInputRefresh, Tag("refresh_token")],
    ],
    Discriminator(lambda m: get_discriminator(m, "grant_type", "grant_type")),
]


class OAuthTokenRequestTypedDict(TypedDict):
    x_publishable_key: NotRequired[str]
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED]."""
    request_body: NotRequired[OAuthTokenRequestBodyTypedDict]


class OAuthTokenRequest(BaseModel):
    x_publishable_key: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED]."""

    request_body: Annotated[
        Optional[OAuthTokenRequestBody],
        FieldMetadata(
            request=RequestMetadata(media_type="application/x-www-form-urlencoded")
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["X-Publishable-Key", "RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
