"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address import OneDot0Dot1Address, OneDot0Dot1AddressTypedDict
from .onedot_0dot_1_cart_shipment_type import OneDot0Dot1CartShipmentType
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CartShipmentTypedDict(TypedDict):
    r"""A cart that is being prepared for shipment"""

    carrier: NotRequired[str]
    r"""The name of the carrier selected."""
    cost: NotRequired[int]
    r"""The cost in cents."""
    discounted_by_membership: NotRequired[bool]
    r"""Defines if shopper has a membership discount."""
    estimated_delivery_date: NotRequired[str]
    r"""The estimated delivery date."""
    expedited: NotRequired[bool]
    r"""True if shipment is expedited."""
    package_depth: NotRequired[int]
    r"""The depth."""
    package_dimension_unit: NotRequired[str]
    r"""The unit of measurement for an item's dimensions."""
    package_height: NotRequired[int]
    r"""The height."""
    package_type: NotRequired[str]
    r"""The type of package."""
    package_weight_unit: NotRequired[str]
    r"""The unit of measurement for an item's weight."""
    package_width: NotRequired[int]
    r"""The width."""
    service: NotRequired[str]
    r"""The service name."""
    shipping_address: NotRequired[OneDot0Dot1AddressTypedDict]
    r"""The Address object is used for billing, shipping, and physical store address use cases."""
    shipping_address_id: NotRequired[str]
    r"""ID for billing address"""
    shipping_method: NotRequired[str]
    r"""The name of the shipping method."""
    signature: NotRequired[str]
    r"""The signature."""
    tax_amount: NotRequired[int]
    r"""Tax amount in cents."""
    tax_code: NotRequired[str]
    r"""The relevant tax code."""
    total_weight: NotRequired[int]
    r"""The total weight."""
    total_weight_unit: NotRequired[str]
    r"""The unit of measurement for an item's weight."""
    type: NotRequired[OneDot0Dot1CartShipmentType]
    r"""The type corresponding to this shipment, if applicable."""


class OneDot0Dot1CartShipment(BaseModel):
    r"""A cart that is being prepared for shipment"""

    carrier: Optional[str] = None
    r"""The name of the carrier selected."""

    cost: Optional[int] = None
    r"""The cost in cents."""

    discounted_by_membership: Optional[bool] = None
    r"""Defines if shopper has a membership discount."""

    estimated_delivery_date: Optional[str] = None
    r"""The estimated delivery date."""

    expedited: Optional[bool] = None
    r"""True if shipment is expedited."""

    package_depth: Optional[int] = None
    r"""The depth."""

    package_dimension_unit: Optional[str] = None
    r"""The unit of measurement for an item's dimensions."""

    package_height: Optional[int] = None
    r"""The height."""

    package_type: Optional[str] = None
    r"""The type of package."""

    package_weight_unit: Optional[str] = None
    r"""The unit of measurement for an item's weight."""

    package_width: Optional[int] = None
    r"""The width."""

    service: Optional[str] = None
    r"""The service name."""

    shipping_address: Optional[OneDot0Dot1Address] = None
    r"""The Address object is used for billing, shipping, and physical store address use cases."""

    shipping_address_id: Optional[str] = None
    r"""ID for billing address"""

    shipping_method: Optional[str] = None
    r"""The name of the shipping method."""

    signature: Optional[str] = None
    r"""The signature."""

    tax_amount: Optional[int] = None
    r"""Tax amount in cents."""

    tax_code: Optional[str] = None
    r"""The relevant tax code."""

    total_weight: Optional[int] = None
    r"""The total weight."""

    total_weight_unit: Optional[str] = None
    r"""The unit of measurement for an item's weight."""

    type: Optional[OneDot0Dot1CartShipmentType] = None
    r"""The type corresponding to this shipment, if applicable."""
