"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class OneDot0Dot1OrderTrackResponseTypedDict(TypedDict):
    r"""Order Tracking Successful"""


class OneDot0Dot1OrderTrackResponse(BaseModel):
    r"""Order Tracking Successful"""
