"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address_view import (
    OneDot0Dot1AddressView,
    OneDot0Dot1AddressViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1AddressChangeViewTypedDict(TypedDict):
    from_address: NotRequired[OneDot0Dot1AddressViewTypedDict]
    r"""The address object returned in the response."""
    status: NotRequired[str]
    ticket_id: NotRequired[str]
    timestamp: NotRequired[float]
    to_address: NotRequired[OneDot0Dot1AddressViewTypedDict]
    r"""The address object returned in the response."""


class OneDot0Dot1AddressChangeView(BaseModel):
    from_address: Optional[OneDot0Dot1AddressView] = None
    r"""The address object returned in the response."""

    status: Optional[str] = None

    ticket_id: Optional[str] = None

    timestamp: Optional[float] = None

    to_address: Optional[OneDot0Dot1AddressView] = None
    r"""The address object returned in the response."""
