"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OneDot0Dot1CustomFieldViewCheckoutStep(str, Enum):
    SHIPPING_STEP = "SHIPPING_STEP"
    DELIVERY_STEP = "DELIVERY_STEP"
    PAYMENT_STEP = "PAYMENT_STEP"
    ACCOUNT_REGISTRATION_SSO = "ACCOUNT_REGISTRATION_SSO"


class OneDot0Dot1CustomFieldViewContext(str, Enum):
    CHECKOUT = "CHECKOUT"
    SSO = "SSO"


class OneDot0Dot1CustomFieldViewTypedDict(TypedDict):
    checkout_step: NotRequired[OneDot0Dot1CustomFieldViewCheckoutStep]
    dynamic: NotRequired[bool]
    context: NotRequired[OneDot0Dot1CustomFieldViewContext]
    external_id: NotRequired[str]
    field_setup: NotRequired[str]
    label: NotRequired[str]
    position: NotRequired[float]
    public_id: NotRequired[str]
    required: NotRequired[bool]
    subscribe_to_newsletter: NotRequired[bool]


class OneDot0Dot1CustomFieldView(BaseModel):
    checkout_step: Optional[OneDot0Dot1CustomFieldViewCheckoutStep] = None

    dynamic: Optional[bool] = None

    context: Optional[OneDot0Dot1CustomFieldViewContext] = None

    external_id: Optional[str] = None

    field_setup: Optional[str] = None

    label: Optional[str] = None

    position: Optional[float] = None

    public_id: Optional[str] = None

    required: Optional[bool] = None

    subscribe_to_newsletter: Annotated[
        Optional[bool], pydantic.Field(alias="subscribeToNewsletter")
    ] = None
