"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1IDescriptionPartTypedDict(TypedDict):
    content: NotRequired[str]
    is_html: NotRequired[bool]


class OneDot0Dot1IDescriptionPart(BaseModel):
    content: Optional[str] = None

    is_html: Optional[bool] = None
