"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address import OneDot0Dot1Address, OneDot0Dot1AddressTypedDict
from .onedot_0dot_1_cart_add_on import (
    OneDot0Dot1CartAddOn,
    OneDot0Dot1CartAddOnTypedDict,
)
from .onedot_0dot_1_cart_discount import (
    OneDot0Dot1CartDiscount,
    OneDot0Dot1CartDiscountTypedDict,
)
from .onedot_0dot_1_cart_fee import OneDot0Dot1CartFee, OneDot0Dot1CartFeeTypedDict
from .onedot_0dot_1_cart_item import OneDot0Dot1CartItem, OneDot0Dot1CartItemTypedDict
from .onedot_0dot_1_cart_loyalty_rewards import (
    OneDot0Dot1CartLoyaltyRewards,
    OneDot0Dot1CartLoyaltyRewardsTypedDict,
)
from .onedot_0dot_1_cart_shipment import (
    OneDot0Dot1CartShipment,
    OneDot0Dot1CartShipmentTypedDict,
)
from .onedot_0dot_1_fulfillment import (
    OneDot0Dot1Fulfillment,
    OneDot0Dot1FulfillmentTypedDict,
)
from .onedot_0dot_1_in_store_cart_shipment import (
    OneDot0Dot1InStoreCartShipment,
    OneDot0Dot1InStoreCartShipmentTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CartCreateTypedDict(TypedDict):
    r"""The cart_create object is a composite of the base_cart object and additional order details."""

    total_amount: float
    r"""The total amount, in cents, of the cart including its items and taxes (if applicable), e.g. $9.00 is 900. This total must match the sum of all other amounts."""
    currency: str
    order_reference: str
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""
    add_ons: NotRequired[List[OneDot0Dot1CartAddOnTypedDict]]
    billing_address: NotRequired[OneDot0Dot1AddressTypedDict]
    r"""The Address object is used for billing, shipping, and physical store address use cases."""
    discounts: NotRequired[List[OneDot0Dot1CartDiscountTypedDict]]
    fees: NotRequired[List[OneDot0Dot1CartFeeTypedDict]]
    fulfillments: NotRequired[List[OneDot0Dot1FulfillmentTypedDict]]
    in_store_cart_shipments: NotRequired[List[OneDot0Dot1InStoreCartShipmentTypedDict]]
    items: NotRequired[List[OneDot0Dot1CartItemTypedDict]]
    r"""The list of items associated with the cart."""
    loyalty_rewards: NotRequired[List[OneDot0Dot1CartLoyaltyRewardsTypedDict]]
    shipments: NotRequired[List[OneDot0Dot1CartShipmentTypedDict]]
    tax_amount: NotRequired[float]
    r"""The total tax amount for all of the items associated with the cart."""
    cart_url: NotRequired[str]
    r"""Used to provide a link to the cart ID."""
    display_id: NotRequired[str]
    r"""This field, although required, can be an empty string."""
    metadata: NotRequired[Dict[str, str]]
    r"""Optional custom metadata."""
    order_description: NotRequired[str]
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""


class OneDot0Dot1CartCreate(BaseModel):
    r"""The cart_create object is a composite of the base_cart object and additional order details."""

    total_amount: float
    r"""The total amount, in cents, of the cart including its items and taxes (if applicable), e.g. $9.00 is 900. This total must match the sum of all other amounts."""

    currency: str

    order_reference: str
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""

    add_ons: Optional[List[OneDot0Dot1CartAddOn]] = None

    billing_address: Optional[OneDot0Dot1Address] = None
    r"""The Address object is used for billing, shipping, and physical store address use cases."""

    discounts: Optional[List[OneDot0Dot1CartDiscount]] = None

    fees: Optional[List[OneDot0Dot1CartFee]] = None

    fulfillments: Optional[List[OneDot0Dot1Fulfillment]] = None

    in_store_cart_shipments: Optional[List[OneDot0Dot1InStoreCartShipment]] = None

    items: Optional[List[OneDot0Dot1CartItem]] = None
    r"""The list of items associated with the cart."""

    loyalty_rewards: Optional[List[OneDot0Dot1CartLoyaltyRewards]] = None

    shipments: Optional[List[OneDot0Dot1CartShipment]] = None

    tax_amount: Optional[float] = None
    r"""The total tax amount for all of the items associated with the cart."""

    cart_url: Optional[str] = None
    r"""Used to provide a link to the cart ID."""

    display_id: Optional[str] = None
    r"""This field, although required, can be an empty string."""

    metadata: Optional[Dict[str, str]] = None
    r"""Optional custom metadata."""

    order_description: Optional[str] = None
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""
