"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address_view import (
    OneDot0Dot1AddressView,
    OneDot0Dot1AddressViewTypedDict,
)
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_gift_option_view import (
    OneDot0Dot1GiftOptionView,
    OneDot0Dot1GiftOptionViewTypedDict,
)
from .onedot_0dot_1_i_description_part import (
    OneDot0Dot1IDescriptionPart,
    OneDot0Dot1IDescriptionPartTypedDict,
)
from .onedot_0dot_1_i_description_tooltip import (
    OneDot0Dot1IDescriptionTooltip,
    OneDot0Dot1IDescriptionTooltipTypedDict,
)
from .onedot_0dot_1_i_weight import OneDot0Dot1IWeight, OneDot0Dot1IWeightTypedDict
from bolt_api_sdk.types import BaseModel
from datetime import datetime
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PackageDimensionTypedDict(TypedDict):
    depth: NotRequired[float]
    height: NotRequired[float]
    unit: NotRequired[str]
    width: NotRequired[float]


class PackageDimension(BaseModel):
    depth: Optional[float] = None

    height: Optional[float] = None

    unit: Optional[str] = None

    width: Optional[float] = None


class OneDot0Dot1ICartShipmentViewTypedDict(TypedDict):
    carrier: NotRequired[str]
    r"""The carrier used to deliver the shipment."""
    cost: NotRequired[OneDot0Dot1AmountViewTypedDict]
    default: NotRequired[bool]
    description: NotRequired[List[OneDot0Dot1IDescriptionPartTypedDict]]
    description_tooltips: NotRequired[List[OneDot0Dot1IDescriptionTooltipTypedDict]]
    estimated_delivery_date: NotRequired[datetime]
    expedited: NotRequired[bool]
    r"""Used to determine whether a shipment has been expedited or not."""
    gift_options: NotRequired[OneDot0Dot1GiftOptionViewTypedDict]
    r"""Defines which gift options are hidden."""
    id: NotRequired[str]
    package_dimension: NotRequired[PackageDimensionTypedDict]
    package_type: NotRequired[str]
    package_weight: NotRequired[OneDot0Dot1IWeightTypedDict]
    reference: NotRequired[str]
    service: NotRequired[str]
    shipping_address: NotRequired[OneDot0Dot1AddressViewTypedDict]
    r"""The address object returned in the response."""
    shipping_method: NotRequired[str]
    signature: NotRequired[str]
    tax_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    total_weight: NotRequired[OneDot0Dot1IWeightTypedDict]
    type: NotRequired[str]


class OneDot0Dot1ICartShipmentView(BaseModel):
    carrier: Optional[str] = None
    r"""The carrier used to deliver the shipment."""

    cost: Optional[OneDot0Dot1AmountView] = None

    default: Optional[bool] = None

    description: Optional[List[OneDot0Dot1IDescriptionPart]] = None

    description_tooltips: Optional[List[OneDot0Dot1IDescriptionTooltip]] = None

    estimated_delivery_date: Optional[datetime] = None

    expedited: Optional[bool] = None
    r"""Used to determine whether a shipment has been expedited or not."""

    gift_options: Optional[OneDot0Dot1GiftOptionView] = None
    r"""Defines which gift options are hidden."""

    id: Optional[str] = None

    package_dimension: Optional[PackageDimension] = None

    package_type: Optional[str] = None

    package_weight: Optional[OneDot0Dot1IWeight] = None

    reference: Optional[str] = None

    service: Optional[str] = None

    shipping_address: Optional[OneDot0Dot1AddressView] = None
    r"""The address object returned in the response."""

    shipping_method: Optional[str] = None

    signature: Optional[str] = None

    tax_amount: Optional[OneDot0Dot1AmountView] = None

    total_weight: Optional[OneDot0Dot1IWeight] = None

    type: Optional[str] = None
