"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1TransactionSplitsViewType(str, Enum):
    NET = "net"
    PROCESSING_FEE = "processing_fee"
    FLOAT = "float"
    RESERVE = "reserve"
    ADJUSTMENT = "adjustment"
    BOLT_FEE = "bolt_fee"


class OneDot0Dot1TransactionSplitsViewTypedDict(TypedDict):
    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    type: NotRequired[OneDot0Dot1TransactionSplitsViewType]


class OneDot0Dot1TransactionSplitsView(BaseModel):
    amount: Optional[OneDot0Dot1AmountView] = None

    type: Optional[OneDot0Dot1TransactionSplitsViewType] = None
