"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1DigitalDeliveryTypedDict(TypedDict):
    email: NotRequired[str]
    phone: NotRequired[str]


class OneDot0Dot1DigitalDelivery(BaseModel):
    email: Optional[str] = None

    phone: Optional[str] = None
