"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_merchant_callback_url_type import OneDot0Dot1MerchantCallbackURLType
from bolt_api_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class OneDot0Dot1MerchantCallbacksInputCallbackURLTypedDict(TypedDict):
    type: OneDot0Dot1MerchantCallbackURLType
    r"""Bolt merchant division callback URL type"""
    url: str
    r"""The full callback URL."""


class OneDot0Dot1MerchantCallbacksInputCallbackURL(BaseModel):
    type: OneDot0Dot1MerchantCallbackURLType
    r"""Bolt merchant division callback URL type"""

    url: str
    r"""The full callback URL."""


class OneDot0Dot1MerchantCallbacksInputTypedDict(TypedDict):
    callback_urls: List[OneDot0Dot1MerchantCallbacksInputCallbackURLTypedDict]
    r"""List of callback URLs to configure"""
    division_id: str
    r"""The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). Use the Bolt Merchant Dashboard to switch between divisions and find the division ID under `Merchant Division Public ID`."""


class OneDot0Dot1MerchantCallbacksInput(BaseModel):
    callback_urls: List[OneDot0Dot1MerchantCallbacksInputCallbackURL]
    r"""List of callback URLs to configure"""

    division_id: str
    r"""The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). Use the Bolt Merchant Dashboard to switch between divisions and find the division ID under `Merchant Division Public ID`."""
