"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_i_cart_view import (
    OneDot0Dot1ICartView,
    OneDot0Dot1ICartViewTypedDict,
)
from .onedot_0dot_1_i_order_dynamic_content import (
    OneDot0Dot1IOrderDynamicContent,
    OneDot0Dot1IOrderDynamicContentTypedDict,
)
from .onedot_0dot_1_i_order_external_data import (
    OneDot0Dot1IOrderExternalData,
    OneDot0Dot1IOrderExternalDataTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1IOrderViewTypedDict(TypedDict):
    cart: NotRequired[OneDot0Dot1ICartViewTypedDict]
    r"""This is the cart object returned in a successful response."""
    dynamic_content: NotRequired[OneDot0Dot1IOrderDynamicContentTypedDict]
    external_data: NotRequired[OneDot0Dot1IOrderExternalDataTypedDict]
    token: NotRequired[str]
    user_note: NotRequired[str]
    r"""Used by shoppers to make extra requests or provide details for gift messages."""


class OneDot0Dot1IOrderView(BaseModel):
    cart: Optional[OneDot0Dot1ICartView] = None
    r"""This is the cart object returned in a successful response."""

    dynamic_content: Optional[OneDot0Dot1IOrderDynamicContent] = None

    external_data: Optional[OneDot0Dot1IOrderExternalData] = None

    token: Optional[str] = None

    user_note: Optional[str] = None
    r"""Used by shoppers to make extra requests or provide details for gift messages."""
