"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_merchant_onboarding_status_code import (
    OneDot0Dot1MerchantOnboardingStatusCode,
)
from .onedot_0dot_1_merchant_status import OneDot0Dot1MerchantStatus
from .onedot_0dot_1_transaction_operational_processor import (
    OneDot0Dot1TransactionOperationalProcessor,
    OneDot0Dot1TransactionOperationalProcessorTypedDict,
)
from .onedot_0dot_1_transaction_processor import OneDot0Dot1TransactionProcessor
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1MerchantTypedDict(TypedDict):
    created_at: int
    r"""The date the merchant account was created.  **Nullable** for Transactions Details."""
    description: str
    r"""The description of the merchant account. **Nullable** for Transactions Details."""
    operational_processors: List[OneDot0Dot1TransactionOperationalProcessorTypedDict]
    r"""**Nullable** for Transactions Details.

    """
    processor: OneDot0Dot1TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""
    time_zone: str
    r"""The timezone of the merchant. **Nullable** for Transactions Details."""
    onboarding_status: NotRequired[OneDot0Dot1MerchantOnboardingStatusCode]
    public_id: NotRequired[str]
    r"""The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions."""
    status: NotRequired[OneDot0Dot1MerchantStatus]
    r"""The merchant's status:
    * `1` - Active
    * `2` - Inactive
    * `3` - Offboarding

    """


class OneDot0Dot1Merchant(BaseModel):
    created_at: int
    r"""The date the merchant account was created.  **Nullable** for Transactions Details."""

    description: str
    r"""The description of the merchant account. **Nullable** for Transactions Details."""

    operational_processors: List[OneDot0Dot1TransactionOperationalProcessor]
    r"""**Nullable** for Transactions Details.

    """

    processor: OneDot0Dot1TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""

    time_zone: str
    r"""The timezone of the merchant. **Nullable** for Transactions Details."""

    onboarding_status: Optional[OneDot0Dot1MerchantOnboardingStatusCode] = None

    public_id: Optional[str] = None
    r"""The unique public ID for the merchant's Bolt account. A merchant account contains many merchant divisions."""

    status: Optional[OneDot0Dot1MerchantStatus] = None
    r"""The merchant's status:
    * `1` - Active
    * `2` - Inactive
    * `3` - Offboarding

    """
