"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_transaction_processor import OneDot0Dot1TransactionProcessor
from .onedot_0dot_1_transaction_processor_status import (
    OneDot0Dot1TransactionProcessorStatus,
)
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class OneDot0Dot1TransactionOperationalProcessorTypedDict(TypedDict):
    processor: OneDot0Dot1TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""
    status: OneDot0Dot1TransactionProcessorStatus
    r"""The processor's status. Only `primary` and `active` processor are displayed."""


class OneDot0Dot1TransactionOperationalProcessor(BaseModel):
    processor: OneDot0Dot1TransactionProcessor
    r"""The processor used. **Nullable** for Transactions Details."""

    status: OneDot0Dot1TransactionProcessorStatus
    r"""The processor's status. Only `primary` and `active` processor are displayed."""
