"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_cart_item import OneDot0Dot1CartItem, OneDot0Dot1CartItemTypedDict
from .onedot_0dot_1_cart_shipment import (
    OneDot0Dot1CartShipment,
    OneDot0Dot1CartShipmentTypedDict,
)
from .onedot_0dot_1_digital_delivery import (
    OneDot0Dot1DigitalDelivery,
    OneDot0Dot1DigitalDeliveryTypedDict,
)
from .onedot_0dot_1_in_store_cart_shipment import (
    OneDot0Dot1InStoreCartShipment,
    OneDot0Dot1InStoreCartShipmentTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1FulfillmentType(str, Enum):
    PHYSICAL_DOOR_DELIVERY = "physical_door_delivery"
    PHYSICAL_SHIP_TO_STORE = "physical_ship_to_store"
    PHYSICAL_IN_STORE_PICKUP = "physical_in_store_pickup"
    DIGITAL_DOWNLOAD = "digital_download"
    DIGITAL_NO_DELIVERY = "digital_no_delivery"


class OneDot0Dot1FulfillmentTypedDict(TypedDict):
    r"""Defines the shipments associated with the cart items."""

    cart_items: NotRequired[List[OneDot0Dot1CartItemTypedDict]]
    cart_shipment: NotRequired[OneDot0Dot1CartShipmentTypedDict]
    r"""A cart that is being prepared for shipment"""
    digital_delivery: NotRequired[OneDot0Dot1DigitalDeliveryTypedDict]
    in_store_cart_shipment: NotRequired[OneDot0Dot1InStoreCartShipmentTypedDict]
    type: NotRequired[OneDot0Dot1FulfillmentType]


class OneDot0Dot1Fulfillment(BaseModel):
    r"""Defines the shipments associated with the cart items."""

    cart_items: Optional[List[OneDot0Dot1CartItem]] = None

    cart_shipment: Optional[OneDot0Dot1CartShipment] = None
    r"""A cart that is being prepared for shipment"""

    digital_delivery: Optional[OneDot0Dot1DigitalDelivery] = None

    in_store_cart_shipment: Optional[OneDot0Dot1InStoreCartShipment] = None

    type: Optional[OneDot0Dot1FulfillmentType] = None
