"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1IGiftOptionViewTypedDict(TypedDict):
    hide_gift_message: NotRequired[bool]
    hide_gift_wrap: NotRequired[bool]


class OneDot0Dot1IGiftOptionView(BaseModel):
    hide_gift_message: Optional[bool] = None

    hide_gift_wrap: Optional[bool] = None
