"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_capture_view import (
    OneDot0Dot1CaptureView,
    OneDot0Dot1CaptureViewTypedDict,
)
from .onedot_0dot_1_consumer_self_view import (
    OneDot0Dot1ConsumerSelfView,
    OneDot0Dot1ConsumerSelfViewTypedDict,
)
from .onedot_0dot_1_credit_card_authorization_view import (
    OneDot0Dot1CreditCardAuthorizationView,
    OneDot0Dot1CreditCardAuthorizationViewTypedDict,
)
from .onedot_0dot_1_credit_card_capture_view import (
    OneDot0Dot1CreditCardCaptureView,
    OneDot0Dot1CreditCardCaptureViewTypedDict,
)
from .onedot_0dot_1_credit_card_credit_view import (
    OneDot0Dot1CreditCardCreditView,
    OneDot0Dot1CreditCardCreditViewTypedDict,
)
from .onedot_0dot_1_credit_card_view import (
    OneDot0Dot1CreditCardView,
    OneDot0Dot1CreditCardViewTypedDict,
)
from .onedot_0dot_1_credit_card_void_view import (
    OneDot0Dot1CreditCardVoidView,
    OneDot0Dot1CreditCardVoidViewTypedDict,
)
from .onedot_0dot_1_merchant_division_summary_view import (
    OneDot0Dot1MerchantDivisionSummaryView,
    OneDot0Dot1MerchantDivisionSummaryViewTypedDict,
)
from .onedot_0dot_1_order_decision_details_view import (
    OneDot0Dot1OrderDecisionDetailsView,
    OneDot0Dot1OrderDecisionDetailsViewTypedDict,
)
from .onedot_0dot_1_review_ticket_view import (
    OneDot0Dot1ReviewTicketView,
    OneDot0Dot1ReviewTicketViewTypedDict,
)
from .onedot_0dot_1_risk_model_external_result_view import (
    OneDot0Dot1RiskModelExternalResultView,
    OneDot0Dot1RiskModelExternalResultViewTypedDict,
)
from .onedot_0dot_1_risk_review_status import OneDot0Dot1RiskReviewStatus
from .onedot_0dot_1_transaction_indemnification_decision import (
    OneDot0Dot1TransactionIndemnificationDecision,
)
from .onedot_0dot_1_transaction_indemnification_reason import (
    OneDot0Dot1TransactionIndemnificationReason,
)
from .onedot_0dot_1_transaction_processor import OneDot0Dot1TransactionProcessor
from .onedot_0dot_1_transaction_splits_view import (
    OneDot0Dot1TransactionSplitsView,
    OneDot0Dot1TransactionSplitsViewTypedDict,
)
from .onedot_0dot_1_transaction_status import OneDot0Dot1TransactionStatus
from .onedot_0dot_1_transaction_type import OneDot0Dot1TransactionType
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OneDot0Dot1TransactionViewViewStatus(str, Enum):
    NOT_VIEWED = "not_viewed"
    VIEWED = "viewed"
    VIEWING = "viewing"


class OneDot0Dot1TransactionViewTypedDict(TypedDict):
    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    authorization: NotRequired[OneDot0Dot1CreditCardAuthorizationViewTypedDict]
    capture: NotRequired[OneDot0Dot1CaptureViewTypedDict]
    r"""Deprecated. Use `captures`."""
    captures: NotRequired[List[OneDot0Dot1CreditCardCaptureViewTypedDict]]
    credit: NotRequired[OneDot0Dot1CreditCardCreditViewTypedDict]
    date_: NotRequired[int]
    r"""Transaction date. **Nullable** for Transactions Details."""
    from_consumer: NotRequired[OneDot0Dot1ConsumerSelfViewTypedDict]
    from_credit_card: NotRequired[OneDot0Dot1CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    id: NotRequired[str]
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""
    indemnification_decision: NotRequired[OneDot0Dot1TransactionIndemnificationDecision]
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """
    indemnification_reason: NotRequired[OneDot0Dot1TransactionIndemnificationReason]
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """
    last4: NotRequired[str]
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""
    last_viewed_utc: NotRequired[float]
    merchant_division: NotRequired[OneDot0Dot1MerchantDivisionSummaryViewTypedDict]
    merchant_order_number: NotRequired[str]
    order_decision: NotRequired[OneDot0Dot1OrderDecisionDetailsViewTypedDict]
    processor: NotRequired[OneDot0Dot1TransactionProcessor]
    r"""The processor used. **Nullable** for Transactions Details."""
    reference: NotRequired[str]
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""
    review_ticket: NotRequired[OneDot0Dot1ReviewTicketViewTypedDict]
    risk_insights: NotRequired[OneDot0Dot1RiskModelExternalResultViewTypedDict]
    risk_review_status: NotRequired[OneDot0Dot1RiskReviewStatus]
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""
    risk_score: NotRequired[int]
    splits: NotRequired[List[OneDot0Dot1TransactionSplitsViewTypedDict]]
    status: NotRequired[OneDot0Dot1TransactionStatus]
    r"""The transaction's status."""
    to_consumer: NotRequired[OneDot0Dot1ConsumerSelfViewTypedDict]
    to_credit_card: NotRequired[OneDot0Dot1CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    transaction_properties: NotRequired[Dict[str, str]]
    type: NotRequired[OneDot0Dot1TransactionType]
    r"""The type of transaction."""
    void: NotRequired[OneDot0Dot1CreditCardVoidViewTypedDict]
    view_status: NotRequired[OneDot0Dot1TransactionViewViewStatus]


class OneDot0Dot1TransactionView(BaseModel):
    amount: Optional[OneDot0Dot1AmountView] = None

    authorization: Optional[OneDot0Dot1CreditCardAuthorizationView] = None

    capture: Optional[OneDot0Dot1CaptureView] = None
    r"""Deprecated. Use `captures`."""

    captures: Optional[List[OneDot0Dot1CreditCardCaptureView]] = None

    credit: Optional[OneDot0Dot1CreditCardCreditView] = None

    date_: Annotated[Optional[int], pydantic.Field(alias="date")] = None
    r"""Transaction date. **Nullable** for Transactions Details."""

    from_consumer: Optional[OneDot0Dot1ConsumerSelfView] = None

    from_credit_card: Optional[OneDot0Dot1CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    id: Optional[str] = None
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""

    indemnification_decision: Optional[
        OneDot0Dot1TransactionIndemnificationDecision
    ] = None
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """

    indemnification_reason: Optional[OneDot0Dot1TransactionIndemnificationReason] = None
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """

    last4: Optional[str] = None
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""

    last_viewed_utc: Optional[float] = None

    merchant_division: Optional[OneDot0Dot1MerchantDivisionSummaryView] = None

    merchant_order_number: Optional[str] = None

    order_decision: Optional[OneDot0Dot1OrderDecisionDetailsView] = None

    processor: Optional[OneDot0Dot1TransactionProcessor] = None
    r"""The processor used. **Nullable** for Transactions Details."""

    reference: Optional[str] = None
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""

    review_ticket: Optional[OneDot0Dot1ReviewTicketView] = None

    risk_insights: Optional[OneDot0Dot1RiskModelExternalResultView] = None

    risk_review_status: Optional[OneDot0Dot1RiskReviewStatus] = None
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""

    risk_score: Optional[int] = None

    splits: Optional[List[OneDot0Dot1TransactionSplitsView]] = None

    status: Optional[OneDot0Dot1TransactionStatus] = None
    r"""The transaction's status."""

    to_consumer: Optional[OneDot0Dot1ConsumerSelfView] = None

    to_credit_card: Optional[OneDot0Dot1CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    transaction_properties: Optional[Dict[str, str]] = None

    type: Optional[OneDot0Dot1TransactionType] = None
    r"""The type of transaction."""

    void: Optional[OneDot0Dot1CreditCardVoidView] = None

    view_status: Optional[OneDot0Dot1TransactionViewViewStatus] = None
