"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_custom_field_response_view import (
    OneDot0Dot1CustomFieldResponseView,
    OneDot0Dot1CustomFieldResponseViewTypedDict,
)
from .onedot_0dot_1_custom_field_view import (
    OneDot0Dot1CustomFieldView,
    OneDot0Dot1CustomFieldViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CustomFieldFullResponseViewTypedDict(TypedDict):
    field: NotRequired[OneDot0Dot1CustomFieldViewTypedDict]
    response: NotRequired[OneDot0Dot1CustomFieldResponseViewTypedDict]


class OneDot0Dot1CustomFieldFullResponseView(BaseModel):
    field: Optional[OneDot0Dot1CustomFieldView] = None

    response: Optional[OneDot0Dot1CustomFieldResponseView] = None
