"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_webhooks_type import OneDot0Dot1WebhooksType
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1EventsArrayCreateWebhookTypedDict(TypedDict):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""
    url: str
    r"""The full URL to receive webhook notifications."""
    events: NotRequired[List[OneDot0Dot1WebhooksType]]
    r"""If `webhook_event_group` is null, pick a list of notification events to subscribe to.

    """


class OneDot0Dot1EventsArrayCreateWebhook(BaseModel):
    division_id: str
    r"""The unique ID associated with the specific merchant division."""

    url: str
    r"""The full URL to receive webhook notifications."""

    events: Optional[List[OneDot0Dot1WebhooksType]] = None
    r"""If `webhook_event_group` is null, pick a list of notification events to subscribe to.

    """
