"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_cart_item_customization import (
    OneDot0Dot1CartItemCustomization,
    OneDot0Dot1CartItemCustomizationTypedDict,
)
from .onedot_0dot_1_cart_item_property_view import (
    OneDot0Dot1CartItemPropertyView,
    OneDot0Dot1CartItemPropertyViewTypedDict,
)
from .onedot_0dot_1_gift_option_view import (
    OneDot0Dot1GiftOptionView,
    OneDot0Dot1GiftOptionViewTypedDict,
)
from .onedot_0dot_1_i_weight import OneDot0Dot1IWeight, OneDot0Dot1IWeightTypedDict
from .onedot_0dot_1_subscription import (
    OneDot0Dot1Subscription,
    OneDot0Dot1SubscriptionTypedDict,
)
from bolt_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1ICartItemViewShipmentType(str, Enum):
    UNKNOWN = "unknown"
    DOOR_DELIVERY = "door_delivery"
    SHIP_TO_STORE = "ship_to_store"
    IN_STORE_PICKUP = "in_store_pickup"
    SHIP_TO_HOME_ONLY = "ship_to_home_only"


class OneDot0Dot1ICartItemViewType(str, Enum):
    UNKNOWN = "unknown"
    DIGITAL = "digital"
    PHYSICAL = "physical"
    BUNDLED = "bundled"


class OneDot0Dot1ICartItemViewTypedDict(TypedDict):
    bolt_product_id: NotRequired[str]
    brand: NotRequired[str]
    category: NotRequired[Nullable[str]]
    r"""Used to define a product category associated with the item."""
    collections: NotRequired[List[str]]
    color: NotRequired[str]
    r"""Used to define the color of the item."""
    customizations: NotRequired[List[OneDot0Dot1CartItemCustomizationTypedDict]]
    description: NotRequired[str]
    details_url: NotRequired[str]
    r"""Used to provide a link to the item's product page."""
    gift_option: NotRequired[OneDot0Dot1GiftOptionViewTypedDict]
    r"""Defines which gift options are hidden."""
    hide: NotRequired[bool]
    image_url: NotRequired[str]
    r"""Used to provide a link to the image associated with the item."""
    isbn: NotRequired[Nullable[str]]
    r"""Used to define the International Standard Book Number associated with the book."""
    item_group: NotRequired[str]
    manufacturer: NotRequired[Nullable[str]]
    r"""Used to define the organization that manufactured the item."""
    merchant_product_id: NotRequired[str]
    merchant_variant_id: NotRequired[str]
    msrp: NotRequired[OneDot0Dot1AmountViewTypedDict]
    name: NotRequired[str]
    options: NotRequired[str]
    properties: NotRequired[List[OneDot0Dot1CartItemPropertyViewTypedDict]]
    quantity: NotRequired[float]
    reference: NotRequired[str]
    shipment_id: NotRequired[str]
    shipment_type: NotRequired[OneDot0Dot1ICartItemViewShipmentType]
    shopify_line_item_reference: NotRequired[float]
    shopify_product_reference: NotRequired[float]
    shopify_product_variant_reference: NotRequired[float]
    size: NotRequired[str]
    r"""Used to define the size of the item."""
    sku: NotRequired[Nullable[str]]
    r"""Used to define an alpha-numeric Stock Keeping Unit associated with the item as it is mapped to your internal product catalogue."""
    subscription: NotRequired[OneDot0Dot1SubscriptionTypedDict]
    r"""Describes a product added as a recurring subscription."""
    tags: NotRequired[str]
    r"""Used to define a comma-separated list of tags associated with the item."""
    tax_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    taxable: NotRequired[bool]
    total_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    type: NotRequired[OneDot0Dot1ICartItemViewType]
    unit_price: NotRequired[OneDot0Dot1AmountViewTypedDict]
    uom: NotRequired[Nullable[str]]
    r"""Used to define the unit of measure used to describe the product."""
    upc: NotRequired[Nullable[str]]
    r"""Used to define the 12-digit Universal Product Code (a barcode) associated with the item worldwide."""
    weight: NotRequired[OneDot0Dot1IWeightTypedDict]


class OneDot0Dot1ICartItemView(BaseModel):
    bolt_product_id: Optional[str] = None

    brand: Optional[str] = None

    category: OptionalNullable[str] = UNSET
    r"""Used to define a product category associated with the item."""

    collections: Optional[List[str]] = None

    color: Optional[str] = None
    r"""Used to define the color of the item."""

    customizations: Optional[List[OneDot0Dot1CartItemCustomization]] = None

    description: Optional[str] = None

    details_url: Optional[str] = None
    r"""Used to provide a link to the item's product page."""

    gift_option: Optional[OneDot0Dot1GiftOptionView] = None
    r"""Defines which gift options are hidden."""

    hide: Optional[bool] = None

    image_url: Optional[str] = None
    r"""Used to provide a link to the image associated with the item."""

    isbn: OptionalNullable[str] = UNSET
    r"""Used to define the International Standard Book Number associated with the book."""

    item_group: Optional[str] = None

    manufacturer: OptionalNullable[str] = UNSET
    r"""Used to define the organization that manufactured the item."""

    merchant_product_id: Optional[str] = None

    merchant_variant_id: Optional[str] = None

    msrp: Optional[OneDot0Dot1AmountView] = None

    name: Optional[str] = None

    options: Optional[str] = None

    properties: Optional[List[OneDot0Dot1CartItemPropertyView]] = None

    quantity: Optional[float] = None

    reference: Optional[str] = None

    shipment_id: Optional[str] = None

    shipment_type: Optional[OneDot0Dot1ICartItemViewShipmentType] = None

    shopify_line_item_reference: Optional[float] = None

    shopify_product_reference: Optional[float] = None

    shopify_product_variant_reference: Optional[float] = None

    size: Optional[str] = None
    r"""Used to define the size of the item."""

    sku: OptionalNullable[str] = UNSET
    r"""Used to define an alpha-numeric Stock Keeping Unit associated with the item as it is mapped to your internal product catalogue."""

    subscription: Optional[OneDot0Dot1Subscription] = None
    r"""Describes a product added as a recurring subscription."""

    tags: Optional[str] = None
    r"""Used to define a comma-separated list of tags associated with the item."""

    tax_amount: Optional[OneDot0Dot1AmountView] = None

    taxable: Optional[bool] = None

    total_amount: Optional[OneDot0Dot1AmountView] = None

    type: Optional[OneDot0Dot1ICartItemViewType] = None

    unit_price: Optional[OneDot0Dot1AmountView] = None

    uom: OptionalNullable[str] = UNSET
    r"""Used to define the unit of measure used to describe the product."""

    upc: OptionalNullable[str] = UNSET
    r"""Used to define the 12-digit Universal Product Code (a barcode) associated with the item worldwide."""

    weight: Optional[OneDot0Dot1IWeight] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "bolt_product_id",
            "brand",
            "category",
            "collections",
            "color",
            "customizations",
            "description",
            "details_url",
            "gift_option",
            "hide",
            "image_url",
            "isbn",
            "item_group",
            "manufacturer",
            "merchant_product_id",
            "merchant_variant_id",
            "msrp",
            "name",
            "options",
            "properties",
            "quantity",
            "reference",
            "shipment_id",
            "shipment_type",
            "shopify_line_item_reference",
            "shopify_product_reference",
            "shopify_product_variant_reference",
            "size",
            "sku",
            "subscription",
            "tags",
            "tax_amount",
            "taxable",
            "total_amount",
            "type",
            "unit_price",
            "uom",
            "upc",
            "weight",
        ]
        nullable_fields = ["category", "isbn", "manufacturer", "sku", "uom", "upc"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
