"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_phone_priority import OneDot0Dot1PhonePriority
from .onedot_0dot_1_phone_status import OneDot0Dot1PhoneStatus
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1PhonesWithCountryCodeTypedDict(TypedDict):
    r"""A phone number with country code."""

    country_code: NotRequired[str]
    r"""A phone number's country code."""
    id: NotRequired[str]
    r"""This is the ID for the phone number associated with the shopper."""
    number: NotRequired[str]
    r"""A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign."""
    priority: NotRequired[OneDot0Dot1PhonePriority]
    r"""This is the priority of the contact method. This field's contents are not displayed in the transaction details view."""
    status: NotRequired[OneDot0Dot1PhoneStatus]
    r"""This is the status of the contact method."""


class OneDot0Dot1PhonesWithCountryCode(BaseModel):
    r"""A phone number with country code."""

    country_code: Optional[str] = None
    r"""A phone number's country code."""

    id: Optional[str] = None
    r"""This is the ID for the phone number associated with the shopper."""

    number: Optional[str] = None
    r"""A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign."""

    priority: Optional[OneDot0Dot1PhonePriority] = None
    r"""This is the priority of the contact method. This field's contents are not displayed in the transaction details view."""

    status: Optional[OneDot0Dot1PhoneStatus] = None
    r"""This is the status of the contact method."""
