"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_credit_card_void_cause import OneDot0Dot1CreditCardVoidCause
from .onedot_0dot_1_credit_card_void_status import OneDot0Dot1CreditCardVoidStatus
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CreditCardVoidViewTypedDict(TypedDict):
    cause: NotRequired[OneDot0Dot1CreditCardVoidCause]
    r"""Specifies why this particular transaction is voided."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    status: NotRequired[OneDot0Dot1CreditCardVoidStatus]
    r"""The status of the void request."""
    void: NotRequired[str]
    r"""The void ID returned from the payment processor."""


class OneDot0Dot1CreditCardVoidView(BaseModel):
    cause: Optional[OneDot0Dot1CreditCardVoidCause] = None
    r"""Specifies why this particular transaction is voided."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    status: Optional[OneDot0Dot1CreditCardVoidStatus] = None
    r"""The status of the void request."""

    void: Optional[str] = None
    r"""The void ID returned from the payment processor."""
