"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1AuthRejectionDetailsTypedDict(TypedDict):
    reason_code: NotRequired[str]
    reason_description: NotRequired[str]


class OneDot0Dot1AuthRejectionDetails(BaseModel):
    reason_code: Optional[str] = None

    reason_description: Optional[str] = None
