"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_chargeback_event_view import (
    OneDot0Dot1ChargebackEventView,
    OneDot0Dot1ChargebackEventViewTypedDict,
)
from .onedot_0dot_1_chargeback_reason_code import OneDot0Dot1ChargebackReasonCode
from .onedot_0dot_1_chargeback_representment_result import (
    OneDot0Dot1ChargebackRepresentmentResult,
)
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1ChargebackDetailsTypedDict(TypedDict):
    amt_won: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_amt: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_fee: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_id: NotRequired[str]
    r"""The unique ID of the chargeback."""
    event_views: NotRequired[List[OneDot0Dot1ChargebackEventViewTypedDict]]
    net_amt: NotRequired[OneDot0Dot1AmountViewTypedDict]
    reason: NotRequired[str]
    r"""The reason for the chargeback."""
    reason_code: NotRequired[OneDot0Dot1ChargebackReasonCode]
    r"""Bolt's [standardized reason codes](https://help.bolt.com/merchants/references/policies/disputes/dispute-codes/)."""
    representment_reply_by_date: NotRequired[int]
    r"""The date of the chargeback."""
    representment_result: NotRequired[OneDot0Dot1ChargebackRepresentmentResult]
    r"""The result of the chargeback representment."""


class OneDot0Dot1ChargebackDetails(BaseModel):
    amt_won: Optional[OneDot0Dot1AmountView] = None

    chargeback_amt: Optional[OneDot0Dot1AmountView] = None

    chargeback_fee: Optional[OneDot0Dot1AmountView] = None

    chargeback_id: Optional[str] = None
    r"""The unique ID of the chargeback."""

    event_views: Optional[List[OneDot0Dot1ChargebackEventView]] = None

    net_amt: Optional[OneDot0Dot1AmountView] = None

    reason: Optional[str] = None
    r"""The reason for the chargeback."""

    reason_code: Optional[OneDot0Dot1ChargebackReasonCode] = None
    r"""Bolt's [standardized reason codes](https://help.bolt.com/merchants/references/policies/disputes/dispute-codes/)."""

    representment_reply_by_date: Optional[int] = None
    r"""The date of the chargeback."""

    representment_result: Optional[OneDot0Dot1ChargebackRepresentmentResult] = None
    r"""The result of the chargeback representment."""
