"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1MerchantDivisionLogoViewTypedDict(TypedDict):
    domain: NotRequired[str]
    resource: NotRequired[str]


class OneDot0Dot1MerchantDivisionLogoView(BaseModel):
    domain: Optional[str] = None

    resource: Optional[str] = None
