"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_marketplace_commission_fee import (
    OneDot0Dot1MarketplaceCommissionFee,
    OneDot0Dot1MarketplaceCommissionFeeTypedDict,
)
from .onedot_0dot_1_seller_split_amounts import (
    OneDot0Dot1SellerSplitAmounts,
    OneDot0Dot1SellerSplitAmountsTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class OneDot0Dot1SellerSplitTypedDict(TypedDict):
    r"""Defines a seller split configuration for marketplace orders, specifying which items and shipments belong to a seller and how amounts should be calculated and distributed."""

    seller_id: str
    r"""The unique identifier for the seller within the marketplace ecosystem."""
    amounts: OneDot0Dot1SellerSplitAmountsTypedDict
    r"""Defines the financial breakdown for a seller split, including subtotals, discounts, shipping, taxes, and the final gross amount."""
    marketplace_commission_fee: OneDot0Dot1MarketplaceCommissionFeeTypedDict
    r"""Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models."""


class OneDot0Dot1SellerSplit(BaseModel):
    r"""Defines a seller split configuration for marketplace orders, specifying which items and shipments belong to a seller and how amounts should be calculated and distributed."""

    seller_id: str
    r"""The unique identifier for the seller within the marketplace ecosystem."""

    amounts: OneDot0Dot1SellerSplitAmounts
    r"""Defines the financial breakdown for a seller split, including subtotals, discounts, shipping, taxes, and the final gross amount."""

    marketplace_commission_fee: OneDot0Dot1MarketplaceCommissionFee
    r"""Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models."""
