"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address_view import (
    OneDot0Dot1AddressView,
    OneDot0Dot1AddressViewTypedDict,
)
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_cart_loyalty_rewards_view import (
    OneDot0Dot1CartLoyaltyRewardsView,
    OneDot0Dot1CartLoyaltyRewardsViewTypedDict,
)
from .onedot_0dot_1_fulfillment_view import (
    OneDot0Dot1FulfillmentView,
    OneDot0Dot1FulfillmentViewTypedDict,
)
from .onedot_0dot_1_i_cart_discount_view import (
    OneDot0Dot1ICartDiscountView,
    OneDot0Dot1ICartDiscountViewTypedDict,
)
from .onedot_0dot_1_i_cart_item_view import (
    OneDot0Dot1ICartItemView,
    OneDot0Dot1ICartItemViewTypedDict,
)
from .onedot_0dot_1_i_cart_shipment_view import (
    OneDot0Dot1ICartShipmentView,
    OneDot0Dot1ICartShipmentViewTypedDict,
)
from .onedot_0dot_1_i_currency import (
    OneDot0Dot1ICurrency,
    OneDot0Dot1ICurrencyTypedDict,
)
from .onedot_0dot_1_in_store_shipment2 import (
    OneDot0Dot1InStoreShipment2,
    OneDot0Dot1InStoreShipment2TypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CartViewTypedDict(TypedDict):
    r"""This is the cart object returned in a successful response."""

    billing_address: NotRequired[OneDot0Dot1AddressViewTypedDict]
    r"""The address object returned in the response."""
    cart_url: NotRequired[str]
    r"""Used to provide a link to the cart ID."""
    currency: NotRequired[OneDot0Dot1ICurrencyTypedDict]
    discount_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    discounts: NotRequired[List[OneDot0Dot1ICartDiscountViewTypedDict]]
    display_id: NotRequired[str]
    fee_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    fees: NotRequired[List[OneDot0Dot1ICartItemViewTypedDict]]
    fulfillments: NotRequired[List[OneDot0Dot1FulfillmentViewTypedDict]]
    in_store_shipments: NotRequired[OneDot0Dot1InStoreShipment2TypedDict]
    r"""A cart that is being prepared for shipment"""
    items: NotRequired[List[OneDot0Dot1ICartItemViewTypedDict]]
    loyalty_rewards: NotRequired[List[OneDot0Dot1CartLoyaltyRewardsViewTypedDict]]
    loyalty_rewards_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    merchant_order_url: NotRequired[str]
    metadata: NotRequired[Dict[str, str]]
    msrp: NotRequired[OneDot0Dot1AmountViewTypedDict]
    order_description: NotRequired[str]
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""
    order_reference: NotRequired[str]
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""
    shipments: NotRequired[List[OneDot0Dot1ICartShipmentViewTypedDict]]
    shipping_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    subtotal_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    tax_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    total_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    transaction_reference: NotRequired[str]
    r"""The 12 digit reference ID associated to a given transaction webhook for an order."""


class OneDot0Dot1CartView(BaseModel):
    r"""This is the cart object returned in a successful response."""

    billing_address: Optional[OneDot0Dot1AddressView] = None
    r"""The address object returned in the response."""

    cart_url: Optional[str] = None
    r"""Used to provide a link to the cart ID."""

    currency: Optional[OneDot0Dot1ICurrency] = None

    discount_amount: Optional[OneDot0Dot1AmountView] = None

    discounts: Optional[List[OneDot0Dot1ICartDiscountView]] = None

    display_id: Optional[str] = None

    fee_amount: Optional[OneDot0Dot1AmountView] = None

    fees: Optional[List[OneDot0Dot1ICartItemView]] = None

    fulfillments: Optional[List[OneDot0Dot1FulfillmentView]] = None

    in_store_shipments: Optional[OneDot0Dot1InStoreShipment2] = None
    r"""A cart that is being prepared for shipment"""

    items: Optional[List[OneDot0Dot1ICartItemView]] = None

    loyalty_rewards: Optional[List[OneDot0Dot1CartLoyaltyRewardsView]] = None

    loyalty_rewards_amount: Optional[OneDot0Dot1AmountView] = None

    merchant_order_url: Optional[str] = None

    metadata: Optional[Dict[str, str]] = None

    msrp: Optional[OneDot0Dot1AmountView] = None

    order_description: Optional[str] = None
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""

    order_reference: Optional[str] = None
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""

    shipments: Optional[List[OneDot0Dot1ICartShipmentView]] = None

    shipping_amount: Optional[OneDot0Dot1AmountView] = None

    subtotal_amount: Optional[OneDot0Dot1AmountView] = None

    tax_amount: Optional[OneDot0Dot1AmountView] = None

    total_amount: Optional[OneDot0Dot1AmountView] = None

    transaction_reference: Optional[str] = None
    r"""The 12 digit reference ID associated to a given transaction webhook for an order."""
