"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_risk_decision_factor_yml import OneDot0Dot1RiskDecisionFactorYml
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1OrderDecisionTypedDict(TypedDict):
    r"""Decision and score for an order."""

    decision_factors: NotRequired[List[OneDot0Dot1RiskDecisionFactorYml]]
    r"""The top 5 factors of the fraud decision."""
    score: NotRequired[int]
    r"""The total fraud risk score of the order."""


class OneDot0Dot1OrderDecision(BaseModel):
    r"""Decision and score for an order."""

    decision_factors: Optional[List[OneDot0Dot1RiskDecisionFactorYml]] = None
    r"""The top 5 factors of the fraud decision."""

    score: Optional[int] = None
    r"""The total fraud risk score of the order."""
