"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address_change_request_metadata_view import (
    OneDot0Dot1AddressChangeRequestMetadataView,
    OneDot0Dot1AddressChangeRequestMetadataViewTypedDict,
)
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_auth_rejection_details_view import (
    OneDot0Dot1AuthRejectionDetailsView,
    OneDot0Dot1AuthRejectionDetailsViewTypedDict,
)
from .onedot_0dot_1_capture_view import (
    OneDot0Dot1CaptureView,
    OneDot0Dot1CaptureViewTypedDict,
)
from .onedot_0dot_1_chargeback_details_view import (
    OneDot0Dot1ChargebackDetailsView,
    OneDot0Dot1ChargebackDetailsViewTypedDict,
)
from .onedot_0dot_1_consumer_self_view import (
    OneDot0Dot1ConsumerSelfView,
    OneDot0Dot1ConsumerSelfViewTypedDict,
)
from .onedot_0dot_1_credit_card_authorization_view import (
    OneDot0Dot1CreditCardAuthorizationView,
    OneDot0Dot1CreditCardAuthorizationViewTypedDict,
)
from .onedot_0dot_1_credit_card_capture_view import (
    OneDot0Dot1CreditCardCaptureView,
    OneDot0Dot1CreditCardCaptureViewTypedDict,
)
from .onedot_0dot_1_credit_card_credit_view import (
    OneDot0Dot1CreditCardCreditView,
    OneDot0Dot1CreditCardCreditViewTypedDict,
)
from .onedot_0dot_1_credit_card_view import (
    OneDot0Dot1CreditCardView,
    OneDot0Dot1CreditCardViewTypedDict,
)
from .onedot_0dot_1_credit_card_void_view import (
    OneDot0Dot1CreditCardVoidView,
    OneDot0Dot1CreditCardVoidViewTypedDict,
)
from .onedot_0dot_1_custom_field_full_response_view import (
    OneDot0Dot1CustomFieldFullResponseView,
    OneDot0Dot1CustomFieldFullResponseViewTypedDict,
)
from .onedot_0dot_1_customer_list_status import (
    OneDot0Dot1CustomerListStatus,
    OneDot0Dot1CustomerListStatusTypedDict,
)
from .onedot_0dot_1_manual_dispute_view import (
    OneDot0Dot1ManualDisputeView,
    OneDot0Dot1ManualDisputeViewTypedDict,
)
from .onedot_0dot_1_merchant_division_summary_view import (
    OneDot0Dot1MerchantDivisionSummaryView,
    OneDot0Dot1MerchantDivisionSummaryViewTypedDict,
)
from .onedot_0dot_1_order_decision_details_view import (
    OneDot0Dot1OrderDecisionDetailsView,
    OneDot0Dot1OrderDecisionDetailsViewTypedDict,
)
from .onedot_0dot_1_order_view import (
    OneDot0Dot1OrderView,
    OneDot0Dot1OrderViewTypedDict,
)
from .onedot_0dot_1_review_ticket_view import (
    OneDot0Dot1ReviewTicketView,
    OneDot0Dot1ReviewTicketViewTypedDict,
)
from .onedot_0dot_1_risk_model_external_result_view import (
    OneDot0Dot1RiskModelExternalResultView,
    OneDot0Dot1RiskModelExternalResultViewTypedDict,
)
from .onedot_0dot_1_risk_review_status import OneDot0Dot1RiskReviewStatus
from .onedot_0dot_1_transaction_indemnification_decision import (
    OneDot0Dot1TransactionIndemnificationDecision,
)
from .onedot_0dot_1_transaction_indemnification_reason import (
    OneDot0Dot1TransactionIndemnificationReason,
)
from .onedot_0dot_1_transaction_processor import OneDot0Dot1TransactionProcessor
from .onedot_0dot_1_transaction_splits_view import (
    OneDot0Dot1TransactionSplitsView,
    OneDot0Dot1TransactionSplitsViewTypedDict,
)
from .onedot_0dot_1_transaction_status import OneDot0Dot1TransactionStatus
from .onedot_0dot_1_transaction_timeline_view import (
    OneDot0Dot1TransactionTimelineView,
    OneDot0Dot1TransactionTimelineViewTypedDict,
)
from .onedot_0dot_1_transaction_type import OneDot0Dot1TransactionType
from .onedot_0dot_1_transaction_view import (
    OneDot0Dot1TransactionView,
    OneDot0Dot1TransactionViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OneDot0Dot1TransactionDetailsViewViewStatus(str, Enum):
    NOT_VIEWED = "not_viewed"
    VIEWED = "viewed"
    VIEWING = "viewing"


class AuthVerificationStatus(str, Enum):
    UNKNOWN = ""
    NEW = "new"


class TransactionRejectionDetailsTypedDict(TypedDict):
    auth_rejection_details: NotRequired[OneDot0Dot1AuthRejectionDetailsViewTypedDict]


class TransactionRejectionDetails(BaseModel):
    auth_rejection_details: Optional[OneDot0Dot1AuthRejectionDetailsView] = None


class VoidCause(str, Enum):
    r"""Determines why the transaction was voided."""

    MERCHANT_ACTION = "merchant_action"
    SHOPIFY_SYNC = "shopify_sync"
    PAYPAL_SYNC = "paypal_sync"
    AMAZON_PAY_SYNC = "amazon_pay_sync"
    IRREVERSIBLE_REJECT = "irreversible_reject"
    AUTH_EXPIRE = "auth_expire"
    AUTH_VERIFICATION_EXPIRED = "auth_verification_expired"
    PAYMENT_METHOD_UPDATER = "payment_method_updater"


class OneDot0Dot1TransactionDetailsViewTypedDict(TypedDict):
    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    authorization: NotRequired[OneDot0Dot1CreditCardAuthorizationViewTypedDict]
    capture: NotRequired[OneDot0Dot1CaptureViewTypedDict]
    r"""Deprecated. Use `captures`."""
    captures: NotRequired[List[OneDot0Dot1CreditCardCaptureViewTypedDict]]
    credit: NotRequired[OneDot0Dot1CreditCardCreditViewTypedDict]
    date_: NotRequired[int]
    r"""Transaction date. **Nullable** for Transactions Details."""
    from_consumer: NotRequired[OneDot0Dot1ConsumerSelfViewTypedDict]
    from_credit_card: NotRequired[OneDot0Dot1CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    id: NotRequired[str]
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""
    indemnification_decision: NotRequired[OneDot0Dot1TransactionIndemnificationDecision]
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """
    indemnification_reason: NotRequired[OneDot0Dot1TransactionIndemnificationReason]
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """
    last4: NotRequired[str]
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""
    last_viewed_utc: NotRequired[float]
    merchant_division: NotRequired[OneDot0Dot1MerchantDivisionSummaryViewTypedDict]
    merchant_order_number: NotRequired[str]
    order_decision: NotRequired[OneDot0Dot1OrderDecisionDetailsViewTypedDict]
    processor: NotRequired[OneDot0Dot1TransactionProcessor]
    r"""The processor used. **Nullable** for Transactions Details."""
    reference: NotRequired[str]
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""
    review_ticket: NotRequired[OneDot0Dot1ReviewTicketViewTypedDict]
    risk_insights: NotRequired[OneDot0Dot1RiskModelExternalResultViewTypedDict]
    risk_review_status: NotRequired[OneDot0Dot1RiskReviewStatus]
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""
    risk_score: NotRequired[int]
    splits: NotRequired[List[OneDot0Dot1TransactionSplitsViewTypedDict]]
    status: NotRequired[OneDot0Dot1TransactionStatus]
    r"""The transaction's status."""
    to_consumer: NotRequired[OneDot0Dot1ConsumerSelfViewTypedDict]
    to_credit_card: NotRequired[OneDot0Dot1CreditCardViewTypedDict]
    r"""Contains details about the credit card transaction."""
    transaction_properties: NotRequired[Dict[str, str]]
    type: NotRequired[OneDot0Dot1TransactionType]
    r"""The type of transaction."""
    void: NotRequired[OneDot0Dot1CreditCardVoidViewTypedDict]
    view_status: NotRequired[OneDot0Dot1TransactionDetailsViewViewStatus]
    address_change_request_metadata: NotRequired[
        OneDot0Dot1AddressChangeRequestMetadataViewTypedDict
    ]
    adjust_transactions: NotRequired[List[OneDot0Dot1TransactionViewTypedDict]]
    auth_verification_status: NotRequired[AuthVerificationStatus]
    authorization_id: NotRequired[str]
    chargeback_details: NotRequired[OneDot0Dot1ChargebackDetailsViewTypedDict]
    custom_fields: NotRequired[List[OneDot0Dot1CustomFieldFullResponseViewTypedDict]]
    customer_list_status: NotRequired[OneDot0Dot1CustomerListStatusTypedDict]
    manual_disputes: NotRequired[List[OneDot0Dot1ManualDisputeViewTypedDict]]
    order: NotRequired[OneDot0Dot1OrderViewTypedDict]
    refund_transaction_ids: NotRequired[List[str]]
    refund_transactions: NotRequired[List[OneDot0Dot1TransactionViewTypedDict]]
    r"""**Nullable** for Transactions Details.

    """
    refunded_amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    source_transaction: NotRequired[OneDot0Dot1TransactionViewTypedDict]
    timeline: NotRequired[List[OneDot0Dot1TransactionTimelineViewTypedDict]]
    transaction_rejection_details: NotRequired[TransactionRejectionDetailsTypedDict]
    void_cause: NotRequired[VoidCause]
    r"""Determines why the transaction was voided."""


class OneDot0Dot1TransactionDetailsView(BaseModel):
    amount: Optional[OneDot0Dot1AmountView] = None

    authorization: Optional[OneDot0Dot1CreditCardAuthorizationView] = None

    capture: Optional[OneDot0Dot1CaptureView] = None
    r"""Deprecated. Use `captures`."""

    captures: Optional[List[OneDot0Dot1CreditCardCaptureView]] = None

    credit: Optional[OneDot0Dot1CreditCardCreditView] = None

    date_: Annotated[Optional[int], pydantic.Field(alias="date")] = None
    r"""Transaction date. **Nullable** for Transactions Details."""

    from_consumer: Optional[OneDot0Dot1ConsumerSelfView] = None

    from_credit_card: Optional[OneDot0Dot1CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    id: Optional[str] = None
    r"""The unique ID associated with the transaction. **Nullable** for Transactions Details."""

    indemnification_decision: Optional[
        OneDot0Dot1TransactionIndemnificationDecision
    ] = None
    r"""Describes whether the transaction is indemnified by Bolt for fraud.

    """

    indemnification_reason: Optional[OneDot0Dot1TransactionIndemnificationReason] = None
    r"""Describes the reason that the transaction is or is not indemnified by Bolt for fraud.

    """

    last4: Optional[str] = None
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""

    last_viewed_utc: Optional[float] = None

    merchant_division: Optional[OneDot0Dot1MerchantDivisionSummaryView] = None

    merchant_order_number: Optional[str] = None

    order_decision: Optional[OneDot0Dot1OrderDecisionDetailsView] = None

    processor: Optional[OneDot0Dot1TransactionProcessor] = None
    r"""The processor used. **Nullable** for Transactions Details."""

    reference: Optional[str] = None
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""

    review_ticket: Optional[OneDot0Dot1ReviewTicketView] = None

    risk_insights: Optional[OneDot0Dot1RiskModelExternalResultView] = None

    risk_review_status: Optional[OneDot0Dot1RiskReviewStatus] = None
    r"""Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team."""

    risk_score: Optional[int] = None

    splits: Optional[List[OneDot0Dot1TransactionSplitsView]] = None

    status: Optional[OneDot0Dot1TransactionStatus] = None
    r"""The transaction's status."""

    to_consumer: Optional[OneDot0Dot1ConsumerSelfView] = None

    to_credit_card: Optional[OneDot0Dot1CreditCardView] = None
    r"""Contains details about the credit card transaction."""

    transaction_properties: Optional[Dict[str, str]] = None

    type: Optional[OneDot0Dot1TransactionType] = None
    r"""The type of transaction."""

    void: Optional[OneDot0Dot1CreditCardVoidView] = None

    view_status: Optional[OneDot0Dot1TransactionDetailsViewViewStatus] = None

    address_change_request_metadata: Optional[
        OneDot0Dot1AddressChangeRequestMetadataView
    ] = None

    adjust_transactions: Optional[List[OneDot0Dot1TransactionView]] = None

    auth_verification_status: Optional[AuthVerificationStatus] = None

    authorization_id: Optional[str] = None

    chargeback_details: Optional[OneDot0Dot1ChargebackDetailsView] = None

    custom_fields: Optional[List[OneDot0Dot1CustomFieldFullResponseView]] = None

    customer_list_status: Optional[OneDot0Dot1CustomerListStatus] = None

    manual_disputes: Optional[List[OneDot0Dot1ManualDisputeView]] = None

    order: Optional[OneDot0Dot1OrderView] = None

    refund_transaction_ids: Optional[List[str]] = None

    refund_transactions: Optional[List[OneDot0Dot1TransactionView]] = None
    r"""**Nullable** for Transactions Details.

    """

    refunded_amount: Optional[OneDot0Dot1AmountView] = None

    source_transaction: Optional[OneDot0Dot1TransactionView] = None

    timeline: Optional[List[OneDot0Dot1TransactionTimelineView]] = None

    transaction_rejection_details: Optional[TransactionRejectionDetails] = None

    void_cause: Optional[VoidCause] = None
    r"""Determines why the transaction was voided."""
