"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_i_cart_item_view import (
    OneDot0Dot1ICartItemView,
    OneDot0Dot1ICartItemViewTypedDict,
)
from .onedot_0dot_1_i_cart_shipment_view import (
    OneDot0Dot1ICartShipmentView,
    OneDot0Dot1ICartShipmentViewTypedDict,
)
from .onedot_0dot_1_in_store_shipment2 import (
    OneDot0Dot1InStoreShipment2,
    OneDot0Dot1InStoreShipment2TypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1FulfillmentViewTypedDict(TypedDict):
    cart_shipment: NotRequired[OneDot0Dot1ICartShipmentViewTypedDict]
    fulfillment_type: NotRequired[str]
    id: NotRequired[str]
    in_store_cart_shipment: NotRequired[OneDot0Dot1InStoreShipment2TypedDict]
    r"""A cart that is being prepared for shipment"""
    items: NotRequired[List[OneDot0Dot1ICartItemViewTypedDict]]


class OneDot0Dot1FulfillmentView(BaseModel):
    cart_shipment: Optional[OneDot0Dot1ICartShipmentView] = None

    fulfillment_type: Optional[str] = None

    id: Optional[str] = None

    in_store_cart_shipment: Optional[OneDot0Dot1InStoreShipment2] = None
    r"""A cart that is being prepared for shipment"""

    items: Optional[List[OneDot0Dot1ICartItemView]] = None
