"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1MerchantLogoTypedDict(TypedDict):
    domain: NotRequired[str]
    r"""The URL of the merchant division."""
    resource: NotRequired[str]
    r"""The logo image file for the merchant division."""


class OneDot0Dot1MerchantLogo(BaseModel):
    domain: Optional[str] = None
    r"""The URL of the merchant division."""

    resource: Optional[str] = None
    r"""The logo image file for the merchant division."""
