"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class OneDot0Dot1TransactionProcessorStatus(str, Enum):
    r"""The processor's status. Only `primary` and `active` processor are displayed."""

    PRIMARY = "primary"
    ACTIVE = "active"
    INACTIVE = "inactive"
