"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_chargeback_event_view import (
    OneDot0Dot1ChargebackEventView,
    OneDot0Dot1ChargebackEventViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RepresentmentResult(str, Enum):
    NONE = "none"
    OPEN = "open"
    LOST = "lost"
    WON = "won"


class OneDot0Dot1ChargebackDetailsViewTypedDict(TypedDict):
    amt_won: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_amt: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_fee: NotRequired[OneDot0Dot1AmountViewTypedDict]
    chargeback_id: NotRequired[str]
    event_views: NotRequired[List[OneDot0Dot1ChargebackEventViewTypedDict]]
    net_amt: NotRequired[OneDot0Dot1AmountViewTypedDict]
    reason: NotRequired[str]
    reason_code: NotRequired[str]
    representment_reply_by_date: NotRequired[float]
    r"""The reply-by date of the dispute in UnixMillis format."""
    representment_result: NotRequired[RepresentmentResult]


class OneDot0Dot1ChargebackDetailsView(BaseModel):
    amt_won: Optional[OneDot0Dot1AmountView] = None

    chargeback_amt: Optional[OneDot0Dot1AmountView] = None

    chargeback_fee: Optional[OneDot0Dot1AmountView] = None

    chargeback_id: Optional[str] = None

    event_views: Optional[List[OneDot0Dot1ChargebackEventView]] = None

    net_amt: Optional[OneDot0Dot1AmountView] = None

    reason: Optional[str] = None

    reason_code: Optional[str] = None

    representment_reply_by_date: Optional[float] = None
    r"""The reply-by date of the dispute in UnixMillis format."""

    representment_result: Optional[RepresentmentResult] = None
