"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_capture_status import OneDot0Dot1CaptureStatus
from .onedot_0dot_1_transaction_splits_view import (
    OneDot0Dot1TransactionSplitsView,
    OneDot0Dot1TransactionSplitsViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Dict, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CreditCardCaptureViewTypedDict(TypedDict):
    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    id: NotRequired[str]
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    metadata: NotRequired[Dict[str, str]]
    splits: NotRequired[OneDot0Dot1TransactionSplitsViewTypedDict]
    status: NotRequired[OneDot0Dot1CaptureStatus]
    r"""The status of the capture. **Nullable** for Transactions Details."""


class OneDot0Dot1CreditCardCaptureView(BaseModel):
    amount: Optional[OneDot0Dot1AmountView] = None

    id: Optional[str] = None
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    metadata: Optional[Dict[str, str]] = None

    splits: Optional[OneDot0Dot1TransactionSplitsView] = None

    status: Optional[OneDot0Dot1CaptureStatus] = None
    r"""The status of the capture. **Nullable** for Transactions Details."""
