"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_address_view import (
    OneDot0Dot1AddressView,
    OneDot0Dot1AddressViewTypedDict,
)
from .onedot_0dot_1_card_network import OneDot0Dot1CardNetwork
from .onedot_0dot_1_shopper_metadata import (
    OneDot0Dot1ShopperMetadata,
    OneDot0Dot1ShopperMetadataTypedDict,
)
from bolt_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1SavedCreditCardViewType(str, Enum):
    r"""The payment method type. If empty, the property defaults to `card`."""

    CARD = "card"
    PAYPAL = "paypal"


class OneDot0Dot1SavedCreditCardViewTypedDict(TypedDict):
    r"""Saved Credit Card Detail"""

    billing_address: NotRequired[OneDot0Dot1AddressViewTypedDict]
    r"""The address object returned in the response."""
    id: NotRequired[str]
    r"""The ID of the payment method associated with the Shopper's account."""
    last4: NotRequired[str]
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""
    exp_month: NotRequired[int]
    r"""The expiration month of the credit card."""
    exp_year: NotRequired[int]
    r"""The expiration year of the credit card."""
    network: NotRequired[OneDot0Dot1CardNetwork]
    r"""The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard

    """
    default: NotRequired[bool]
    r"""The default card payment method chosen by the shopper."""
    type: NotRequired[OneDot0Dot1SavedCreditCardViewType]
    r"""The payment method type. If empty, the property defaults to `card`."""
    description: NotRequired[str]
    r"""The APM account identifier; usually the email address."""
    metadata: NotRequired[Nullable[OneDot0Dot1ShopperMetadataTypedDict]]
    r"""A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).

    """


class OneDot0Dot1SavedCreditCardView(BaseModel):
    r"""Saved Credit Card Detail"""

    billing_address: Optional[OneDot0Dot1AddressView] = None
    r"""The address object returned in the response."""

    id: Optional[str] = None
    r"""The ID of the payment method associated with the Shopper's account."""

    last4: Optional[str] = None
    r"""The card's last 4 digits. **Nullable** for Transactions Details."""

    exp_month: Optional[int] = None
    r"""The expiration month of the credit card."""

    exp_year: Optional[int] = None
    r"""The expiration year of the credit card."""

    network: Optional[OneDot0Dot1CardNetwork] = None
    r"""The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard

    """

    default: Optional[bool] = None
    r"""The default card payment method chosen by the shopper."""

    type: Optional[OneDot0Dot1SavedCreditCardViewType] = None
    r"""The payment method type. If empty, the property defaults to `card`."""

    description: Optional[str] = None
    r"""The APM account identifier; usually the email address."""

    metadata: OptionalNullable[OneDot0Dot1ShopperMetadata] = UNSET
    r"""A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "billing_address",
            "id",
            "last4",
            "exp_month",
            "exp_year",
            "network",
            "default",
            "type",
            "description",
            "metadata",
        ]
        nullable_fields = ["metadata"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
