"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_tracking_detail import (
    OneDot0Dot1TrackingDetail,
    OneDot0Dot1TrackingDetailTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import List
from typing_extensions import TypedDict


class OneDot0Dot1MockTrackingInputStatus(str, Enum):
    r"""The shipment status of a simulated order."""

    IN_TRANSIT = "in_transit"
    CANCELLED = "cancelled"
    FAILURE = "failure"
    DELIVERED = "delivered"


class OneDot0Dot1MockTrackingInputTypedDict(TypedDict):
    delivery_estimate: str
    status: OneDot0Dot1MockTrackingInputStatus
    r"""The shipment status of a simulated order."""
    tracking_detail: List[OneDot0Dot1TrackingDetailTypedDict]
    r"""A list of tracking updates that contain the shipment's status, location, and any unique messages."""
    tracking_number: str
    r"""The carrier's tracking number for the shipment (Order Tracking Testing). Must begin with `MockBolt`."""


class OneDot0Dot1MockTrackingInput(BaseModel):
    delivery_estimate: str

    status: OneDot0Dot1MockTrackingInputStatus
    r"""The shipment status of a simulated order."""

    tracking_detail: List[OneDot0Dot1TrackingDetail]
    r"""A list of tracking updates that contain the shipment's status, location, and any unique messages."""

    tracking_number: str
    r"""The carrier's tracking number for the shipment (Order Tracking Testing). Must begin with `MockBolt`."""
