"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_risk_model_result_view import (
    OneDot0Dot1RiskModelResultView,
    OneDot0Dot1RiskModelResultViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OneDot0Dot1TransactionReviewViewTypedDict(TypedDict):
    date_: NotRequired[float]
    decision: NotRequired[str]
    risk_model_result: NotRequired[OneDot0Dot1RiskModelResultViewTypedDict]
    source: NotRequired[str]


class OneDot0Dot1TransactionReviewView(BaseModel):
    date_: Annotated[Optional[float], pydantic.Field(alias="date")] = None

    decision: Optional[str] = None

    risk_model_result: Optional[OneDot0Dot1RiskModelResultView] = None

    source: Optional[str] = None
