"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amounts import OneDot0Dot1Amounts, OneDot0Dot1AmountsTypedDict
from .onedot_0dot_1_item_property import (
    OneDot0Dot1ItemProperty,
    OneDot0Dot1ItemPropertyTypedDict,
)
from .onedot_0dot_1_item_shipment_type import OneDot0Dot1ItemShipmentType
from .onedot_0dot_1_metadata_component import (
    OneDot0Dot1MetadataComponent,
    OneDot0Dot1MetadataComponentTypedDict,
)
from .onedot_0dot_1_total_weight import (
    OneDot0Dot1TotalWeight,
    OneDot0Dot1TotalWeightTypedDict,
)
from .onedot_0dot_1_type import OneDot0Dot1Type
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CustomizationTypedDict(TypedDict):
    attributes: OneDot0Dot1MetadataComponentTypedDict
    name: str
    r"""The name of the customization."""
    price: OneDot0Dot1AmountsTypedDict
    r"""The amount. **Nullable** for Transactions Details."""


class Customization(BaseModel):
    attributes: OneDot0Dot1MetadataComponent

    name: str
    r"""The name of the customization."""

    price: OneDot0Dot1Amounts
    r"""The amount. **Nullable** for Transactions Details."""


class OneDot0Dot1ItemTypedDict(TypedDict):
    r"""An item with properties."""

    name: str
    r"""The name of an item."""
    quantity: int
    r"""The quantity of this item."""
    reference: str
    r"""Reference for the object."""
    total_amount: OneDot0Dot1AmountsTypedDict
    r"""The amount. **Nullable** for Transactions Details."""
    unit_price: OneDot0Dot1AmountsTypedDict
    r"""The amount. **Nullable** for Transactions Details."""
    bolt_product_id: NotRequired[str]
    r"""Unique ID generated for a product via the products endpoint."""
    brand: NotRequired[str]
    r"""The name of a brand."""
    category: NotRequired[str]
    r"""A category."""
    collections: NotRequired[List[str]]
    color: NotRequired[str]
    r"""The color."""
    customizations: NotRequired[List[CustomizationTypedDict]]
    description: NotRequired[str]
    r"""A description for the item added to the cart/order."""
    details_url: NotRequired[str]
    r"""The URL for the item's details."""
    image_url: NotRequired[str]
    r"""The URL for the item's image."""
    isbn: NotRequired[str]
    r"""A 13-digit identifier for a book item."""
    item_group: NotRequired[str]
    r"""Enables grouping in the checkout UI."""
    manufacturer: NotRequired[str]
    r"""The name of a manufacturer."""
    options: NotRequired[str]
    properties: NotRequired[List[OneDot0Dot1ItemPropertyTypedDict]]
    shipment_type: NotRequired[OneDot0Dot1ItemShipmentType]
    r"""The shipment type selected by the shopper."""
    size: NotRequired[str]
    r"""The size."""
    sku: NotRequired[str]
    r"""The SKU identifier for this item or service."""
    tags: NotRequired[str]
    r"""A tag"""
    tax_amount: NotRequired[OneDot0Dot1AmountsTypedDict]
    r"""The amount. **Nullable** for Transactions Details."""
    taxable: NotRequired[bool]
    r"""Determines if item is taxable."""
    type: NotRequired[OneDot0Dot1Type]
    r"""Determines if item is a physical, digital, or bundled good, or if the good type is unknown."""
    uom: NotRequired[str]
    upc: NotRequired[str]
    weight: NotRequired[OneDot0Dot1TotalWeightTypedDict]


class OneDot0Dot1Item(BaseModel):
    r"""An item with properties."""

    name: str
    r"""The name of an item."""

    quantity: int
    r"""The quantity of this item."""

    reference: str
    r"""Reference for the object."""

    total_amount: OneDot0Dot1Amounts
    r"""The amount. **Nullable** for Transactions Details."""

    unit_price: OneDot0Dot1Amounts
    r"""The amount. **Nullable** for Transactions Details."""

    bolt_product_id: Optional[str] = None
    r"""Unique ID generated for a product via the products endpoint."""

    brand: Optional[str] = None
    r"""The name of a brand."""

    category: Optional[str] = None
    r"""A category."""

    collections: Optional[List[str]] = None

    color: Optional[str] = None
    r"""The color."""

    customizations: Optional[List[Customization]] = None

    description: Optional[str] = None
    r"""A description for the item added to the cart/order."""

    details_url: Optional[str] = None
    r"""The URL for the item's details."""

    image_url: Optional[str] = None
    r"""The URL for the item's image."""

    isbn: Optional[str] = None
    r"""A 13-digit identifier for a book item."""

    item_group: Optional[str] = None
    r"""Enables grouping in the checkout UI."""

    manufacturer: Optional[str] = None
    r"""The name of a manufacturer."""

    options: Optional[str] = None

    properties: Optional[List[OneDot0Dot1ItemProperty]] = None

    shipment_type: Optional[OneDot0Dot1ItemShipmentType] = None
    r"""The shipment type selected by the shopper."""

    size: Optional[str] = None
    r"""The size."""

    sku: Optional[str] = None
    r"""The SKU identifier for this item or service."""

    tags: Optional[str] = None
    r"""A tag"""

    tax_amount: Optional[OneDot0Dot1Amounts] = None
    r"""The amount. **Nullable** for Transactions Details."""

    taxable: Optional[bool] = None
    r"""Determines if item is taxable."""

    type: Optional[OneDot0Dot1Type] = None
    r"""Determines if item is a physical, digital, or bundled good, or if the good type is unknown."""

    uom: Optional[str] = None

    upc: Optional[str] = None

    weight: Optional[OneDot0Dot1TotalWeight] = None
