"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_item import OneDot0Dot1Item, OneDot0Dot1ItemTypedDict
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1OrderTrackRequestBodyTypedDict(TypedDict):
    r"""Send order tracking details."""

    carrier: str
    r"""the name of the carrier used for shipment."""
    items: List[OneDot0Dot1ItemTypedDict]
    r"""A list of items."""
    tracking_number: str
    r"""The carrier's tracking number for the shipment."""
    transaction_reference: str
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""
    is_non_bolt_order: NotRequired[bool]
    r"""Designates if the order was placed outside of Bolt checkout."""


class OneDot0Dot1OrderTrackRequestBody(BaseModel):
    r"""Send order tracking details."""

    carrier: str
    r"""the name of the carrier used for shipment."""

    items: List[OneDot0Dot1Item]
    r"""A list of items."""

    tracking_number: str
    r"""The carrier's tracking number for the shipment."""

    transaction_reference: str
    r"""The transaction's 12-digit Bolt reference ID. **Nullable** for Transactions Details."""

    is_non_bolt_order: Optional[bool] = None
    r"""Designates if the order was placed outside of Bolt checkout."""
