"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_payment_service import OneDot0Dot1PaymentService
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1EligiblePaymentMethodTypedDict(TypedDict):
    eligible: NotRequired[bool]
    transaction_processor_type: NotRequired[OneDot0Dot1PaymentService]


class OneDot0Dot1EligiblePaymentMethod(BaseModel):
    eligible: Optional[bool] = None

    transaction_processor_type: Optional[OneDot0Dot1PaymentService] = None
