"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_amount_view import (
    OneDot0Dot1AmountView,
    OneDot0Dot1AmountViewTypedDict,
)
from .onedot_0dot_1_capture_status import OneDot0Dot1CaptureStatus
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1CaptureViewType(str, Enum):
    r"""Fee type options. **Nullable** for Transactions Details."""

    NET = "net"
    PROCESSING_FEE = "processing_fee"
    RISK_FEE = "risk_fee"
    APM_FEE = "apm_fee"
    NETWORK_FEE = "network_fee"
    PLATFORM_FEE = "platform_fee"
    BOLT_ACCOUNT_FEE = "bolt_account_fee"


class SplitTypedDict(TypedDict):
    r"""A split of fees by type and amount."""

    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    type: NotRequired[OneDot0Dot1CaptureViewType]
    r"""Fee type options. **Nullable** for Transactions Details.

    """


class Split(BaseModel):
    r"""A split of fees by type and amount."""

    amount: Optional[OneDot0Dot1AmountView] = None

    type: Optional[OneDot0Dot1CaptureViewType] = None
    r"""Fee type options. **Nullable** for Transactions Details.

    """


class OneDot0Dot1CaptureViewTypedDict(TypedDict):
    r"""Deprecated. Use `captures`."""

    amount: NotRequired[OneDot0Dot1AmountViewTypedDict]
    id: NotRequired[str]
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""
    merchant_event_id: NotRequired[str]
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""
    metadata: NotRequired[Dict[str, str]]
    r"""Additional information about the capture. For example, the processor capture ID. **Nullable** for Transactions Details."""
    splits: NotRequired[List[SplitTypedDict]]
    r"""A split of fees by type and amount. **Nullable** for Transactions Details."""
    status: NotRequired[OneDot0Dot1CaptureStatus]
    r"""The status of the capture. **Nullable** for Transactions Details."""


class OneDot0Dot1CaptureView(BaseModel):
    r"""Deprecated. Use `captures`."""

    amount: Optional[OneDot0Dot1AmountView] = None

    id: Optional[str] = None
    r"""The unique ID for the capture. **Nullable** for Transactions Details."""

    merchant_event_id: Optional[str] = None
    r"""The reference ID associated with a transaction event (auth, capture, refund, void). This is an arbitrary identifier created by the merchant. Bolt does not enforce any uniqueness constraints on this ID. It is up to the merchant to generate identifiers that properly fulfill its needs."""

    metadata: Optional[Dict[str, str]] = None
    r"""Additional information about the capture. For example, the processor capture ID. **Nullable** for Transactions Details."""

    splits: Optional[List[Split]] = None
    r"""A split of fees by type and amount. **Nullable** for Transactions Details."""

    status: Optional[OneDot0Dot1CaptureStatus] = None
    r"""The status of the capture. **Nullable** for Transactions Details."""
