"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_cart_view import OneDot0Dot1CartView, OneDot0Dot1CartViewTypedDict
from .onedot_0dot_1_i_order_dynamic_content import (
    OneDot0Dot1IOrderDynamicContent,
    OneDot0Dot1IOrderDynamicContentTypedDict,
)
from .onedot_0dot_1_order_external_data_view import (
    OneDot0Dot1OrderExternalDataView,
    OneDot0Dot1OrderExternalDataViewTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1OrderViewTypedDict(TypedDict):
    cart: NotRequired[OneDot0Dot1CartViewTypedDict]
    r"""This is the cart object returned in a successful response."""
    dynamic_content: NotRequired[OneDot0Dot1IOrderDynamicContentTypedDict]
    external_data: NotRequired[OneDot0Dot1OrderExternalDataViewTypedDict]
    platform_user_id: NotRequired[str]
    requires_action: NotRequired[str]
    token: NotRequired[str]
    user_note: NotRequired[str]
    r"""Used by shoppers to make extra requests or provide details for gift messages."""


class OneDot0Dot1OrderView(BaseModel):
    cart: Optional[OneDot0Dot1CartView] = None
    r"""This is the cart object returned in a successful response."""

    dynamic_content: Optional[OneDot0Dot1IOrderDynamicContent] = None

    external_data: Optional[OneDot0Dot1OrderExternalDataView] = None

    platform_user_id: Optional[str] = None

    requires_action: Optional[str] = None

    token: Optional[str] = None

    user_note: Optional[str] = None
    r"""Used by shoppers to make extra requests or provide details for gift messages."""
