"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .onedot_0dot_1_auth_rejection_details import (
    OneDot0Dot1AuthRejectionDetails,
    OneDot0Dot1AuthRejectionDetailsTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OneDot0Dot1TransactionRejectionDetailsViewTypedDict(TypedDict):
    auth_rejection_details: NotRequired[OneDot0Dot1AuthRejectionDetailsTypedDict]


class OneDot0Dot1TransactionRejectionDetailsView(BaseModel):
    auth_rejection_details: Optional[OneDot0Dot1AuthRejectionDetails] = None
