"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_order import ThreeDot3Dot7Order, ThreeDot3Dot7OrderTypedDict
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
    SecurityMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ORDERS_CREATE_OP_SERVERS = [
    "https://{environment}.bolt.com/v3",
]


class OrdersCreateSecurityTypedDict(TypedDict):
    three_dot_3_dot_7_api_key: str


class OrdersCreateSecurity(BaseModel):
    three_dot_3_dot_7_api_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ]


class OrdersCreateRequestTypedDict(TypedDict):
    x_publishable_key: str
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""
    three_dot_3_dot_7_order: ThreeDot3Dot7OrderTypedDict
    x_merchant_client_id: NotRequired[str]
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""


class OrdersCreateRequest(BaseModel):
    x_publishable_key: Annotated[
        str,
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""

    three_dot_3_dot_7_order: Annotated[
        ThreeDot3Dot7Order,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_merchant_client_id: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Merchant-Client-Id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""
