"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PackageDimensionTypedDict(TypedDict):
    r"""Contains the package's width, eight, depth, and unit details."""

    depth: NotRequired[int]
    r"""The depth."""
    height: NotRequired[int]
    r"""The height."""
    unit: NotRequired[str]
    r"""The unit of measurement for an item's dimensions."""
    width: NotRequired[int]
    r"""The width."""


class PackageDimension(BaseModel):
    r"""Contains the package's width, eight, depth, and unit details."""

    depth: Optional[int] = None
    r"""The depth."""

    height: Optional[int] = None
    r"""The height."""

    unit: Optional[str] = None
    r"""The unit of measurement for an item's dimensions."""

    width: Optional[int] = None
    r"""The width."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["depth", "height", "unit", "width"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
