"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_payment_action_request import (
    ThreeDot3Dot7PaymentActionRequest,
    ThreeDot3Dot7PaymentActionRequestTypedDict,
)
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
    SecurityMetadata,
)
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


PAYMENTS_ACTION_OP_SERVERS = [
    "https://{environment}.bolt.com/v3",
]


class PaymentsActionSecurityTypedDict(TypedDict):
    three_dot_3_dot_7_oauth: str
    three_dot_3_dot_7_api_key: str


class PaymentsActionSecurity(BaseModel):
    three_dot_3_dot_7_oauth: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", field_name="Authorization"
            )
        ),
    ]

    three_dot_3_dot_7_api_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ]


class PaymentsActionRequestTypedDict(TypedDict):
    x_publishable_key: str
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""
    id: str
    r"""The ID of the payment to operate on"""
    three_dot_3_dot_7_payment_action_request: ThreeDot3Dot7PaymentActionRequestTypedDict
    x_merchant_client_id: NotRequired[str]
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""


class PaymentsActionRequest(BaseModel):
    x_publishable_key: Annotated[
        str,
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the payment to operate on"""

    three_dot_3_dot_7_payment_action_request: Annotated[
        ThreeDot3Dot7PaymentActionRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_merchant_client_id: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Merchant-Client-Id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""A unique identifier for a shopper's device, generated by Bolt. The value is retrieved with `Bolt.state.merchantClientId` in your frontend context, per-shopper. This header is required for proper attribution of this operation to your analytics reports. Omitting this header may result in incorrect statistics."""
