"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .request_status import RequestStatus
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ReviewTicketTypedDict(TypedDict):
    r"""Internal use only."""

    id: NotRequired[str]
    r"""The unique ID for the request ticket."""
    request_deadline: NotRequired[int]
    status: NotRequired[RequestStatus]


class ReviewTicket(BaseModel):
    r"""Internal use only."""

    id: Optional[str] = None
    r"""The unique ID for the request ticket."""

    request_deadline: Optional[int] = None

    status: Optional[RequestStatus] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "request_deadline", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
