"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .shopper_metadata import ShopperMetadata, ShopperMetadataTypedDict
from bolt_api_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SavedPaypalAccountViewType(str, Enum):
    r"""Type field indicates this is a saved PayPal to differentiate it from a saved card."""

    PAYPAL = "paypal"


class SavedPaypalAccountViewTypedDict(TypedDict):
    r"""Saved PayPal account details."""

    id: NotRequired[str]
    r"""The ID of the payment method associated with the Shopper's account."""
    type: NotRequired[SavedPaypalAccountViewType]
    r"""Type field indicates this is a saved PayPal to differentiate it from a saved card."""
    description: NotRequired[str]
    r"""The email associated with a shopper's saved PayPal account."""
    metadata: NotRequired[Nullable[ShopperMetadataTypedDict]]
    r"""A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).

    """


class SavedPaypalAccountView(BaseModel):
    r"""Saved PayPal account details."""

    id: Optional[str] = None
    r"""The ID of the payment method associated with the Shopper's account."""

    type: Optional[SavedPaypalAccountViewType] = None
    r"""Type field indicates this is a saved PayPal to differentiate it from a saved card."""

    description: Optional[str] = None
    r"""The email associated with a shopper's saved PayPal account."""

    metadata: OptionalNullable[ShopperMetadata] = UNSET
    r"""A key-value pair object that allows users to store arbitrary information associated with an object.  For any individual account object, we allow up to 50 keys. Keys can be up to 40 characters long and values can be up to 500 characters long.  Metadata should not contain any sensitive customer information, like PII (Personally Identifiable Information). For more information about metadata, see our [documentation](https://help.bolt.com/developers/references/embedded-metadata/).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "description", "metadata"])
        nullable_fields = set(["metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
