"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amount_view import AmountView, AmountViewTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SplitsViewType(str, Enum):
    r"""**Nullable** for Transactions Details."""

    NET = "net"
    PROCESSING_FEE = "processing_fee"
    BOLT_FEE = "bolt_fee"
    ADJUSTMENT = "adjustment"
    FLOAT = "float"
    RESERVE = "reserve"


class SplitsViewTypedDict(TypedDict):
    r"""A split of fees by type and amount."""

    amount: NotRequired[AmountViewTypedDict]
    type: NotRequired[SplitsViewType]
    r"""**Nullable** for Transactions Details.

    """


class SplitsView(BaseModel):
    r"""A split of fees by type and amount."""

    amount: Optional[AmountView] = None

    type: Optional[SplitsViewType] = None
    r"""**Nullable** for Transactions Details.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
