"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class SubscriptionV2SuccessTypedDict(TypedDict):
    r"""A generic confirmation response."""

    success: bool


class SubscriptionV2Success(BaseModel):
    r"""A generic confirmation response."""

    success: bool
