"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscription_v2_initial_period import (
    SubscriptionV2InitialPeriod,
    SubscriptionV2InitialPeriodTypedDict,
)
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SubscriptionV2PlanFrequencyUnit(str, Enum):
    r"""The unit of time between billing cycles."""

    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"


class SubscriptionV2PlanTypedDict(TypedDict):
    r"""The billing plan the subscription is enrolled in."""

    id: str
    r"""The unique ID for the subscription plan."""
    name: str
    r"""The display name of the plan."""
    sku: str
    r"""The merchant-defined SKU for the plan."""
    created_at: datetime
    updated_at: datetime
    frequency: int
    r"""The number of `frequency_unit`s between each billing cycle."""
    frequency_unit: SubscriptionV2PlanFrequencyUnit
    r"""The unit of time between billing cycles."""
    product_id: str
    r"""The unique ID of the subscription product this plan belongs to."""
    checkout_link: NotRequired[str]
    r"""A hosted checkout link for this plan, when available."""
    initial_period: NotRequired[SubscriptionV2InitialPeriodTypedDict]
    r"""An initial billing period, such as a trial or introductory offer, that differs from the plan's regular frequency."""


class SubscriptionV2Plan(BaseModel):
    r"""The billing plan the subscription is enrolled in."""

    id: str
    r"""The unique ID for the subscription plan."""

    name: str
    r"""The display name of the plan."""

    sku: str
    r"""The merchant-defined SKU for the plan."""

    created_at: datetime

    updated_at: datetime

    frequency: int
    r"""The number of `frequency_unit`s between each billing cycle."""

    frequency_unit: SubscriptionV2PlanFrequencyUnit
    r"""The unit of time between billing cycles."""

    product_id: str
    r"""The unique ID of the subscription product this plan belongs to."""

    checkout_link: Optional[str] = None
    r"""A hosted checkout link for this plan, when available."""

    initial_period: Optional[SubscriptionV2InitialPeriod] = None
    r"""An initial billing period, such as a trial or introductory offer, that differs from the plan's regular frequency."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["checkout_link", "initial_period"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
