"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing_extensions import TypedDict


class SubscriptionV2InitialPeriodFrequencyUnit(str, Enum):
    r"""The unit of time for the initial period's frequency."""

    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"


class SubscriptionV2InitialPeriodTypedDict(TypedDict):
    r"""An initial billing period, such as a trial or introductory offer, that differs from the plan's regular frequency."""

    frequency: int
    r"""The number of `frequency_unit`s in the initial period."""
    frequency_unit: SubscriptionV2InitialPeriodFrequencyUnit
    r"""The unit of time for the initial period's frequency."""


class SubscriptionV2InitialPeriod(BaseModel):
    r"""An initial billing period, such as a trial or introductory offer, that differs from the plan's regular frequency."""

    frequency: int
    r"""The number of `frequency_unit`s in the initial period."""

    frequency_unit: SubscriptionV2InitialPeriodFrequencyUnit
    r"""The unit of time for the initial period's frequency."""
