"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class SubscriptionV2PaginationTypedDict(TypedDict):
    r"""Pagination details for a list response."""

    page_size: int
    total_count: int


class SubscriptionV2Pagination(BaseModel):
    r"""Pagination details for a list response."""

    page_size: int

    total_count: int
