"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .subscription_v2 import SubscriptionV2, SubscriptionV2TypedDict
from .subscription_v2_pagination import (
    SubscriptionV2Pagination,
    SubscriptionV2PaginationTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SubscriptionV2ListTypedDict(TypedDict):
    r"""A paginated list of subscriptions."""

    subscriptions: List[SubscriptionV2TypedDict]
    pagination: SubscriptionV2PaginationTypedDict
    r"""Pagination details for a list response."""


class SubscriptionV2List(BaseModel):
    r"""A paginated list of subscriptions."""

    subscriptions: List[SubscriptionV2]

    pagination: SubscriptionV2Pagination
    r"""Pagination details for a list response."""
