"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SubscriptionV2OrderStatus(str, Enum):
    r"""The status of a subscription order."""

    SCHEDULED = "scheduled"
    DONE = "done"
    PAUSED = "paused"
    PAYMENT_FAILED = "payment_failed"
    CANCELED = "canceled"
