"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Unit(str, Enum):
    r"""The unit for this subscription's frequency."""

    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"


class FrequencyTypedDict(TypedDict):
    r"""Describes how often the subscription recurs."""

    unit: NotRequired[Unit]
    r"""The unit for this subscription's frequency."""
    value: NotRequired[int]
    r"""The value applied to the unit frequency."""


class Frequency(BaseModel):
    r"""Describes how often the subscription recurs."""

    unit: Optional[Unit] = None
    r"""The unit for this subscription's frequency."""

    value: Optional[int] = None
    r"""The value applied to the unit frequency."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unit", "value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SubscriptionTypedDict(TypedDict):
    r"""Describes a product added as a recurring subscription."""

    frequency: NotRequired[FrequencyTypedDict]
    r"""Describes how often the subscription recurs."""


class Subscription(BaseModel):
    r"""Describes a product added as a recurring subscription."""

    frequency: Optional[Frequency] = None
    r"""Describes how often the subscription recurs."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["frequency"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
