"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import FieldMetadata, HeaderMetadata, SecurityMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


TESTING_ACCOUNT_PHONE_GET_OP_SERVERS = [
    "https://{environment}.bolt.com/v3",
]


class TestingAccountPhoneGetSecurityTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    three_dot_3_dot_7_api_key: str


class TestingAccountPhoneGetSecurity(BaseModel):
    __test__ = False

    three_dot_3_dot_7_api_key: Annotated[
        str,
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="apiKey",
                sub_type="header",
                field_name="X-API-Key",
            )
        ),
    ]


class TestingAccountPhoneGetRequestTypedDict(TypedDict):
    __test__ = False  # pyright: ignore[reportGeneralTypeIssues]

    x_publishable_key: str
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""


class TestingAccountPhoneGetRequest(BaseModel):
    __test__ = False

    x_publishable_key: Annotated[
        str,
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The publicly shareable identifier used to identify your Bolt merchant division."""
