"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ThreeDot3Dot7CreditCardErrorTag(str, Enum):
    r"""The type of error returned"""

    DECLINED = "declined"
    DECLINED_INVALID_AMOUNT = "declined_invalid_amount"
    DECLINED_INVALID_CVV = "declined_invalid_cvv"
    DECLINED_INVALID_MERCHANT = "declined_invalid_merchant"
    DECLINED_INVALID_NUMBER = "declined_invalid_number"
    DECLINED_EXPIRED = "declined_expired"
    DECLINED_CALL_ISSUER = "declined_call_issuer"
    DECLINED_UNSUPPORTED = "declined_unsupported"
