"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing_extensions import TypedDict


class Currency(str, Enum):
    r"""A supported currency."""

    AUD = "AUD"
    CAD = "CAD"
    EUR = "EUR"
    GBP = "GBP"
    USD = "USD"


class ThreeDot3Dot7AmountTypedDict(TypedDict):
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    currency: Currency
    r"""A supported currency."""
    units: int
    r"""A monetary amount, represented in its base units (e.g. USD/EUR cents)."""


class ThreeDot3Dot7Amount(BaseModel):
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    currency: Currency
    r"""A supported currency."""

    units: int
    r"""A monetary amount, represented in its base units (e.g. USD/EUR cents)."""
