"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodAfterpayTag(str, Enum):
    AFTERPAY = "afterpay"


class ThreeDot3Dot7PaymentMethodAfterpayOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodAfterpayTag


class ThreeDot3Dot7PaymentMethodAfterpayOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodAfterpayTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodAfterpayTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodAfterpayTag
    return_url: str
    r"""Return URL to return to after payment completion in Afterpay."""


class ThreeDot3Dot7PaymentMethodAfterpay(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodAfterpayTag, pydantic.Field(alias=".tag")
    ]

    return_url: str
    r"""Return URL to return to after payment completion in Afterpay."""
