"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7ProcessorResponseTypedDict(TypedDict):
    r"""Raw authorization response from the payment processor"""

    content_type: NotRequired[str]
    api_version: NotRequired[str]
    text: NotRequired[str]


class ThreeDot3Dot7ProcessorResponse(BaseModel):
    r"""Raw authorization response from the payment processor"""

    content_type: Optional[str] = None

    api_version: Optional[str] = None

    text: Optional[str] = None
