"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodPaypalTag(str, Enum):
    PAYPAL = "paypal"


class ThreeDot3Dot7PaymentMethodPaypalOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodPaypalTag


class ThreeDot3Dot7PaymentMethodPaypalOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodPaypalTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodPaypalTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodPaypalTag
    success_url: str
    r"""Redirect URL for successful PayPal transaction."""
    cancel_url: str
    r"""Redirect URL for canceled PayPal transaction."""


class ThreeDot3Dot7PaymentMethodPaypal(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodPaypalTag, pydantic.Field(alias=".tag")
    ]

    success_url: str
    r"""Redirect URL for successful PayPal transaction."""

    cancel_url: str
    r"""Redirect URL for canceled PayPal transaction."""
