"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_cart import ThreeDot3Dot7Cart, ThreeDot3Dot7CartTypedDict
from .threedot_3dot_7_profile import ThreeDot3Dot7Profile, ThreeDot3Dot7ProfileTypedDict
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class ThreeDot3Dot7OrderTypedDict(TypedDict):
    profile: ThreeDot3Dot7ProfileTypedDict
    r"""An account's identifying information."""
    cart: ThreeDot3Dot7CartTypedDict


class ThreeDot3Dot7Order(BaseModel):
    profile: ThreeDot3Dot7Profile
    r"""An account's identifying information."""

    cart: ThreeDot3Dot7Cart
