"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodKlarnaTag(str, Enum):
    KLARNA = "klarna"


class ThreeDot3Dot7PaymentMethodKlarnaOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaTag


class ThreeDot3Dot7PaymentMethodKlarnaOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodKlarnaTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaTag
    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""


class ThreeDot3Dot7PaymentMethodKlarna(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaTag, pydantic.Field(alias=".tag")
    ]

    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""
