"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7AddressReferenceIDTag(str, Enum):
    r"""The type of address reference"""

    ID = "id"


class ThreeDot3Dot7AddressReferenceIDTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7AddressReferenceIDTag
    r"""The type of address reference"""
    id: str
    r"""The address's ID"""


class ThreeDot3Dot7AddressReferenceID(BaseModel):
    dot_tag: Annotated[ThreeDot3Dot7AddressReferenceIDTag, pydantic.Field(alias=".tag")]
    r"""The type of address reference"""

    id: str
    r"""The address's ID"""
