"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_amount import ThreeDot3Dot7Amount, ThreeDot3Dot7AmountTypedDict
from .threedot_3dot_7_cart_discount import (
    ThreeDot3Dot7CartDiscount,
    ThreeDot3Dot7CartDiscountTypedDict,
)
from .threedot_3dot_7_cart_item import (
    ThreeDot3Dot7CartItem,
    ThreeDot3Dot7CartItemTypedDict,
)
from .threedot_3dot_7_cart_shipment import (
    ThreeDot3Dot7CartShipment,
    ThreeDot3Dot7CartShipmentTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7CartTypedDict(TypedDict):
    order_reference: str
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""
    total: ThreeDot3Dot7AmountTypedDict
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""
    tax: ThreeDot3Dot7AmountTypedDict
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""
    order_description: NotRequired[str]
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""
    display_id: NotRequired[str]
    r"""A shopper-facing identifier corresponding to the order reference associated with this transaction."""
    shipments: NotRequired[List[ThreeDot3Dot7CartShipmentTypedDict]]
    discounts: NotRequired[List[ThreeDot3Dot7CartDiscountTypedDict]]
    items: NotRequired[List[ThreeDot3Dot7CartItemTypedDict]]


class ThreeDot3Dot7Cart(BaseModel):
    order_reference: str
    r"""This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction."""

    total: ThreeDot3Dot7Amount
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    tax: ThreeDot3Dot7Amount
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    order_description: Optional[str] = None
    r"""Used optionally to pass additional information like order numbers or other IDs as needed."""

    display_id: Optional[str] = None
    r"""A shopper-facing identifier corresponding to the order reference associated with this transaction."""

    shipments: Optional[List[ThreeDot3Dot7CartShipment]] = None

    discounts: Optional[List[ThreeDot3Dot7CartDiscount]] = None

    items: Optional[List[ThreeDot3Dot7CartItem]] = None
