"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_credit_card_network import ThreeDot3Dot7CreditCardNetwork
from bolt_api_sdk.types import BaseModel
from datetime import datetime
from typing_extensions import TypedDict


class ThreeDot3Dot7TestCreditCardTypedDict(TypedDict):
    network: ThreeDot3Dot7CreditCardNetwork
    r"""The credit card's network."""
    bin: str
    r"""The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number."""
    last4: str
    r"""The account number's last four digits."""
    expiration: datetime
    r"""The token's expiration date. Tokens used past their expiration will be rejected."""
    token: str
    r"""The Bolt token associated with the credit card."""


class ThreeDot3Dot7TestCreditCard(BaseModel):
    network: ThreeDot3Dot7CreditCardNetwork
    r"""The credit card's network."""

    bin: str
    r"""The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number."""

    last4: str
    r"""The account number's last four digits."""

    expiration: datetime
    r"""The token's expiration date. Tokens used past their expiration will be rejected."""

    token: str
    r"""The Bolt token associated with the credit card."""
