"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_transaction_authorization import (
    ThreeDot3Dot7TransactionAuthorization,
    ThreeDot3Dot7TransactionAuthorizationTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7TransactionTypedDict(TypedDict):
    reference: NotRequired[str]
    authorizations: NotRequired[List[ThreeDot3Dot7TransactionAuthorizationTypedDict]]
    r"""Payment authorization events attached to a transaction"""


class ThreeDot3Dot7Transaction(BaseModel):
    reference: Optional[str] = None

    authorizations: Optional[List[ThreeDot3Dot7TransactionAuthorization]] = None
    r"""Payment authorization events attached to a transaction"""
