"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_address_reference_explicit import (
    ThreeDot3Dot7AddressReferenceExplicitInput,
    ThreeDot3Dot7AddressReferenceExplicitInputTypedDict,
)
from .threedot_3dot_7_address_reference_id import (
    ThreeDot3Dot7AddressReferenceID,
    ThreeDot3Dot7AddressReferenceIDTypedDict,
)
from bolt_api_sdk.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


ThreeDot3Dot7AddressReferenceInputTypedDict = TypeAliasType(
    "ThreeDot3Dot7AddressReferenceInputTypedDict",
    Union[
        ThreeDot3Dot7AddressReferenceIDTypedDict,
        ThreeDot3Dot7AddressReferenceExplicitInputTypedDict,
    ],
)


ThreeDot3Dot7AddressReferenceInput = Annotated[
    Union[
        Annotated[ThreeDot3Dot7AddressReferenceID, Tag("id")],
        Annotated[ThreeDot3Dot7AddressReferenceExplicitInput, Tag("explicit")],
    ],
    Discriminator(lambda m: get_discriminator(m, "dot_tag", ".tag")),
]
