"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_processor_response import (
    ThreeDot3Dot7ProcessorResponse,
    ThreeDot3Dot7ProcessorResponseTypedDict,
)
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7TransactionAuthorizationTypedDict(TypedDict):
    processor_reference: NotRequired[str]
    processor_response: NotRequired[ThreeDot3Dot7ProcessorResponseTypedDict]
    r"""Raw authorization response from the payment processor"""


class ThreeDot3Dot7TransactionAuthorization(BaseModel):
    processor_reference: Optional[str] = None

    processor_response: Optional[ThreeDot3Dot7ProcessorResponse] = None
    r"""Raw authorization response from the payment processor"""
