"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThreeDot3Dot7PaymentResponsePendingTag(str, Enum):
    PENDING = "pending"


class ThreeDot3Dot7PaymentResponsePendingStatus(str, Enum):
    AWAITING_USER_CONFIRMATION = "awaiting_user_confirmation"


class ThreeDot3Dot7PaymentResponsePendingAction(str, Enum):
    REDIRECT = "redirect"


class ThreeDot3Dot7PaymentResponsePendingTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentResponsePendingTag
    status: ThreeDot3Dot7PaymentResponsePendingStatus
    action: ThreeDot3Dot7PaymentResponsePendingAction
    url: str
    id: NotRequired[str]


class ThreeDot3Dot7PaymentResponsePending(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentResponsePendingTag, pydantic.Field(alias=".tag")
    ]

    status: ThreeDot3Dot7PaymentResponsePendingStatus

    action: ThreeDot3Dot7PaymentResponsePendingAction

    url: str

    id: Optional[str] = None
