"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodAffirmTag(str, Enum):
    AFFIRM = "affirm"


class ThreeDot3Dot7PaymentMethodAffirmOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodAffirmTag


class ThreeDot3Dot7PaymentMethodAffirmOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodAffirmTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodAffirmTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodAffirmTag
    return_url: str
    r"""Return URL to return to after payment completion in Affirm."""


class ThreeDot3Dot7PaymentMethodAffirm(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodAffirmTag, pydantic.Field(alias=".tag")
    ]

    return_url: str
    r"""Return URL to return to after payment completion in Affirm."""
