"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodKlarnaPaynowTag(str, Enum):
    KLARNA_PAYNOW = "klarna_paynow"


class ThreeDot3Dot7PaymentMethodKlarnaPaynowOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaPaynowTag


class ThreeDot3Dot7PaymentMethodKlarnaPaynowOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaPaynowTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodKlarnaPaynowTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaPaynowTag
    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""


class ThreeDot3Dot7PaymentMethodKlarnaPaynow(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaPaynowTag, pydantic.Field(alias=".tag")
    ]

    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""
