"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ThreeDot3Dot7FieldErrorTag(str, Enum):
    r"""The type of error returned"""

    INVALID_INPUT_PARAMETER = "invalid_input_parameter"
