"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_transaction import (
    ThreeDot3Dot7Transaction,
    ThreeDot3Dot7TransactionTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThreeDot3Dot7PaymentResponseFinalizedTag(str, Enum):
    FINALIZED = "finalized"


class ThreeDot3Dot7PaymentResponseFinalizedStatus(str, Enum):
    SUCCESS = "success"


class ThreeDot3Dot7PaymentResponseFinalizedTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentResponseFinalizedTag
    status: ThreeDot3Dot7PaymentResponseFinalizedStatus
    transaction: ThreeDot3Dot7TransactionTypedDict
    id: NotRequired[str]


class ThreeDot3Dot7PaymentResponseFinalized(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentResponseFinalizedTag, pydantic.Field(alias=".tag")
    ]

    status: ThreeDot3Dot7PaymentResponseFinalizedStatus

    transaction: ThreeDot3Dot7Transaction

    id: Optional[str] = None
