"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing_extensions import Annotated, TypedDict


class ThreeDot3Dot7PaymentMethodKlarnaAccountTag(str, Enum):
    KLARNA_ACCOUNT = "klarna_account"


class ThreeDot3Dot7PaymentMethodKlarnaAccountOutputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaAccountTag


class ThreeDot3Dot7PaymentMethodKlarnaAccountOutput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaAccountTag, pydantic.Field(alias=".tag")
    ]


class ThreeDot3Dot7PaymentMethodKlarnaAccountTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7PaymentMethodKlarnaAccountTag
    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""


class ThreeDot3Dot7PaymentMethodKlarnaAccount(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7PaymentMethodKlarnaAccountTag, pydantic.Field(alias=".tag")
    ]

    return_url: str
    r"""Return URL to return to after payment completion in Klarna."""
