"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ThreeDot3Dot7ErrorTag(str, Enum):
    r"""The type of error returned"""

    UNAUTHORIZED = "unauthorized"
    FORBIDDEN = "forbidden"
    UNPROCESSABLE_REQUEST = "unprocessable_request"
    NOT_FOUND = "not_found"
