"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_payment_method_affirm_output import (
    ThreeDot3Dot7PaymentMethodAffirmOutput,
    ThreeDot3Dot7PaymentMethodAffirmOutputTypedDict,
)
from .threedot_3dot_7_payment_method_afterpay_output import (
    ThreeDot3Dot7PaymentMethodAfterpayOutput,
    ThreeDot3Dot7PaymentMethodAfterpayOutputTypedDict,
)
from .threedot_3dot_7_payment_method_credit_card_output import (
    ThreeDot3Dot7PaymentMethodCreditCardOutput,
    ThreeDot3Dot7PaymentMethodCreditCardOutputTypedDict,
)
from .threedot_3dot_7_payment_method_klarna_account_output import (
    ThreeDot3Dot7PaymentMethodKlarnaAccountOutput,
    ThreeDot3Dot7PaymentMethodKlarnaAccountOutputTypedDict,
)
from .threedot_3dot_7_payment_method_klarna_output import (
    ThreeDot3Dot7PaymentMethodKlarnaOutput,
    ThreeDot3Dot7PaymentMethodKlarnaOutputTypedDict,
)
from .threedot_3dot_7_payment_method_klarna_paynow_output import (
    ThreeDot3Dot7PaymentMethodKlarnaPaynowOutput,
    ThreeDot3Dot7PaymentMethodKlarnaPaynowOutputTypedDict,
)
from .threedot_3dot_7_payment_method_paypal_output import (
    ThreeDot3Dot7PaymentMethodPaypalOutput,
    ThreeDot3Dot7PaymentMethodPaypalOutputTypedDict,
)
from bolt_api_sdk.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


ThreeDot3Dot7PaymentMethodOutputTypedDict = TypeAliasType(
    "ThreeDot3Dot7PaymentMethodOutputTypedDict",
    Union[
        ThreeDot3Dot7PaymentMethodPaypalOutputTypedDict,
        ThreeDot3Dot7PaymentMethodAffirmOutputTypedDict,
        ThreeDot3Dot7PaymentMethodAfterpayOutputTypedDict,
        ThreeDot3Dot7PaymentMethodKlarnaOutputTypedDict,
        ThreeDot3Dot7PaymentMethodKlarnaAccountOutputTypedDict,
        ThreeDot3Dot7PaymentMethodKlarnaPaynowOutputTypedDict,
        ThreeDot3Dot7PaymentMethodCreditCardOutputTypedDict,
    ],
)


ThreeDot3Dot7PaymentMethodOutput = Annotated[
    Union[
        Annotated[ThreeDot3Dot7PaymentMethodCreditCardOutput, Tag("credit_card")],
        Annotated[ThreeDot3Dot7PaymentMethodPaypalOutput, Tag("paypal")],
        Annotated[ThreeDot3Dot7PaymentMethodAffirmOutput, Tag("affirm")],
        Annotated[ThreeDot3Dot7PaymentMethodAfterpayOutput, Tag("afterpay")],
        Annotated[ThreeDot3Dot7PaymentMethodKlarnaOutput, Tag("klarna")],
        Annotated[ThreeDot3Dot7PaymentMethodKlarnaAccountOutput, Tag("klarna_account")],
        Annotated[ThreeDot3Dot7PaymentMethodKlarnaPaynowOutput, Tag("klarna_paynow")],
    ],
    Discriminator(lambda m: get_discriminator(m, "dot_tag", ".tag")),
]
