"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_amount import ThreeDot3Dot7Amount, ThreeDot3Dot7AmountTypedDict
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7CartDiscountTypedDict(TypedDict):
    amount: ThreeDot3Dot7AmountTypedDict
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""
    code: NotRequired[str]
    r"""Discount code."""
    details_url: NotRequired[str]
    r"""Used to provide a link to additional details, such as a landing page, associated with the discount offering."""


class ThreeDot3Dot7CartDiscount(BaseModel):
    amount: ThreeDot3Dot7Amount
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    code: Optional[str] = None
    r"""Discount code."""

    details_url: Optional[str] = None
    r"""Used to provide a link to additional details, such as a landing page, associated with the discount offering."""
