"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_country_code import ThreeDot3Dot7CountryCode
from bolt_api_sdk.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThreeDot3Dot7AddressReferenceExplicitTag(str, Enum):
    r"""The type of address reference"""

    EXPLICIT = "explicit"


class ThreeDot3Dot7AddressReferenceExplicitTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7AddressReferenceExplicitTag
    r"""The type of address reference"""
    first_name: str
    r"""The first name of the person associated with this address."""
    last_name: str
    r"""The last name of the person associated with this address."""
    street_address1: str
    r"""The street address associated with this address."""
    locality: str
    r"""The locality (e.g. city, town, etc...) associated with this address."""
    postal_code: str
    r"""The postal code associated with this address."""
    country_code: ThreeDot3Dot7CountryCode
    r"""The country (in its ISO 3166 alpha-2 format) associated with this address."""
    id: NotRequired[str]
    r"""The address's unique identifier."""
    company: NotRequired[str]
    r"""The company associated with this address."""
    street_address2: NotRequired[str]
    r"""Any additional, optional, street address information associated with this address."""
    region: NotRequired[str]
    r"""The region or administrative area (e.g. state, province, county, etc...) associated with this address."""
    email: NotRequired[str]
    r"""The email address associated with this address."""
    phone: NotRequired[str]
    r"""The phone number associated with this address."""


class ThreeDot3Dot7AddressReferenceExplicit(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7AddressReferenceExplicitTag, pydantic.Field(alias=".tag")
    ]
    r"""The type of address reference"""

    first_name: str
    r"""The first name of the person associated with this address."""

    last_name: str
    r"""The last name of the person associated with this address."""

    street_address1: str
    r"""The street address associated with this address."""

    locality: str
    r"""The locality (e.g. city, town, etc...) associated with this address."""

    postal_code: str
    r"""The postal code associated with this address."""

    country_code: ThreeDot3Dot7CountryCode
    r"""The country (in its ISO 3166 alpha-2 format) associated with this address."""

    id: Optional[str] = None
    r"""The address's unique identifier."""

    company: Optional[str] = None
    r"""The company associated with this address."""

    street_address2: Optional[str] = None
    r"""Any additional, optional, street address information associated with this address."""

    region: Optional[str] = None
    r"""The region or administrative area (e.g. state, province, county, etc...) associated with this address."""

    email: Optional[str] = None
    r"""The email address associated with this address."""

    phone: Optional[str] = None
    r"""The phone number associated with this address."""


class ThreeDot3Dot7AddressReferenceExplicitInputTypedDict(TypedDict):
    dot_tag: ThreeDot3Dot7AddressReferenceExplicitTag
    r"""The type of address reference"""
    first_name: str
    r"""The first name of the person associated with this address."""
    last_name: str
    r"""The last name of the person associated with this address."""
    street_address1: str
    r"""The street address associated with this address."""
    locality: str
    r"""The locality (e.g. city, town, etc...) associated with this address."""
    postal_code: str
    r"""The postal code associated with this address."""
    country_code: ThreeDot3Dot7CountryCode
    r"""The country (in its ISO 3166 alpha-2 format) associated with this address."""
    company: NotRequired[str]
    r"""The company associated with this address."""
    street_address2: NotRequired[str]
    r"""Any additional, optional, street address information associated with this address."""
    region: NotRequired[str]
    r"""The region or administrative area (e.g. state, province, county, etc...) associated with this address."""
    email: NotRequired[str]
    r"""The email address associated with this address."""
    phone: NotRequired[str]
    r"""The phone number associated with this address."""


class ThreeDot3Dot7AddressReferenceExplicitInput(BaseModel):
    dot_tag: Annotated[
        ThreeDot3Dot7AddressReferenceExplicitTag, pydantic.Field(alias=".tag")
    ]
    r"""The type of address reference"""

    first_name: str
    r"""The first name of the person associated with this address."""

    last_name: str
    r"""The last name of the person associated with this address."""

    street_address1: str
    r"""The street address associated with this address."""

    locality: str
    r"""The locality (e.g. city, town, etc...) associated with this address."""

    postal_code: str
    r"""The postal code associated with this address."""

    country_code: ThreeDot3Dot7CountryCode
    r"""The country (in its ISO 3166 alpha-2 format) associated with this address."""

    company: Optional[str] = None
    r"""The company associated with this address."""

    street_address2: Optional[str] = None
    r"""Any additional, optional, street address information associated with this address."""

    region: Optional[str] = None
    r"""The region or administrative area (e.g. state, province, county, etc...) associated with this address."""

    email: Optional[str] = None
    r"""The email address associated with this address."""

    phone: Optional[str] = None
    r"""The phone number associated with this address."""
