"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_address_reference_input import (
    ThreeDot3Dot7AddressReferenceInput,
    ThreeDot3Dot7AddressReferenceInputTypedDict,
)
from .threedot_3dot_7_amount import ThreeDot3Dot7Amount, ThreeDot3Dot7AmountTypedDict
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7CartShipmentTypedDict(TypedDict):
    address: NotRequired[ThreeDot3Dot7AddressReferenceInputTypedDict]
    cost: NotRequired[ThreeDot3Dot7AmountTypedDict]
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""
    carrier: NotRequired[str]
    r"""The name of the carrier selected."""


class ThreeDot3Dot7CartShipment(BaseModel):
    address: Optional[ThreeDot3Dot7AddressReferenceInput] = None

    cost: Optional[ThreeDot3Dot7Amount] = None
    r"""A monetary amount, i.e. a base unit amount and a supported currency."""

    carrier: Optional[str] = None
    r"""The name of the carrier selected."""
