"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ThreeDot3Dot7CreditCardNetwork(str, Enum):
    r"""The credit card's network."""

    VISA = "visa"
    MASTERCARD = "mastercard"
    AMEX = "amex"
    DISCOVER = "discover"
    JCB = "jcb"
    DINERSCLUB = "dinersclub"
    UNIONPAY = "unionpay"
    ALLIANCEDATA = "alliancedata"
    CITIPLCC = "citiplcc"
