"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .threedot_3dot_7_address_listing import (
    ThreeDot3Dot7AddressListing,
    ThreeDot3Dot7AddressListingTypedDict,
)
from .threedot_3dot_7_payment_method_output import (
    ThreeDot3Dot7PaymentMethodOutput,
    ThreeDot3Dot7PaymentMethodOutputTypedDict,
)
from .threedot_3dot_7_profile import ThreeDot3Dot7Profile, ThreeDot3Dot7ProfileTypedDict
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ThreeDot3Dot7AccountTypedDict(TypedDict):
    addresses: List[ThreeDot3Dot7AddressListingTypedDict]
    r"""A list of addresses associated with this account. These can be considered the \"shipping addresses\". The account's visible addresses are filtered according to the configured shipping destinations in your Bolt merchant dashboard. If no account addresses are available, use the billing address of the selected payment method."""
    payment_methods: List[ThreeDot3Dot7PaymentMethodOutputTypedDict]
    r"""A list of payment methods associated with this account. The account's visible payment methods are filtered to include only cards that are chargeable."""
    profile: NotRequired[ThreeDot3Dot7ProfileTypedDict]
    r"""An account's identifying information."""


class ThreeDot3Dot7Account(BaseModel):
    addresses: List[ThreeDot3Dot7AddressListing]
    r"""A list of addresses associated with this account. These can be considered the \"shipping addresses\". The account's visible addresses are filtered according to the configured shipping destinations in your Bolt merchant dashboard. If no account addresses are available, use the billing address of the selected payment method."""

    payment_methods: List[ThreeDot3Dot7PaymentMethodOutput]
    r"""A list of payment methods associated with this account. The account's visible payment methods are filtered to include only cards that are chargeable."""

    profile: Optional[ThreeDot3Dot7Profile] = None
    r"""An account's identifying information."""
