"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import FieldMetadata
from enum import Enum
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThreeDot3Dot7AuthorizationCodeRequestScope(str, Enum):
    BOLT_ACCOUNT_MANAGE = "bolt.account.manage"
    BOLT_ACCOUNT_VIEW = "bolt.account.view"
    OPENID = "openid"


class ThreeDot3Dot7AuthorizationCodeRequestGrantType(str, Enum):
    r"""The type of OAuth 2.0 grant being utilized."""

    AUTHORIZATION_CODE = "authorization_code"


class ThreeDot3Dot7AuthorizationCodeRequestTypedDict(TypedDict):
    r"""Perform the initial token exchange, using the authorization code provided by Bolt's Login Modal."""

    client_id: str
    r"""The OAuth client ID, which corresponds to the merchant publishable key, which can be retrieved in your Merchant Dashboard."""
    client_secret: str
    r"""The OAuth client secret, which corresponds the merchant API key, which can be retrieved in your Merchant Dashboard."""
    scope: List[ThreeDot3Dot7AuthorizationCodeRequestScope]
    r"""The requested scopes. If the request is successful, the OAuth client will be able to perform operations requiring these scopes.
    https://help.bolt.com/developers/references/bolt-oauth/#scopes - OAuth Developer Reference
    """
    grant_type: ThreeDot3Dot7AuthorizationCodeRequestGrantType
    r"""The type of OAuth 2.0 grant being utilized."""
    code: str
    r"""Fetched value using OTP value from the Authorization Modal."""
    state: NotRequired[str]
    r"""A randomly generated string sent along with an authorization code. This must be included if provided. It is used to prevent cross-site request forgery (CSRF) attacks."""


class ThreeDot3Dot7AuthorizationCodeRequest(BaseModel):
    r"""Perform the initial token exchange, using the authorization code provided by Bolt's Login Modal."""

    client_id: Annotated[str, FieldMetadata(form=True)]
    r"""The OAuth client ID, which corresponds to the merchant publishable key, which can be retrieved in your Merchant Dashboard."""

    client_secret: Annotated[str, FieldMetadata(form=True)]
    r"""The OAuth client secret, which corresponds the merchant API key, which can be retrieved in your Merchant Dashboard."""

    scope: Annotated[
        List[ThreeDot3Dot7AuthorizationCodeRequestScope], FieldMetadata(form=True)
    ]
    r"""The requested scopes. If the request is successful, the OAuth client will be able to perform operations requiring these scopes.
    https://help.bolt.com/developers/references/bolt-oauth/#scopes - OAuth Developer Reference
    """

    grant_type: Annotated[
        ThreeDot3Dot7AuthorizationCodeRequestGrantType, FieldMetadata(form=True)
    ]
    r"""The type of OAuth 2.0 grant being utilized."""

    code: Annotated[str, FieldMetadata(form=True)]
    r"""Fetched value using OTP value from the Authorization Modal."""

    state: Annotated[Optional[str], FieldMetadata(form=True)] = None
    r"""A randomly generated string sent along with an authorization code. This must be included if provided. It is used to prevent cross-site request forgery (CSRF) attacks."""
