"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address_change_view import AddressChangeView, AddressChangeViewTypedDict
from .amount_view import AmountView, AmountViewTypedDict
from .consumer_summary_view import ConsumerSummaryView, ConsumerSummaryViewTypedDict
from .transaction_review_view import (
    TransactionReviewView,
    TransactionReviewViewTypedDict,
)
from .transaction_view import TransactionView, TransactionViewTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TransactionTimelineViewType(str, Enum):
    COMPLETED = "completed"
    AUTHORIZED = "authorized"
    REVIEW = "review"
    NOTE = "note"
    VOIDED = "voided"
    CAPTURED = "captured"
    CREDITED = "credited"
    ADDRESS_CHANGE = "address_change"


class TransactionTimelineViewTypedDict(TypedDict):
    address_change: NotRequired[AddressChangeViewTypedDict]
    amount: NotRequired[AmountViewTypedDict]
    consumer: NotRequired[ConsumerSummaryViewTypedDict]
    date_: NotRequired[float]
    note: NotRequired[str]
    review: NotRequired[TransactionReviewViewTypedDict]
    transaction: NotRequired[TransactionViewTypedDict]
    type: NotRequired[TransactionTimelineViewType]
    visibility: NotRequired[str]


class TransactionTimelineView(BaseModel):
    address_change: Optional[AddressChangeView] = None

    amount: Optional[AmountView] = None

    consumer: Optional[ConsumerSummaryView] = None

    date_: Annotated[Optional[float], pydantic.Field(alias="date")] = None

    note: Optional[str] = None

    review: Optional[TransactionReviewView] = None

    transaction: Optional[TransactionView] = None

    type: Optional[TransactionTimelineViewType] = None

    visibility: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "address_change",
                "amount",
                "consumer",
                "date",
                "note",
                "review",
                "transaction",
                "type",
                "visibility",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TransactionTimelineView.model_rebuild()
except NameError:
    pass
