"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .amount_view import AmountView, AmountViewTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
from enum import Enum
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TransactionSplitsViewType(str, Enum):
    NET = "net"
    PROCESSING_FEE = "processing_fee"
    FLOAT = "float"
    RESERVE = "reserve"
    ADJUSTMENT = "adjustment"
    BOLT_FEE = "bolt_fee"


class TransactionSplitsViewTypedDict(TypedDict):
    amount: NotRequired[AmountViewTypedDict]
    type: NotRequired[TransactionSplitsViewType]


class TransactionSplitsView(BaseModel):
    amount: Optional[AmountView] = None

    type: Optional[TransactionSplitsViewType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["amount", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
