"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .risk_model_result_view import RiskModelResultView, RiskModelResultViewTypedDict
from bolt_api_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TransactionReviewViewTypedDict(TypedDict):
    date_: NotRequired[float]
    decision: NotRequired[str]
    risk_model_result: NotRequired[RiskModelResultViewTypedDict]
    source: NotRequired[str]


class TransactionReviewView(BaseModel):
    date_: Annotated[Optional[float], pydantic.Field(alias="date")] = None

    decision: Optional[str] = None

    risk_model_result: Optional[RiskModelResultView] = None

    source: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["date", "decision", "risk_model_result", "source"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TransactionReviewView.model_rebuild()
except NameError:
    pass
