"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from bolt_api_sdk.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UnpauseSubscriptionRequestTypedDict(TypedDict):
    subscription_id: str
    r"""The unique ID for the subscription."""
    x_publishable_key: str
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard."""


class UnpauseSubscriptionRequest(BaseModel):
    subscription_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique ID for the subscription."""

    x_publishable_key: Annotated[
        str,
        pydantic.Field(alias="X-Publishable-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard."""
