"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class V1ErrorReasonTypedDict(TypedDict):
    r"""The reason for the error."""

    reason: NotRequired[str]


class V1ErrorReason(BaseModel):
    r"""The reason for the error."""

    reason: Optional[str] = None
