"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v1_errorreason import V1ErrorReason, V1ErrorReasonTypedDict
from bolt_api_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class V1ErrorTypedDict(TypedDict):
    code: NotRequired[int]
    r"""This is an error code."""
    data: NotRequired[List[V1ErrorReasonTypedDict]]


class V1Error(BaseModel):
    code: Optional[int] = None
    r"""This is an error code."""

    data: Optional[List[V1ErrorReason]] = None
