"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from typing_extensions import TypedDict


class V1PaymentMethodTypedDict(TypedDict):
    card_last_4: str
    card_network: str


class V1PaymentMethod(BaseModel):
    card_last_4: str

    card_network: str
