"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v1_subscriptionstatus import V1SubscriptionStatus
from bolt_api_sdk.types import BaseModel
from datetime import datetime
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class V1SubscriptionOrderTypedDict(TypedDict):
    id: NotRequired[str]
    r"""unique identifier for the subscription order."""
    subscription_id: NotRequired[str]
    r"""ID of the subscription associated with the order."""
    order_id: NotRequired[str]
    r"""ID of the order."""
    placement_time: NotRequired[datetime]
    status: NotRequired[V1SubscriptionStatus]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]


class V1SubscriptionOrder(BaseModel):
    id: Optional[str] = None
    r"""unique identifier for the subscription order."""

    subscription_id: Optional[str] = None
    r"""ID of the subscription associated with the order."""

    order_id: Optional[str] = None
    r"""ID of the order."""

    placement_time: Optional[datetime] = None

    status: Optional[V1SubscriptionStatus] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None
