"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing_extensions import TypedDict


class V1WebhookSuccessStatus(str, Enum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class V1WebhookSuccessTypedDict(TypedDict):
    r"""Webhooks Subscription Response"""

    status: V1WebhookSuccessStatus


class V1WebhookSuccess(BaseModel):
    r"""Webhooks Subscription Response"""

    status: V1WebhookSuccessStatus
