"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v1_subscriptionresponse import (
    V1SubscriptionResponse,
    V1SubscriptionResponseTypedDict,
)
from bolt_api_sdk.types import BaseModel
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class V1WebhookBodyType(str, Enum):
    SUBSCRIPTION_CREATED = "subscription_created"
    SUBSCRIPTION_RENEWED = "subscription_renewed"
    SUBSCRIPTION_CANCELED = "subscription_canceled"


class Object(str, Enum):
    SUBSCRIPTION = "subscription"


class V1WebhookBodyTypedDict(TypedDict):
    type: NotRequired[V1WebhookBodyType]
    object: NotRequired[Object]
    data: NotRequired[V1SubscriptionResponseTypedDict]


class V1WebhookBody(BaseModel):
    type: Optional[V1WebhookBodyType] = None

    object: Optional[Object] = None

    data: Optional[V1SubscriptionResponse] = None
